<?php

namespace Database\Seeders\ProductData;

class AccessoryData
{
    public static function get(): array
    {
        return array_merge(
            self::dockingStations(),
            self::laptopBags(),
            self::deskAccessories(),
            self::upsPower(),
        );
    }

    private static function dockingStations(): array
    {
        return [
            ['sku'=>'TH-DS-001','name'=>'CalDigit TS4 Thunderbolt 4 Dock','brand'=>'Belkin','category'=>'docking-stations','price'=>399.00,'special_price'=>null,'weight'=>0.54,'stock'=>22,'new'=>0,'featured'=>1,'short_description'=>'CalDigit TS4 — 18 ports including 2× Thunderbolt 4 downstream, 98W host charging and 2× 2.5G Ethernet.','description'=>'<p>TS4 is widely considered the best Thunderbolt 4 dock for Mac and Windows. 18 ports include dual 2.5G Ethernet ports for separate networks (wired LAN + NAS backup), 2 downstream Thunderbolt 4 ports for daisy-chaining monitors and devices, and 98W host charging for 14" or 16" MacBook Pro. A single Thunderbolt 4 cable replaces 18 individual connections.</p><ul><li><strong>Host:</strong> 1× Thunderbolt 4 (upstream, 98W charging)</li><li><strong>Downstream TB4:</strong> 2× Thunderbolt 4 (40Gbps)</li><li><strong>USB-A:</strong> 5× USB-A 3.2 Gen 2 (10Gbps)</li><li><strong>Ethernet:</strong> 2× 2.5G RJ45</li><li><strong>Display:</strong> 2× DisplayPort 1.4, 1× DisplayPort 1.2</li><li><strong>Audio:</strong> 3.5mm combo jack</li><li><strong>Total Ports:</strong> 18</li></ul>'],
            ['sku'=>'TH-DS-002','name'=>'Anker 777 Thunderbolt 4 Dock (13-in-1)','brand'=>'Anker','category'=>'docking-stations','price'=>249.00,'special_price'=>219.00,'weight'=>0.39,'stock'=>37,'new'=>1,'featured'=>0,'short_description'=>'Anker 777 Thunderbolt 4 Dock — 13 ports, 90W charging, 4K 60Hz dual display for MacBook and Windows.','description'=>'<p>Anker 777 is the value Thunderbolt 4 dock for users who want maximum connectivity without paying CalDigit prices. 13 ports include 2× 10Gbps USB-A, 2× Thunderbolt 4 downstream, HDMI 2.1, and 90W host charging. Solid aluminium build matches MacBook aesthetic, and the vertical stand orientation saves desk space.</p><ul><li><strong>Host:</strong> 1× Thunderbolt 4 (upstream, 90W charging)</li><li><strong>Downstream TB4:</strong> 1× Thunderbolt 4 downstream</li><li><strong>USB-A:</strong> 4× USB-A 3.2</li><li><strong>Ethernet:</strong> 1× Gigabit</li><li><strong>Display:</strong> 1× HDMI 2.1 + 1× DP via TB4</li><li><strong>Total Ports:</strong> 13</li></ul>'],
            ['sku'=>'TH-DS-003','name'=>'Dell WD22TB4 Thunderbolt 4 Dock','brand'=>'Dell','category'=>'docking-stations','price'=>299.00,'special_price'=>null,'weight'=>0.55,'stock'=>18,'new'=>0,'featured'=>0,'short_description'=>'Dell WD22TB4 — official Dell Thunderbolt 4 dock with 130W charging for Dell XPS and Precision laptops.','description'=>'<p>WD22TB4 is Dell\'s official Thunderbolt 4 docking solution, certified for Dell XPS, Inspiron, and Precision laptops with 130W host charging — enough for the most power-hungry Dell laptops. Dell Peripheral Manager software manages connected peripherals and updates dock firmware automatically.</p><ul><li><strong>Host:</strong> 1× Thunderbolt 4 (130W charging)</li><li><strong>USB-A:</strong> 4× USB-A 3.2</li><li><strong>USB-C:</strong> 1× USB-C 3.2</li><li><strong>Ethernet:</strong> 1× 2.5G</li><li><strong>Display:</strong> 2× DisplayPort 1.4</li><li><strong>Audio:</strong> 3.5mm combo</li><li><strong>Max Displays:</strong> 3× 4K 60Hz</li></ul>'],
            ['sku'=>'TH-DS-004','name'=>'Belkin Connect Pro 12-in-1 USB-C Hub','brand'=>'Belkin','category'=>'docking-stations','price'=>149.00,'special_price'=>null,'weight'=>0.27,'stock'=>53,'new'=>0,'featured'=>0,'short_description'=>'Belkin 12-in-1 USB-C hub — 100W PD passthrough, HDMI 4K, Ethernet and 7 data ports in one slim unit.','description'=>'<p>Belkin Connect Pro 12-in-1 is the portable dock for travellers — light enough to pack alongside a laptop, with enough ports to replace the laptop bag full of individual adapters. 100W PD passthrough charges most laptops at full speed while the hub is in use. HDMI 4K 30Hz and USB-C 4K 60Hz provide dual external display connectivity.</p><ul><li><strong>USB-C PD:</strong> 100W host passthrough</li><li><strong>Display:</strong> 1× HDMI 4K 30Hz + 1× USB-C 4K 60Hz</li><li><strong>USB-A:</strong> 4× USB-A 3.2 Gen 1</li><li><strong>Ethernet:</strong> 1× Gigabit</li><li><strong>Card Reader:</strong> SD + microSD</li><li><strong>Connection:</strong> USB-C (cable attached)</li></ul>'],
            ['sku'=>'TH-DS-005','name'=>'Anker 552 USB-C Hub (9-in-1)','brand'=>'Anker','category'=>'docking-stations','price'=>49.00,'special_price'=>null,'weight'=>0.13,'stock'=>88,'new'=>0,'featured'=>0,'short_description'=>'Anker 9-in-1 USB-C Hub — 4K 60Hz HDMI, 85W PD passthrough and SD card reader for everyday portability.','description'=>'<p>Anker 552 is the practical everyday USB-C hub for MacBook and iPad Pro users who need more ports without the expense of a Thunderbolt dock. 4K 60Hz HDMI connects a single 4K monitor, 85W PD passthrough charges the laptop, and the compact form factor attaches cleanly to the side of the MacBook.</p><ul><li><strong>USB-C PD:</strong> 85W passthrough</li><li><strong>Display:</strong> 1× HDMI 4K 60Hz</li><li><strong>USB-A:</strong> 2× USB-A 3.0</li><li><strong>USB-C:</strong> 2× USB-C data (5Gbps)</li><li><strong>Card Reader:</strong> SD + microSD</li></ul>'],
        ];
    }

    private static function laptopBags(): array
    {
        return [
            ['sku'=>'TH-LB-001','name'=>'Bellroy Classic Backpack Compact (20L)','brand'=>'Anker','category'=>'laptop-bags','price'=>199.00,'special_price'=>null,'weight'=>0.72,'stock'=>34,'new'=>0,'featured'=>1,'short_description'=>'Bellroy Classic Backpack Compact — premium woven recycled fabric, fits 16" laptop and carry-on friendly.','description'=>'<p>Bellroy Classic Backpack Compact is designed for people who commute daily and travel frequently. The 20L volume is perfectly sized for an overhead locker or under-seat storage, while the internal organisation provides dedicated slots for a laptop (up to 16"), tablet, chargers, and documents without needing to unpack at security.</p><ul><li><strong>Capacity:</strong> 20L</li><li><strong>Laptop:</strong> Up to 16" (padded sleeve)</li><li><strong>Material:</strong> Recycled woven twill (water resistant)</li><li><strong>Carry-on:</strong> Airline compliant size</li><li><strong>Organisation:</strong> Laptop sleeve, tablet pocket, accessory pockets</li></ul>'],
            ['sku'=>'TH-LB-002','name'=>'Targus CitySmart 15.6" Laptop Backpack','brand'=>'Anker','category'=>'laptop-bags','price'=>79.00,'special_price'=>null,'weight'=>0.53,'stock'=>61,'new'=>0,'featured'=>0,'short_description'=>'Targus CitySmart 15.6" — adjustable dividers, USB-A charging port and trolley sleeve for business travel.','description'=>'<p>CitySmart is the versatile business backpack for commuters and travellers. The Air Protect system uses a floating suspended panel to keep the laptop isolated from the bag frame during impacts. A pass-through trolley sleeve slides over upright luggage handles for hands-free airport navigation.</p><ul><li><strong>Laptop:</strong> Up to 15.6"</li><li><strong>Capacity:</strong> 22L</li><li><strong>External USB-A:</strong> Yes (connect powerbank inside)</li><li><strong>Trolley:</strong> Luggage pass-through strap</li><li><strong>Protection:</strong> Air Protect system</li></ul>'],
            ['sku'=>'TH-LB-003','name'=>'Incase ICON Pack 15" MacBook Backpack','brand'=>'Anker','category'=>'laptop-bags','price'=>139.00,'special_price'=>null,'weight'=>0.68,'stock'=>27,'new'=>0,'featured'=>0,'short_description'=>'Incase ICON Pack — Apple exclusive design, fleece-lined 15" MacBook slot and CabLock organiser.','description'=>'<p>ICON Pack is designed specifically for MacBook users — the fleece-lined dedicated sleeve holds 15" MacBook Pro snugly without a zipper to scratch the lid. CabLock side loops anchor cables while ports are in use, and the luggage pass-through strap attaches to rolling luggage handle. Available in a colour palette that matches MacBook finishes.</p><ul><li><strong>Laptop:</strong> 15" MacBook (fleece-lined sleeve)</li><li><strong>CabLock:</strong> Cable management loops</li><li><strong>Trolley:</strong> Luggage pass-through</li><li><strong>Material:</strong> Recycled polyester</li></ul>'],
            ['sku'=>'TH-LB-004','name'=>'Waterfield Designs CitySlicker 14" Laptop Sleeve','brand'=>'Anker','category'=>'laptop-bags','price'=>129.00,'special_price'=>null,'weight'=>0.26,'stock'=>19,'new'=>0,'featured'=>0,'short_description'=>'Waterfield CitySlicker 14" sleeve — hand-crafted US leather and neoprene with magnetic closure.','description'=>'<p>CitySlicker is hand-made in San Francisco using full-grain leather exterior and neoprene interior. The magnetic closure allows one-handed opening and closing while walking. A second neoprene-lined compartment stores chargers and cables alongside the laptop. Custom monogramming available at checkout.</p><ul><li><strong>Laptop:</strong> 13–14" (laptop only, no handle)</li><li><strong>Material:</strong> Full-grain leather + neoprene</li><li><strong>Closure:</strong> Magnetic snap</li><li><strong>Made in:</strong> San Francisco, USA</li><li><strong>Custom:</strong> Monogramming available</li></ul>'],
            ['sku'=>'TH-LB-005','name'=>'Knomo Beauchamp 15.6" Laptop Briefcase','brand'=>'Anker','category'=>'laptop-bags','price'=>159.00,'special_price'=>139.00,'weight'=>0.72,'stock'=>23,'new'=>0,'featured'=>0,'short_description'=>'Knomo Beauchamp 15.6" — water-resistant PU exterior with RFID blocking passport pocket and detachable strap.','description'=>'<p>Beauchamp combines briefcase professionalism with modern practicality. The RFID-blocking passport and card holder protects contactless payment cards in busy public transit, while the quick-access front pocket holds phone and keys. Detachable shoulder strap converts between briefcase and messenger carry styles.</p><ul><li><strong>Laptop:</strong> Up to 15.6" (padded sleeve)</li><li><strong>RFID:</strong> Blocking card holder built-in</li><li><strong>Carry:</strong> Top handle + detachable shoulder strap</li><li><strong>Material:</strong> Water-resistant PU leather</li><li><strong>Trolley:</strong> Luggage pass-through</li></ul>'],
        ];
    }

    private static function deskAccessories(): array
    {
        return [
            ['sku'=>'TH-DA-001','name'=>'Ergotron LX Monitor Arm (Single)','brand'=>'Belkin','category'=>'desk-accessories','price'=>199.00,'special_price'=>null,'weight'=>3.60,'stock'=>38,'new'=>0,'featured'=>1,'short_description'=>'Ergotron LX Monitor Arm — height, tilt, swivel and rotation in 6 axes, holds monitors up to 25kg.','description'=>'<p>Ergotron LX is the benchmark for monitor arms, offering frictionless positioning in every axis — height, depth, tilt, pan, and portrait/landscape rotation. The Constant Force mechanism means the monitor stays exactly where you place it without drift, and frees up the entire footprint of a traditional monitor stand for cable management and desk space.</p><ul><li><strong>VESA:</strong> 75×75 and 100×100mm</li><li><strong>Weight Capacity:</strong> 3.2–11.3 kg (7–25 lbs)</li><li><strong>Adjustment:</strong> Height, depth, tilt ±90°, pan 360°</li><li><strong>Reach:</strong> 25-inch extension from post</li><li><strong>Clamp:</strong> Desk clamp (up to 76mm thick)</li></ul>'],
            ['sku'=>'TH-DA-002','name'=>'Logitech MX Desk Mat Extended (Extended)','brand'=>'Logitech','category'=>'desk-accessories','price'=>49.00,'special_price'=>null,'weight'=>0.65,'stock'=>73,'new'=>0,'featured'=>0,'short_description'=>'Logitech MX Extended Desk Mat — 900×400mm premium micro-textured surface for keyboard and mouse.','description'=>'<p>MX Desk Mat uses a micro-textured surface tuned for Logitech\'s high-DPI mouse sensors while also providing a comfortable typing surface for keyboards. The 900×400mm extended format covers keyboard, mouse, and space for a water bottle or coffee cup. Non-slip rubber base prevents the mat from shifting during use.</p><ul><li><strong>Dimensions:</strong> 900 × 400 × 2mm</li><li><strong>Surface:</strong> Micro-textured polyester blend</li><li><strong>Tracking:</strong> Compatible with all Logitech optical sensors</li><li><strong>Base:</strong> Non-slip rubber</li><li><strong>Edge:</strong> Stitched anti-fray edging</li></ul>'],
            ['sku'=>'TH-DA-003','name'=>'Anker 675 USB-C Docking Station (Magnetic Desktop)','brand'=>'Anker','category'=>'desk-accessories','price'=>199.00,'special_price'=>null,'weight'=>0.88,'stock'=>24,'new'=>1,'featured'=>0,'short_description'=>'Anker 675 Magnetic Desktop Docking Station — vertical stand that MagSafe-attaches to MacBook, 12-in-1 USB-C.','description'=>'<p>Anker 675 uses magnetic attachment to connect to the side of an M-series MacBook, eliminating the dangling USB-C hub concept entirely. The desktop stand doubles as the hub body — MacBook sits vertically in the magnetic dock, with all 12 ports accessible from the rear and side. Compatible with MacBook Air M1/M2/M3 and MacBook Pro 14".</p><ul><li><strong>Compatibility:</strong> MacBook Air M1/M2/M3, MacBook Pro 14"</li><li><strong>Attachment:</strong> Magnetic side mount</li><li><strong>Host PD:</strong> 100W passthrough</li><li><strong>Ports:</strong> 12-in-1 (HDMI, USB-A, USB-C, Ethernet, SD)</li></ul>'],
            ['sku'=>'TH-DA-004','name'=>'Cable Matters 10G USB-C Hub with Card Reader','brand'=>'Anker','category'=>'desk-accessories','price'=>39.00,'special_price'=>null,'weight'=>0.11,'stock'=>64,'new'=>0,'featured'=>0,'short_description'=>'Cable Matters 7-in-1 USB-C hub — 10Gbps data, 4K 60Hz HDMI and UHS-II SD card reader.','description'=>'<p>Cable Matters provides the highest USB-A data speeds (10Gbps Gen 2) and UHS-II card reader — the fastest SD card standard supporting speeds up to 312 MB/s for cameras using UHS-II cards. HDMI 4K 60Hz connectivity for a single external display. Compact travel-friendly design weighs 110g.</p><ul><li><strong>USB-A:</strong> 2× 10Gbps Gen 2</li><li><strong>USB-C PD:</strong> 100W passthrough</li><li><strong>Display:</strong> 1× HDMI 4K 60Hz</li><li><strong>Card Reader:</strong> UHS-II SD + microSD</li><li><strong>Weight:</strong> 110g</li></ul>'],
            ['sku'=>'TH-DA-005','name'=>'3M Anti-Glare Privacy Filter 27" (16:9)','brand'=>'Anker','category'=>'desk-accessories','price'=>99.00,'special_price'=>null,'weight'=>0.31,'stock'=>41,'new'=>0,'featured'=>0,'short_description'=>'3M Privacy Filter 27" widescreen — blocks side-viewing angles, reduces glare and cuts 99% UV light.','description'=>'<p>3M privacy filter limits screen visibility to 60° viewing angle — people beside you see only a darkened screen. The micro-louvre technology blocks side views while maintaining optimal colour and brightness for the user looking directly at the screen. The anti-glare front surface reduces ambient light reflections in bright offices. Easy slide-mount or adhesive installation.</p><ul><li><strong>Screen Size:</strong> 27" widescreen (16:9)</li><li><strong>Viewing Angle:</strong> 60° (±30° from centre)</li><li><strong>UV Blocking:</strong> 99%</li><li><strong>Anti-Glare:</strong> Yes</li><li><strong>Installation:</strong> Slide-mount tabs or adhesive strips</li></ul>'],
        ];
    }

    private static function upsPower(): array
    {
        return [
            ['sku'=>'TH-UP-001','name'=>'APC Back-UPS Pro 1500VA 900W Tower UPS','brand'=>'APC','category'=>'ups-power','price'=>249.00,'special_price'=>null,'weight'=>8.50,'stock'=>27,'new'=>0,'featured'=>1,'short_description'=>'APC BX1500M 1500VA 900W — 10 outlets, surge protection and AVR for PC, NAS and networking equipment.','description'=>'<p>Back-UPS Pro 1500VA provides 900W of pure sine wave battery backup to keep your workstation, NAS, or network equipment running through power outages. AVR (Automatic Voltage Regulation) stabilises fluctuating utility power without using battery, extending its life. PowerChute software initiates graceful shutdown of connected computers before the battery is exhausted.</p><ul><li><strong>VA/Watts:</strong> 1500VA / 900W</li><li><strong>Output:</strong> 10 outlets (8 battery + 2 surge only)</li><li><strong>Battery Backup Runtime:</strong> ~10 min at 50% load</li><li><strong>Waveform:</strong> Pure Sine Wave</li><li><strong>AVR:</strong> Yes (stabilises without using battery)</li><li><strong>Software:</strong> PowerChute for graceful shutdown</li></ul>'],
            ['sku'=>'TH-UP-002','name'=>'APC UPS 600VA Surge Protector Battery Backup','brand'=>'APC','category'=>'ups-power','price'=>89.00,'special_price'=>null,'weight'=>2.80,'stock'=>54,'new'=>0,'featured'=>0,'short_description'=>'APC 600VA desk UPS — 6 battery-backed outlets and 3 surge-only for home office and networking equipment.','description'=>'<p>APC 600VA is the entry-level battery backup for home office users who want to protect against short power outages and save open documents before shutdown. 9 total outlets (6 battery + 3 surge-only) serve a typical home office setup — desktop PC, monitor, router, and NAS simultaneously. Connect to PC via USB for automatic graceful shutdown via PowerChute software.</p><ul><li><strong>VA/Watts:</strong> 600VA / 360W</li><li><strong>Outlets:</strong> 6 battery + 3 surge-only</li><li><strong>Runtime:</strong> ~6 min at half load</li><li><strong>Connection:</strong> USB for PowerChute</li><li><strong>Surge Protection:</strong> Yes</li></ul>'],
            ['sku'=>'TH-UP-003','name'=>'APC Smart-UPS 1500VA 1000W Rack/Tower LCD','brand'=>'APC','category'=>'ups-power','price'=>699.00,'special_price'=>null,'weight'=>22.50,'stock'=>9,'new'=>0,'featured'=>0,'short_description'=>'APC Smart-UPS 1500VA rack/tower — true online double-conversion UPS for servers and networking equipment.','description'=>'<p>Smart-UPS 1500VA is a true online double-conversion UPS — all power is conditioned through the inverter 100% of the time, providing the cleanest power possible for sensitive network and server equipment. The LCD front panel displays all status metrics without needing to connect a PC. Rack or tower mounting in 2U.</p><ul><li><strong>VA/Watts:</strong> 1500VA / 1000W</li><li><strong>Type:</strong> Online double-conversion</li><li><strong>Outlets:</strong> 8× IEC C13</li><li><strong>Mounting:</strong> 2U rack or tower</li><li><strong>Management:</strong> SNMP/Web management card slot</li><li><strong>LCD:</strong> Yes</li></ul>'],
        ];
    }
}
