<?php

namespace Database\Seeders\ProductData;

class AudioData
{
    public static function get(): array
    {
        return array_merge(
            self::headphones(),
            self::earbuds(),
            self::gamingHeadsets(),
            self::speakers(),
        );
    }

    private static function headphones(): array
    {
        return [
            ['sku'=>'TH-HP-001','name'=>'Sony WH-1000XM5 Wireless Headphones','brand'=>'Sony','category'=>'headphones','price'=>399.00,'special_price'=>349.00,'weight'=>0.25,'stock'=>73,'new'=>0,'featured'=>1,'short_description'=>'Sony WH-1000XM5 — industry-leading ANC, 30-hour battery and exceptional call quality.','description'=>'<p>WH-1000XM5 sets the benchmark for consumer noise-cancelling headphones. Eight microphones and two processors work together to block more noise than any previous Sony headphone, while the finely-tuned 30mm drivers deliver warm, detailed sound for music, podcasts and calls.</p><ul><li><strong>Driver:</strong> 30mm dynamic</li><li><strong>ANC:</strong> Yes — 8 microphones, 2 processors</li><li><strong>Battery:</strong> 30 hours (ANC on), 3-min charge = 3 hours</li><li><strong>Codecs:</strong> LDAC, AAC, SBC</li><li><strong>Multipoint:</strong> Yes (2 devices)</li><li><strong>Weight:</strong> 250g</li><li><strong>Foldable:</strong> No</li></ul>'],
            ['sku'=>'TH-HP-002','name'=>'Bose QuietComfort Ultra Headphones','brand'=>'Bose','category'=>'headphones','price'=>429.00,'special_price'=>null,'weight'=>0.25,'stock'=>41,'new'=>1,'featured'=>1,'short_description'=>'Bose QuietComfort Ultra with Immersive Audio — world-class ANC and spatial audio for music and calls.','description'=>'<p>QuietComfort Ultra introduces Bose Immersive Audio, a spatial processing system that creates a concert-hall soundstage directly in the headphones — no HRTF measurements or app setup required. Combined with Bose\'s best-ever ANC and CustomTune microphone adaptation, it\'s the most complete headphone in Bose\'s history.</p><ul><li><strong>ANC:</strong> World-class, CustomTune adapts to your ear</li><li><strong>Spatial Audio:</strong> Bose Immersive Audio</li><li><strong>Battery:</strong> 24 hours (ANC on)</li><li><strong>Codecs:</strong> aptX Adaptive, AAC, SBC</li><li><strong>Multipoint:</strong> Yes (2 devices)</li><li><strong>Weight:</strong> 250g</li></ul>'],
            ['sku'=>'TH-HP-003','name'=>'Apple AirPods Max (USB-C)','brand'=>'Apple','category'=>'headphones','price'=>549.00,'special_price'=>null,'weight'=>0.39,'stock'=>28,'new'=>1,'featured'=>0,'short_description'=>'Apple AirPods Max with USB-C — computational audio, adaptive transparency, and Apple ecosystem integration.','description'=>'<p>AirPods Max deliver a premium listening experience that integrates seamlessly with Apple devices. The Apple H2 chip enables ultra-low latency audio, while Adaptive Transparency processes external sound in real time to create a natural, transparent soundscape without removing the headphones.</p><ul><li><strong>Chip:</strong> Apple H2</li><li><strong>ANC:</strong> Active Noise Cancellation</li><li><strong>Transparency:</strong> Adaptive Transparency</li><li><strong>Spatial Audio:</strong> Yes, with dynamic head tracking</li><li><strong>Battery:</strong> 20 hours (ANC on)</li><li><strong>Charging:</strong> USB-C</li><li><strong>Weight:</strong> 385g</li></ul>'],
            ['sku'=>'TH-HP-004','name'=>'Sennheiser HD 660S2 Open-Back Headphones','brand'=>'Sennheiser','category'=>'headphones','price'=>599.00,'special_price'=>499.00,'weight'=>0.26,'stock'=>17,'new'=>0,'featured'=>0,'short_description'=>'Sennheiser HD 660S2 open-back audiophile headphones — reference-class sound for home listening.','description'=>'<p>HD 660S2 is Sennheiser\'s definitive consumer audiophile headphone, featuring new 38mm transducers with improved bass extension over the original HD 660S. The open-back design creates a natural, spacious soundstage that closed-back headphones cannot replicate. Requires an amplifier for best results.</p><ul><li><strong>Driver:</strong> 38mm dynamic transducer</li><li><strong>Type:</strong> Open-back, over-ear</li><li><strong>Impedance:</strong> 300 Ω</li><li><strong>Frequency Response:</strong> 8–41,500 Hz</li><li><strong>THD:</strong> &lt;0.04% (1kHz, 100dB)</li><li><strong>Cable:</strong> Balanced 4.4mm + SE 6.35mm included</li><li><strong>Weight:</strong> 260g</li></ul>'],
            ['sku'=>'TH-HP-005','name'=>'Jabra Evolve2 85 UC Wireless Headset','brand'=>'Jabra','category'=>'headphones','price'=>449.00,'special_price'=>null,'weight'=>0.34,'stock'=>22,'new'=>0,'featured'=>0,'short_description'=>'Jabra Evolve2 85 UC — professional hybrid ANC headset with 10-mic call clarity and 37-hour battery.','description'=>'<p>Evolve2 85 is the gold standard for remote workers and professionals on video calls all day. Ten microphones filter background noise with professional precision — background coffee shop noise, HVAC systems, and keyboard typing disappear. Certified for Microsoft Teams, Zoom, and Google Meet.</p><ul><li><strong>Microphones:</strong> 10 (6 for ANC + 4 for calls)</li><li><strong>ANC:</strong> Advanced Hybrid ANC</li><li><strong>Battery:</strong> 37 hours (ANC on)</li><li><strong>Certifications:</strong> Microsoft Teams, Zoom, Google Meet</li><li><strong>Connectivity:</strong> Bluetooth 5.0, USB-A/USB-C dongle</li><li><strong>Multipoint:</strong> Yes (3 devices)</li></ul>'],
            ['sku'=>'TH-HP-006','name'=>'Sony WH-CH720N Lightweight ANC Headphones','brand'=>'Sony','category'=>'headphones','price'=>149.00,'special_price'=>119.00,'weight'=>0.19,'stock'=>58,'new'=>0,'featured'=>0,'short_description'=>'Sony WH-CH720N — lightest Sony ANC headphones at 192g with 35-hour battery and multipoint.','description'=>'<p>WH-CH720N is Sony\'s value ANC headphone, offering meaningful noise cancellation and impressive 35-hour battery in one of the lightest over-ear designs available at 192g. Multipoint connectivity lets you switch between phone and laptop with a single tap.</p><ul><li><strong>Driver:</strong> 30mm dynamic</li><li><strong>ANC:</strong> Yes, with ambient sound mode</li><li><strong>Battery:</strong> 35 hours (ANC on)</li><li><strong>Codecs:</strong> AAC, SBC</li><li><strong>Multipoint:</strong> Yes (2 devices)</li><li><strong>Weight:</strong> 192g (world\'s lightest Sony ANC headphone)</li></ul>'],
        ];
    }

    private static function earbuds(): array
    {
        return [
            ['sku'=>'TH-EB-001','name'=>'Apple AirPods Pro (2nd Gen) USB-C','brand'=>'Apple','category'=>'earbuds','price'=>249.00,'special_price'=>null,'weight'=>0.01,'stock'=>94,'new'=>1,'featured'=>1,'short_description'=>'AirPods Pro 2 USB-C with H2 chip — adaptive ANC, spatial audio, and new hearing aid features.','description'=>'<p>AirPods Pro 2nd gen USB-C adds Apple\'s new Hearing Aid feature (FDA-cleared) alongside the best ANC in any earbud. The H2 chip processes 48,000 computational audio adjustments per second for perfectly tuned sound in any environment. MagSafe and Apple Watch charging compatible.</p><ul><li><strong>Chip:</strong> Apple H2</li><li><strong>ANC:</strong> Adaptive Transparency, Active Noise Cancellation</li><li><strong>Spatial Audio:</strong> Personalised with head tracking</li><li><strong>Battery:</strong> 6 hours (ANC on) + 24 hours from case</li><li><strong>Charging:</strong> USB-C, MagSafe, Apple Watch charger</li><li><strong>IPX4:</strong> Earbuds and case</li></ul>'],
            ['sku'=>'TH-EB-002','name'=>'Sony WF-1000XM5 Wireless Earbuds','brand'=>'Sony','category'=>'earbuds','price'=>299.00,'special_price'=>249.00,'weight'=>0.01,'stock'=>52,'new'=>1,'featured'=>1,'short_description'=>'Sony WF-1000XM5 — best-in-class ANC earbuds with LDAC Hi-Res Audio and 8-hour battery.','description'=>'<p>WF-1000XM5 packs Sony\'s best ANC technology into the smallest, lightest case Sony has ever made. LDAC support enables Hi-Res Audio streaming over Bluetooth at up to 990kbps — 3× the data rate of standard Bluetooth — for audiophile-quality sound without wires.</p><ul><li><strong>Driver:</strong> 8.4mm dynamic</li><li><strong>ANC:</strong> Industry-leading, 4 microphones</li><li><strong>Battery:</strong> 8 hours (ANC on) + 24 hours with case</li><li><strong>Codecs:</strong> LDAC, AAC, SBC</li><li><strong>Multipoint:</strong> Yes (2 devices)</li><li><strong>IPX4:</strong> Yes</li></ul>'],
            ['sku'=>'TH-EB-003','name'=>'Jabra Evolve2 Buds UC Wireless Earbuds','brand'=>'Jabra','category'=>'earbuds','price'=>249.00,'special_price'=>null,'weight'=>0.01,'stock'=>31,'new'=>0,'featured'=>0,'short_description'=>'Jabra Evolve2 Buds UC — professional hybrid ANC earbuds certified for Microsoft Teams and Zoom.','description'=>'<p>Evolve2 Buds are the only professional-grade earbuds with 6 microphones and 4-mic Call ANC. Microsoft Teams Certified ensures they work seamlessly with Teams\' meeting controls, status indicators, and voice pickup optimisation. The compact charging pad also charges the supplied USB dongle simultaneously.</p><ul><li><strong>Microphones:</strong> 6 (4 for calls, 2 ANC)</li><li><strong>ANC:</strong> Hybrid ANC</li><li><strong>Battery:</strong> 8 hours + 23 hours case</li><li><strong>Certifications:</strong> Microsoft Teams, Zoom</li><li><strong>IPX54:</strong> Yes</li><li><strong>Charging:</strong> USB-C + wireless charging pad</li></ul>'],
            ['sku'=>'TH-EB-004','name'=>'Samsung Galaxy Buds3 Pro','brand'=>'Samsung','category'=>'earbuds','price'=>249.00,'special_price'=>219.00,'weight'=>0.01,'stock'=>44,'new'=>1,'featured'=>0,'short_description'=>'Samsung Galaxy Buds3 Pro with blade-style design — 360° audio, adaptive ANC and Galaxy integration.','description'=>'<p>Galaxy Buds3 Pro introduce Samsung\'s blade-style design for a secure, ergonomic fit. SSC HiFi codec (Samsung Seamless Codec High Fidelity) delivers lossless audio to compatible Galaxy devices, while 360° Audio with head tracking creates a spatial soundstage for music and movies.</p><ul><li><strong>Driver:</strong> 10.5mm woofer + 6.1mm tweeter (2-way)</li><li><strong>ANC:</strong> Adaptive ANC with three levels</li><li><strong>Codec:</strong> SSC HiFi (lossless), AAC, SBC</li><li><strong>Battery:</strong> 6 hours + 18 hours case</li><li><strong>IP57:</strong> Yes</li></ul>'],
            ['sku'=>'TH-EB-005','name'=>'Bose QuietComfort Earbuds II','brand'=>'Bose','category'=>'earbuds','price'=>279.00,'special_price'=>229.00,'weight'=>0.01,'stock'=>39,'new'=>0,'featured'=>0,'short_description'=>'Bose QC Earbuds II — CustomTune microphone measures your ear for personalised ANC and EQ.','description'=>'<p>QuietComfort Earbuds II use CustomTune technology — an internal microphone measures the acoustic properties of your ear canal and adjusts both ANC and EQ in real time. The result is more effective noise cancellation and better sound quality than earbuds using a one-size-fits-all approach.</p><ul><li><strong>ANC:</strong> Best-ever Bose, CustomTune personalisation</li><li><strong>Battery:</strong> 6 hours + 18 hours from case</li><li><strong>Codecs:</strong> AAC, SBC</li><li><strong>Multipoint:</strong> No</li><li><strong>IPX4:</strong> Yes</li><li><strong>Fit:</strong> StayHear Max ear tips (3 sizes)</li></ul>'],
        ];
    }

    private static function gamingHeadsets(): array
    {
        return [
            ['sku'=>'TH-GH-001','name'=>'SteelSeries Arctis Nova Pro Wireless','brand'=>'SteelSeries','category'=>'gaming-headsets','price'=>349.00,'special_price'=>null,'weight'=>0.34,'stock'=>27,'new'=>1,'featured'=>1,'short_description'=>'SteelSeries Arctis Nova Pro Wireless — hot-swappable batteries, ANC and Hi-Res audio for PC, PS5, mobile.','description'=>'<p>Arctis Nova Pro Wireless is the most feature-complete gaming headset available. Hot-swappable batteries mean you never have to pause mid-game to charge — swap the depleted battery for the pre-charged spare in the base station in seconds. ANC and Hi-Res Audio certification are firsts for any gaming headset.</p><ul><li><strong>Driver:</strong> 40mm Neodymium</li><li><strong>Wireless:</strong> 2.4 GHz + Bluetooth 5.0</li><li><strong>Battery:</strong> Dual hot-swap (20 hours each)</li><li><strong>ANC:</strong> Active Noise Cancellation</li><li><strong>Hi-Res Audio:</strong> Yes (Hi-Res certified)</li><li><strong>Multipoint:</strong> Yes (2 simultaneous)</li><li><strong>Platforms:</strong> PC, PS5, mobile, Nintendo Switch</li></ul>'],
            ['sku'=>'TH-GH-002','name'=>'Razer BlackShark V2 Pro (2023) Wireless','brand'=>'Razer','category'=>'gaming-headsets','price'=>199.00,'special_price'=>null,'weight'=>0.32,'stock'=>38,'new'=>1,'featured'=>0,'short_description'=>'Razer BlackShark V2 Pro 2023 — THX Spatial Audio, 70-hour battery and HyperClear Super Wideband mic.','description'=>'<p>BlackShark V2 Pro 2023 features Razer\'s HyperClear Super Wideband microphone — recording up to 20kHz to capture more voice nuance for team comms and streaming. THX Spatial Audio provides positional accuracy across 7.1 virtual channels on PC. 70-hour battery ensures it lasts a full week of daily gaming sessions.</p><ul><li><strong>Driver:</strong> 50mm Razer TriForce Titanium</li><li><strong>Wireless:</strong> Razer HyperSpeed 2.4 GHz</li><li><strong>Battery:</strong> 70 hours</li><li><strong>Microphone:</strong> HyperClear Super Wideband (20kHz)</li><li><strong>Spatial Audio:</strong> THX Spatial Audio (PC)</li><li><strong>Platforms:</strong> PC, PS5, mobile</li></ul>'],
            ['sku'=>'TH-GH-003','name'=>'Logitech G535 Lightspeed Wireless Headset','brand'=>'Logitech','category'=>'gaming-headsets','price'=>99.00,'special_price'=>79.00,'weight'=>0.23,'stock'=>54,'new'=>0,'featured'=>0,'short_description'=>'Logitech G535 LIGHTSPEED wireless gaming headset — ultralight 236g with flip-to-mute mic and 33-hour battery.','description'=>'<p>G535 is one of the lightest wireless gaming headsets at 236g, making it comfortable for long gaming sessions. LIGHTSPEED 2.4 GHz delivers sub-1ms wireless latency — imperceptible in gaming scenarios. The flip-to-mute microphone gives clear physical feedback that you\'ve muted.</p><ul><li><strong>Driver:</strong> 40mm</li><li><strong>Wireless:</strong> Logitech LIGHTSPEED 2.4 GHz</li><li><strong>Battery:</strong> 33 hours</li><li><strong>Microphone:</strong> Flip-to-mute cardioid</li><li><strong>Weight:</strong> 236g</li><li><strong>Platform:</strong> PC, PlayStation</li></ul>'],
            ['sku'=>'TH-GH-004','name'=>'Corsair Virtuoso RGB Wireless XT','brand'=>'Corsair','category'=>'gaming-headsets','price'=>199.00,'special_price'=>169.00,'weight'=>0.36,'stock'=>31,'new'=>0,'featured'=>0,'short_description'=>'Corsair Virtuoso RGB XT — premium 50mm drivers, Slipstream 2.4 GHz, Bluetooth and USB-C for console and PC.','description'=>'<p>Virtuoso RGB Wireless XT spans PC and console with Slipstream 2.4 GHz for PC and Bluetooth for PlayStation 5, iOS and Android — both simultaneously active. The 50mm high-density neodymium drivers and aluminium construction make it one of the most premium-feeling gaming headsets.</p><ul><li><strong>Driver:</strong> 50mm Neodymium high-density</li><li><strong>Wireless:</strong> Slipstream 2.4 GHz + Bluetooth 5.0</li><li><strong>Battery:</strong> 20 hours (2.4 GHz) / 15 hours (BT)</li><li><strong>Microphone:</strong> Detachable broadcast-grade omnidirectional</li><li><strong>Platform:</strong> PC, PS5, PS4, mobile</li></ul>'],
            ['sku'=>'TH-GH-005','name'=>'SteelSeries Arctis Nova 1 Wired Gaming Headset','brand'=>'SteelSeries','category'=>'gaming-headsets','price'=>49.00,'special_price'=>null,'weight'=>0.25,'stock'=>78,'new'=>0,'featured'=>0,'short_description'=>'SteelSeries Arctis Nova 1 — multi-platform wired headset with noise-cancelling mic and 40mm drivers.','description'=>'<p>Arctis Nova 1 is the entry point to SteelSeries\' premium headset range. Universal USB-C + 3.5mm connectivity works with PC, PS5, Xbox, Nintendo Switch, and mobile without adapters. The ClearCast noise-cancelling bidirectional microphone provides clear voice pickup without background noise.</p><ul><li><strong>Driver:</strong> 40mm Neodymium</li><li><strong>Connection:</strong> USB-C + 3.5mm</li><li><strong>Microphone:</strong> ClearCast noise-cancelling bidirectional</li><li><strong>Weight:</strong> 250g</li><li><strong>Platform:</strong> Universal (PC, PS5, Xbox, Switch, mobile)</li></ul>'],
        ];
    }

    private static function speakers(): array
    {
        return [
            ['sku'=>'TH-SP-001','name'=>'Logitech Z623 2.1 Desktop Speaker System','brand'=>'Logitech','category'=>'speakers','price'=>149.00,'special_price'=>null,'weight'=>4.95,'stock'=>44,'new'=>0,'featured'=>1,'short_description'=>'Logitech Z623 2.1 speakers — 200W RMS THX-certified desktop system with powerful downward-firing subwoofer.','description'=>'<p>Z623 is THX Certified, meeting stringent acoustic standards for clarity and power. The 200W RMS system (including a downward-firing 8-inch subwoofer) produces genuine bass that you can feel during movies and music. Multiple inputs including 3.5mm and RCA make it compatible with any device.</p><ul><li><strong>Total Power:</strong> 200W RMS</li><li><strong>Subwoofer:</strong> 8-inch downward-firing, 130W</li><li><strong>Satellites:</strong> 2× 35W</li><li><strong>Certification:</strong> THX Certified</li><li><strong>Inputs:</strong> 2× 3.5mm, 1× RCA</li><li><strong>Controls:</strong> Front-panel volume, bass, power</li></ul>'],
            ['sku'=>'TH-SP-002','name'=>'Razer Nommo V2 Pro 2.1 PC Speaker System','brand'=>'Razer','category'=>'speakers','price'=>399.00,'special_price'=>null,'weight'=>5.80,'stock'=>16,'new'=>1,'featured'=>0,'short_description'=>'Razer Nommo V2 Pro — 2.1 THX Spatial Audio desktop speakers with Razer Chroma RGB and wireless subwoofer.','description'=>'<p>Nommo V2 Pro delivers the THX Spatial Audio experience from a 2.1 desktop system. The wireless subwoofer connects without cables cluttering your desk, while full-range 3-inch woven glass fibre drivers in the satellites produce clear mids and highs. Razer Chroma RGB syncs with your gaming setup.</p><ul><li><strong>System:</strong> 2.1 with THX Spatial Audio</li><li><strong>Satellites:</strong> 3-inch woven glass fibre drivers</li><li><strong>Subwoofer:</strong> 5.5-inch, wireless connection</li><li><strong>Chroma RGB:</strong> Yes (16.8M colours)</li><li><strong>Connections:</strong> USB-C, 3.5mm, optical</li></ul>'],
            ['sku'=>'TH-SP-003','name'=>'Logitech G560 LIGHTSYNC RGB PC Speakers','brand'=>'Logitech','category'=>'speakers','price'=>199.00,'special_price'=>149.00,'weight'=>3.20,'stock'=>29,'new'=>0,'featured'=>0,'short_description'=>'Logitech G560 2.1 gaming speakers with LIGHTSYNC RGB backlighting that reacts to on-screen content.','description'=>'<p>G560 LIGHTSYNC transforms the speaker backlight colour based on what\'s happening in your game or on screen — explosions pulse red, ocean scenes glow blue. Combined with 240W peak power output, it creates an immersive gaming atmosphere that goes beyond sound alone.</p><ul><li><strong>Peak Power:</strong> 240W</li><li><strong>RMS Power:</strong> 120W</li><li><strong>RGB:</strong> LIGHTSYNC (4 zones, 16.8M colours, game-reactive)</li><li><strong>Connections:</strong> USB, 3.5mm, Bluetooth</li></ul>'],
            ['sku'=>'TH-SP-004','name'=>'Razer Leviathan V2 X USB-C Desktop Speakers','brand'=>'Razer','category'=>'speakers','price'=>99.00,'special_price'=>null,'weight'=>2.10,'stock'=>47,'new'=>0,'featured'=>0,'short_description'=>'Razer Leviathan V2 X — compact USB-C soundbar with built-in subwoofer and Chroma RGB.','description'=>'<p>Leviathan V2 X is the most compact way to upgrade laptop or monitor audio with a real soundbar and subwoofer combination. The single USB-C cable powers the unit and delivers digital audio — no separate power adapter needed. Four Chroma RGB zones sync with the rest of your Razer ecosystem.</p><ul><li><strong>System:</strong> Soundbar with built-in subwoofer</li><li><strong>Connection:</strong> USB-C (power + audio)</li><li><strong>Driver:</strong> 2× 1.5-inch full-range + 3-inch subwoofer</li><li><strong>Chroma RGB:</strong> 4 zones</li><li><strong>Dimensions:</strong> 550 × 87 × 88mm</li></ul>'],
        ];
    }
}
