<?php

namespace Database\Seeders\ProductData;

class CameraData
{
    public static function get(): array
    {
        return array_merge(
            self::mirrorlessCameras(),
            self::actionCameras(),
            self::webcams(),
        );
    }

    private static function mirrorlessCameras(): array
    {
        return [
            ['sku'=>'TH-MC-001','name'=>'Sony Alpha 7 IV (Body Only)','brand'=>'Sony','category'=>'mirrorless-cameras','price'=>2499.00,'special_price'=>null,'weight'=>0.66,'stock'=>14,'new'=>0,'featured'=>1,'short_description'=>'Sony A7 IV — 33MP full-frame BSI sensor, 4K 60fps video, AI-powered subject detection and real-time tracking.','description'=>'<p>A7 IV is Sony\'s hybrid full-frame mirrorless camera that equally excels at photography and video. The 33MP Exmor R BSI sensor delivers excellent dynamic range and high-ISO performance, while real-time Eye AF and subject recognition track humans, animals, birds, and insects with near-perfect reliability.</p><ul><li><strong>Sensor:</strong> 33MP full-frame BSI CMOS (Exmor R)</li><li><strong>ISO Range:</strong> 100–51200 (expandable)</li><li><strong>Video:</strong> 4K 60fps (Super 35mm), 4K 30fps (full-frame)</li><li><strong>AF System:</strong> 759-point PDAF, real-time Eye AF, subject recognition</li><li><strong>Stabilisation:</strong> 5-axis in-body (5.5 stops)</li><li><strong>Mount:</strong> Sony E-mount</li><li><strong>Battery:</strong> NP-FZ100, ~580 shots CIPA</li></ul>'],
            ['sku'=>'TH-MC-002','name'=>'Sony Alpha 6700 APS-C Mirrorless (Body)','brand'=>'Sony','category'=>'mirrorless-cameras','price'=>1399.00,'special_price'=>1299.00,'weight'=>0.49,'stock'=>22,'new'=>1,'featured'=>0,'short_description'=>'Sony A6700 — 26MP APS-C with AI subject detection, 4K 120fps and 5-axis IBIS in a compact body.','description'=>'<p>A6700 brings full-frame A7 IV AI subject recognition capabilities to an APS-C sensor — perfect for wildlife, sport, and street photographers who want a compact system without sacrificing autofocus performance. 4K 120fps slow-motion in Super 35mm is unprecedented at this price point.</p><ul><li><strong>Sensor:</strong> 26MP APS-C (Exmor R)</li><li><strong>Video:</strong> 4K 120fps (Super 35mm), 6K oversampled</li><li><strong>AF System:</strong> AI subject recognition (human, animal, insect, vehicle)</li><li><strong>Stabilisation:</strong> 5-axis IBIS (7 stops with OSS lenses)</li><li><strong>Mount:</strong> Sony E-mount</li><li><strong>Battery:</strong> NP-FZ100</li></ul>'],
            ['sku'=>'TH-MC-003','name'=>'Canon EOS R6 Mark II (Body Only)','brand'=>'Canon','category'=>'mirrorless-cameras','price'=>2499.00,'special_price'=>null,'weight'=>0.67,'stock'=>11,'new'=>0,'featured'=>0,'short_description'=>'Canon EOS R6 Mark II — 40fps burst, 4K 60fps video, Dual Pixel CMOS AF II and improved EVF.','description'=>'<p>EOS R6 Mark II targets sports and action photographers needing extraordinary speed. 40fps RAW burst rate with mechanical shutter and Dual Pixel CMOS AF II ensures sharp tracking shots of fast-moving subjects. The 40MP equivalent pre-burst captures images 0.5 seconds before you press the shutter — for decisive-moment photography.</p><ul><li><strong>Sensor:</strong> 24.2MP full-frame CMOS</li><li><strong>Burst Rate:</strong> 40fps (electronic) / 12fps (mechanical)</li><li><strong>Video:</strong> 4K 60fps (full-frame), 4K 180fps (crop)</li><li><strong>AF:</strong> Dual Pixel CMOS AF II, deep learning subject tracking</li><li><strong>Stabilisation:</strong> 8 stops (IBIS + lens IS combined)</li><li><strong>Mount:</strong> Canon RF</li></ul>'],
            ['sku'=>'TH-MC-004','name'=>'Nikon Z fc Retro APS-C Mirrorless (Body)','brand'=>'Nikon','category'=>'mirrorless-cameras','price'=>849.00,'special_price'=>null,'weight'=>0.39,'stock'=>29,'new'=>0,'featured'=>0,'short_description'=>'Nikon Z fc — retro rangefinder styling, 20.9MP APS-C sensor and manual-style dials for hands-on photographers.','description'=>'<p>Z fc combines the ergonomics of a classic film camera with modern digital performance. Physical dials for shutter speed, exposure compensation, and ISO provide a tactile shooting experience that menu-driven cameras cannot replicate. Retro-inspired design is available in Sand, Coral Red, Cyan, and Special Edition colourways.</p><ul><li><strong>Sensor:</strong> 20.9MP DX CMOS</li><li><strong>AF:</strong> Hybrid AF, eye detection, animal detection</li><li><strong>Video:</strong> 4K UHD 30fps, Full HD 120fps</li><li><strong>Mount:</strong> Nikon Z (DX)</li><li><strong>Design:</strong> Retro rangefinder with manual dials</li><li><strong>Battery:</strong> EN-EL25, ~360 shots</li></ul>'],
            ['sku'=>'TH-MC-005','name'=>'Canon EOS R50 Content Creator Kit','brand'=>'Canon','category'=>'mirrorless-cameras','price'=>999.00,'special_price'=>null,'weight'=>0.38,'stock'=>34,'new'=>1,'featured'=>0,'short_description'=>'Canon EOS R50 Content Creator Kit — 24.2MP APS-C, 4K video and accessories for vlogging and YouTube.','description'=>'<p>EOS R50 Content Creator Kit bundles the EOS R50 with a microphone, filter, and extra accessories optimised for vlogging and social media creation. The compact body with flip-out touchscreen is ideal for self-shooting, and Canon\'s subject recognition AF tracks faces and eyes flawlessly during movement. Dual SD card memory gives you instant backup while shooting.</p><ul><li><strong>Sensor:</strong> 24.2MP APS-C CMOS</li><li><strong>Video:</strong> 4K UHD, oversampled from 6K</li><li><strong>AF:</strong> Dual Pixel CMOS AF, face + eye detection</li><li><strong>Screen:</strong> 3" vari-angle touchscreen</li><li><strong>Kit Includes:</strong> EOS R50 + RF-S 18-45mm + DM-E100 mic + accessories</li><li><strong>Mount:</strong> Canon RF</li></ul>'],
            ['sku'=>'TH-MC-006','name'=>'Sony ZV-E1 Full-Frame Vlogging Camera','brand'=>'Sony','category'=>'mirrorless-cameras','price'=>2199.00,'special_price'=>1999.00,'weight'=>0.48,'stock'=>17,'new'=>1,'featured'=>0,'short_description'=>'Sony ZV-E1 — full-frame 12MP sensor, Cinema Line 4K 120fps in a compact vlogging-optimised body.','description'=>'<p>ZV-E1 is the world\'s first Cinema Line vlogging camera with a full-frame sensor. The 12MP pixel count enables massive photosites for exceptional low-light performance — filming in dark bars, venues, and evening exteriors without noise. Cinematic Look modes are pre-calibrated to S-Cinetone and S-Log3 for colour grading.</p><ul><li><strong>Sensor:</strong> 12.1MP full-frame BSI CMOS</li><li><strong>Video:</strong> 4K 120fps, S-Log3, HLG, S-Cinetone</li><li><strong>AF:</strong> AI subject recognition (human + animal)</li><li><strong>Screen:</strong> 3" vari-angle touchscreen</li><li><strong>Microphone:</strong> 3-capsule directional mic built-in</li><li><strong>Mount:</strong> Sony E-mount</li></ul>'],
            ['sku'=>'TH-MC-007','name'=>'Nikon Z8 45.7MP Full-Frame Mirrorless (Body)','brand'=>'Nikon','category'=>'mirrorless-cameras','price'=>3999.00,'special_price'=>null,'weight'=>0.91,'stock'=>7,'new'=>1,'featured'=>0,'short_description'=>'Nikon Z8 — 45.7MP stacked BSI sensor, 8K RAW video and 120fps blackout-free burst for professionals.','description'=>'<p>Z8 delivers near-Z9 capabilities without the vertical grip — a smaller, lighter professional camera with the same 45.7MP stacked CMOS sensor, 8K internal RAW video, and 120fps blackout-free shooting. The pre-release capture function stores images continuously, retroactively saving the decisive moment even after the fact.</p><ul><li><strong>Sensor:</strong> 45.7MP full-frame stacked BSI CMOS</li><li><strong>Burst Rate:</strong> 120fps (RAW), 20fps (mechanical)</li><li><strong>Video:</strong> 8.3K N-RAW, 4K 120fps ProRes RAW HQ</li><li><strong>AF:</strong> 493-point, subject detection (human + animal + vehicle)</li><li><strong>Mount:</strong> Nikon Z</li></ul>'],
        ];
    }

    private static function actionCameras(): array
    {
        return [
            ['sku'=>'TH-AC-001','name'=>'GoPro HERO12 Black','brand'=>'GoPro','category'=>'action-cameras','price'=>399.00,'special_price'=>349.00,'weight'=>0.15,'stock'=>48,'new'=>1,'featured'=>1,'short_description'=>'GoPro HERO12 Black — 5.3K 60fps, HyperSmooth 6.0 stabilisation, HDR video and GP2 chip.','description'=>'<p>HERO12 Black is GoPro\'s most capable action camera to date. HyperSmooth 6.0 delivers gimbal-smooth footage without a physical gimbal, and Max Lens Mod 2.0 adds in-camera horizon lock for footage that stays level even when the camera rolls 360°. 5.3K 60fps captures ultra-detailed slow-motion footage.</p><ul><li><strong>Video:</strong> 5.3K 60fps, 4K 120fps, 2.7K 240fps</li><li><strong>Stabilisation:</strong> HyperSmooth 6.0, Max Horizon Lock</li><li><strong>HDR:</strong> HDR video (5.3K, 4K)</li><li><strong>Waterproof:</strong> 10 metres (no housing)</li><li><strong>Battery:</strong> Enduro battery (30% longer than previous)</li><li><strong>Connectivity:</strong> Bluetooth 5.0, Wi-Fi 5GHz</li></ul>'],
            ['sku'=>'TH-AC-002','name'=>'DJI Osmo Action 4','brand'=>'DJI','category'=>'action-cameras','price'=>299.00,'special_price'=>null,'weight'=>0.14,'stock'=>37,'new'=>1,'featured'=>0,'short_description'=>'DJI Osmo Action 4 — 1/1.3" sensor, 4K 120fps, 18m waterproof and DJI\'s RockSteady 3.0 stabilisation.','description'=>'<p>Osmo Action 4 has a significant sensor advantage over GoPro\'s standard cameras — the 1/1.3" sensor collects more light for better low-light performance in caves, forests, and dusk activities. 18-metre waterproofing without a housing case is deeper than GoPro\'s 10m. DJI Mimo app provides intuitive post-production tools.</p><ul><li><strong>Sensor:</strong> 1/1.3" CMOS (large format for action cams)</li><li><strong>Video:</strong> 4K 120fps, 1080p 240fps</li><li><strong>Stabilisation:</strong> RockSteady 3.0 + HorizonSteady</li><li><strong>Waterproof:</strong> 18 metres (no housing)</li><li><strong>Battery:</strong> Extreme Edition battery, 160 min at 4K 30fps</li></ul>'],
            ['sku'=>'TH-AC-003','name'=>'GoPro HERO12 Black + Volta Battery Grip Bundle','brand'=>'GoPro','category'=>'action-cameras','price'=>549.00,'special_price'=>null,'weight'=>0.42,'stock'=>19,'new'=>1,'featured'=>0,'short_description'=>'GoPro HERO12 Black + Volta battery grip — 4× longer battery life, tripod mount, wireless shutter control.','description'=>'<p>The Volta battery grip quadruples HERO12\'s runtime to over 4 hours for all-day shoots without recharging. It integrates a tripod mount, wireless shutter button, and GoPro Quik capture shortcut. Ideal for event coverage, time-lapse shoots, and extended hikes where power access is unavailable.</p><ul><li><strong>Camera:</strong> GoPro HERO12 Black (5.3K 60fps)</li><li><strong>Battery:</strong> Volta grip (4× runtime = 4+ hours)</li><li><strong>Grip Features:</strong> Tripod mount, wireless shutter, Quik shortcut</li><li><strong>Total Weight:</strong> 280g (camera + grip)</li></ul>'],
            ['sku'=>'TH-AC-004','name'=>'DJI Action 4 Adventure Combo','brand'=>'DJI','category'=>'action-cameras','price'=>449.00,'special_price'=>null,'weight'=>0.35,'stock'=>23,'new'=>1,'featured'=>0,'short_description'=>'DJI Osmo Action 4 Adventure Combo — camera plus two batteries, charging hub and vertical shooting frame.','description'=>'<p>Adventure Combo bundles everything you need for a full day of shooting. Two extreme batteries in the charging hub charge simultaneously overnight. The vertical shooting frame captures 9:16 vertical video natively for Instagram Reels and TikTok without cropping — a significant advantage for social media creators.</p><ul><li><strong>Camera:</strong> DJI Osmo Action 4 (4K 120fps)</li><li><strong>Batteries:</strong> 2× extreme edition batteries</li><li><strong>Accessories:</strong> Charging hub + vertical shooting frame + protective frame</li><li><strong>Runtime:</strong> Full day with 2 batteries</li></ul>'],
        ];
    }

    private static function webcams(): array
    {
        return [
            ['sku'=>'TH-WC-001','name'=>'Logitech MX Brio 4K Ultra HD Webcam','brand'=>'Logitech','category'=>'webcams','price'=>199.00,'special_price'=>null,'weight'=>0.15,'stock'=>41,'new'=>1,'featured'=>1,'short_description'=>'Logitech MX Brio 4K — 4K 30fps, 95° FoV, AI noise reduction and USB-C with 90W PD passthrough.','description'=>'<p>MX Brio is Logitech\'s most advanced webcam, designed for professionals on video calls all day. The 8MP sensor captures true 4K at 30fps, while RightLight 5 with TrueVision HDR automatically adjusts for back-lit environments (sitting in front of a window). USB-C passthrough delivers 90W to charge your MacBook simultaneously.</p><ul><li><strong>Resolution:</strong> 4K 30fps / 1080p 60fps</li><li><strong>Sensor:</strong> 8MP</li><li><strong>Field of View:</strong> 65°, 78°, 90° (adjustable)</li><li><strong>HDR:</strong> RightLight 5 with TrueVision HDR</li><li><strong>USB-C PD:</strong> 90W passthrough</li><li><strong>Privacy:</strong> Physical shutter</li><li><strong>Certifications:</strong> Teams, Zoom, Google Meet</li></ul>'],
            ['sku'=>'TH-WC-002','name'=>'Elgato Facecam Pro 4K Streaming Webcam','brand'=>'Elgato','category'=>'webcams','price'=>299.00,'special_price'=>null,'weight'=>0.20,'stock'=>27,'new'=>1,'featured'=>0,'short_description'=>'Elgato Facecam Pro 4K — Sony STARVIS 2 sensor, 60fps 4K, manual focus ring and no AI processing.','description'=>'<p>Facecam Pro is designed for streamers and content creators who want full manual control over their image without AI auto-corrections. Sony STARVIS 2 sensor with large pixels performs exceptionally in low-light streaming environments. Manual focus ring allows precise depth adjustment for creative compositions. Captured footage is uncompressed for highest quality.</p><ul><li><strong>Resolution:</strong> 4K 60fps (Ultra HD)</li><li><strong>Sensor:</strong> Sony STARVIS 2 (low-light specialist)</li><li><strong>Focus:</strong> Manual focus ring</li><li><strong>AI Processing:</strong> None (manual control preferred by creators)</li><li><strong>Connection:</strong> USB-C</li><li><strong>Software:</strong> Camera Hub (Elgato)</li></ul>'],
            ['sku'=>'TH-WC-003','name'=>'Logitech C922 Pro Stream 1080p Webcam','brand'=>'Logitech','category'=>'webcams','price'=>99.00,'special_price'=>79.00,'weight'=>0.13,'stock'=>73,'new'=>0,'featured'=>0,'short_description'=>'Logitech C922 Pro 1080p — 60fps at 720p, background replacement and RightLight 2 for low-light streaming.','description'=>'<p>C922 Pro is the classic streaming webcam that launched countless careers. 60fps at 720p keeps motion smooth during fast-paced streams, while RightLight 2 automatically optimises exposure in dim environments. Background replacement works without a green screen via Logitech Capture software.</p><ul><li><strong>Resolution:</strong> 1080p 30fps / 720p 60fps</li><li><strong>AF:</strong> Autofocus</li><li><strong>Low Light:</strong> RightLight 2</li><li><strong>Background:</strong> XSplit software licence included (3 months)</li><li><strong>Certifications:</strong> Teams, Zoom, OBS compatible</li></ul>'],
            ['sku'=>'TH-WC-004','name'=>'Razer Kiyo Pro Ultra 4K Streaming Webcam','brand'=>'Razer','category'=>'webcams','price'=>249.00,'special_price'=>199.00,'weight'=>0.19,'stock'=>22,'new'=>1,'featured'=>0,'short_description'=>'Razer Kiyo Pro Ultra 4K — Sony STARVIS 2 sensor, HDR and 4K 30fps with AI-powered background effects.','description'=>'<p>Kiyo Pro Ultra uses a Sony STARVIS 2 large-format sensor to capture 4K video in environments where other webcams fail — gaming rooms with backlighting, dimly-lit home offices, and RGB-heavy setups. AI background blur and replacement work on the local Synapse GPU without cloud processing for real-time performance.</p><ul><li><strong>Resolution:</strong> 4K 30fps / 1080p 60fps</li><li><strong>Sensor:</strong> 1/1.2" Sony STARVIS 2 (largest in its class)</li><li><strong>HDR:</strong> Yes</li><li><strong>AI Effects:</strong> Background blur, replacement (local GPU)</li><li><strong>Privacy:</strong> Physical cap included</li></ul>'],
            ['sku'=>'TH-WC-005','name'=>'Logitech Brio 500 1080p Webcam','brand'=>'Logitech','category'=>'webcams','price'=>129.00,'special_price'=>null,'weight'=>0.09,'stock'=>56,'new'=>0,'featured'=>0,'short_description'=>'Logitech Brio 500 — RightLight 4 auto-framing, 1080p, privacy shutter and Show Mode for product demos.','description'=>'<p>Brio 500 is Logitech\'s AI-framing 1080p webcam. Show Mode tilts the camera downward to display hands and desk objects — useful for product demonstrations, unboxings, and online teaching. The built-in privacy shutter covers the lens when not in use, visible as a red indicator to ensure you\'re never accidentally broadcasting.</p><ul><li><strong>Resolution:</strong> 1080p 30fps</li><li><strong>RightLight:</strong> 4 (AI-powered auto exposure)</li><li><strong>Show Mode:</strong> Yes (angled down for desk/hand demos)</li><li><strong>Privacy:</strong> Physical shutter (red indicator)</li><li><strong>Certifications:</strong> Teams, Zoom, Google Meet</li></ul>'],
        ];
    }
}
