<?php

namespace Database\Seeders\ProductData;

class ComponentData
{
    public static function get(): array
    {
        return array_merge(
            self::graphicsCards(),
            self::processors(),
            self::cooling(),
        );
    }

    private static function graphicsCards(): array
    {
        return [
            ['sku'=>'TH-GPU-001','name'=>'NVIDIA GeForce RTX 4090 24GB Founders Edition','brand'=>'NVIDIA','category'=>'graphics-cards','price'=>1599.00,'special_price'=>null,'weight'=>2.20,'stock'=>8,'new'=>0,'featured'=>1,'short_description'=>'NVIDIA RTX 4090 24GB — the fastest consumer GPU ever with 16,384 CUDA cores and 82.6 TFLOPS.','description'=>'<p>RTX 4090 Founders Edition is the definitive high-performance GPU for 4K gaming, generative AI, and 3D rendering. 24GB of GDDR6X memory and 82.6 TFLOPS of shader performance put it in a class of its own. DLSS 3 Frame Generation delivers frame rates impossible on previous-generation hardware.</p><ul><li><strong>CUDA Cores:</strong> 16,384</li><li><strong>VRAM:</strong> 24GB GDDR6X</li><li><strong>Memory Bandwidth:</strong> 1,008 GB/s</li><li><strong>TDP:</strong> 450W</li><li><strong>Performance:</strong> 82.6 TFLOPS (FP32)</li><li><strong>Connector:</strong> 1× 16-pin (12VHPWR)</li><li><strong>Display Outputs:</strong> 3× DisplayPort 1.4a, 1× HDMI 2.1</li><li><strong>DLSS:</strong> DLSS 3 (Frame Generation)</li></ul>'],
            ['sku'=>'TH-GPU-002','name'=>'NVIDIA GeForce RTX 4080 Super 16GB','brand'=>'NVIDIA','category'=>'graphics-cards','price'=>999.00,'special_price'=>null,'weight'=>1.91,'stock'=>17,'new'=>1,'featured'=>1,'short_description'=>'NVIDIA RTX 4080 Super 16GB — 10,240 CUDA cores and 52 TFLOPS for 4K gaming without compromise.','description'=>'<p>RTX 4080 Super fills the gap between RTX 4080 and RTX 4090 with 10,240 CUDA cores and 52 TFLOPS — a 21% shader performance uplift over the RTX 4080. It handles every current game at 4K ultra settings with DLSS 3 providing headroom for frame rates well above 60fps on demanding titles.</p><ul><li><strong>CUDA Cores:</strong> 10,240</li><li><strong>VRAM:</strong> 16GB GDDR6X</li><li><strong>Memory Bandwidth:</strong> 736 GB/s</li><li><strong>TDP:</strong> 320W</li><li><strong>Performance:</strong> 52.2 TFLOPS (FP32)</li><li><strong>Display Outputs:</strong> 3× DisplayPort 1.4a, 1× HDMI 2.1</li><li><strong>DLSS:</strong> DLSS 3</li></ul>'],
            ['sku'=>'TH-GPU-003','name'=>'NVIDIA GeForce RTX 4070 Ti Super 16GB','brand'=>'NVIDIA','category'=>'graphics-cards','price'=>799.00,'special_price'=>749.00,'weight'=>1.71,'stock'=>23,'new'=>1,'featured'=>0,'short_description'=>'RTX 4070 Ti Super with 16GB GDDR6X — the sweet spot for 1440p and capable 4K gaming.','description'=>'<p>RTX 4070 Ti Super adds 3GB more VRAM over the RTX 4070 Ti (totalling 16GB) and 20% more CUDA cores, making it the recommended card for creators running Stable Diffusion or DaVinci Resolve alongside gaming. It delivers playable 4K in most titles and excellent 1440p performance at all quality levels.</p><ul><li><strong>CUDA Cores:</strong> 8,448</li><li><strong>VRAM:</strong> 16GB GDDR6X</li><li><strong>Memory Bandwidth:</strong> 672 GB/s</li><li><strong>TDP:</strong> 285W</li><li><strong>Performance:</strong> 40 TFLOPS (FP32)</li><li><strong>DLSS:</strong> DLSS 3</li></ul>'],
            ['sku'=>'TH-GPU-004','name'=>'NVIDIA GeForce RTX 4070 Super 12GB','brand'=>'NVIDIA','category'=>'graphics-cards','price'=>599.00,'special_price'=>null,'weight'=>1.60,'stock'=>32,'new'=>1,'featured'=>0,'short_description'=>'RTX 4070 Super — 7168 CUDA cores and 30 TFLOPS for 1440p excellence at mainstream pricing.','description'=>'<p>RTX 4070 Super is the new benchmark for 1440p gaming, outperforming the previous-generation RTX 3090 at a fraction of the price. 7168 CUDA cores and DLSS 3 make it more than capable for modern titles at 2560×1440, and the 12GB GDDR6X VRAM handles texture-heavy modded games and creative applications.</p><ul><li><strong>CUDA Cores:</strong> 7,168</li><li><strong>VRAM:</strong> 12GB GDDR6X</li><li><strong>TDP:</strong> 220W</li><li><strong>Performance:</strong> 30.1 TFLOPS (FP32)</li><li><strong>DLSS:</strong> DLSS 3</li><li><strong>Connector:</strong> 1× 16-pin (12VHPWR)</li></ul>'],
            ['sku'=>'TH-GPU-005','name'=>'AMD Radeon RX 7900 XTX 24GB','brand'=>'AMD','category'=>'graphics-cards','price'=>999.00,'special_price'=>849.00,'weight'=>2.05,'stock'=>14,'new'=>0,'featured'=>0,'short_description'=>'AMD RX 7900 XTX 24GB GDDR6 — AMD\'s fastest consumer GPU with 96 RDNA 3 compute units and FSR 3.','description'=>'<p>RX 7900 XTX is AMD\'s answer to RTX 4080 Super, offering competing 4K performance with a generous 24GB GDDR6 frame buffer — more than any NVIDIA consumer card below the RTX 4090. FSR 3 Frame Generation provides AI-accelerated upscaling across a broader range of supported games.</p><ul><li><strong>Compute Units:</strong> 96 (RDNA 3)</li><li><strong>VRAM:</strong> 24GB GDDR6</li><li><strong>Memory Bandwidth:</strong> 960 GB/s</li><li><strong>TDP:</strong> 355W</li><li><strong>Performance:</strong> 61.4 TFLOPS (FP32)</li><li><strong>Display Outputs:</strong> 2× DisplayPort 2.1, 1× HDMI 2.1, 1× USB-C</li><li><strong>FSR:</strong> FSR 3 (Frame Generation)</li></ul>'],
            ['sku'=>'TH-GPU-006','name'=>'AMD Radeon RX 7700 XT 12GB','brand'=>'AMD','category'=>'graphics-cards','price'=>449.00,'special_price'=>399.00,'weight'=>1.28,'stock'=>28,'new'=>0,'featured'=>0,'short_description'=>'AMD RX 7700 XT 12GB — 54 RDNA 3 compute units for excellent 1440p gaming and 4K content viewing.','description'=>'<p>RX 7700 XT targets the 1440p gaming mainstream. 54 RDNA 3 compute units deliver solid performance in current-generation titles at 2560×1440, while DisplayPort 2.1 support future-proofs for 4K 240Hz displays. AMD\'s Radeon Super Resolution (RSR) works at the driver level across all supported titles.</p><ul><li><strong>Compute Units:</strong> 54 (RDNA 3)</li><li><strong>VRAM:</strong> 12GB GDDR6</li><li><strong>TDP:</strong> 245W</li><li><strong>Display Outputs:</strong> 3× DisplayPort 2.1, 1× HDMI 2.1</li><li><strong>FSR:</strong> FSR 2 and RSR</li></ul>'],
            ['sku'=>'TH-GPU-007','name'=>'NVIDIA GeForce RTX 4060 8GB','brand'=>'NVIDIA','category'=>'graphics-cards','price'=>299.00,'special_price'=>null,'weight'=>0.88,'stock'=>54,'new'=>0,'featured'=>0,'short_description'=>'RTX 4060 8GB — DLSS 3 Frame Generation, AV1 encoder and 1080p performance in a 115W package.','description'=>'<p>RTX 4060 is designed for 1080p gaming with DLSS 3 delivering frame rates no previous-generation card in this price bracket could achieve. The 115W TDP allows use in compact Mini-ITX builds or machines with modest power supplies. AV1 hardware encoding is a streaming upgrade over the RTX 3060.</p><ul><li><strong>CUDA Cores:</strong> 3,072</li><li><strong>VRAM:</strong> 8GB GDDR6</li><li><strong>TDP:</strong> 115W</li><li><strong>DLSS:</strong> DLSS 3 (Frame Generation)</li><li><strong>Encoder:</strong> AV1 hardware encode</li><li><strong>Power Connector:</strong> Standard 8-pin</li></ul>'],
            ['sku'=>'TH-GPU-008','name'=>'NVIDIA GeForce RTX 4060 Ti 16GB','brand'=>'NVIDIA','category'=>'graphics-cards','price'=>499.00,'special_price'=>449.00,'weight'=>1.15,'stock'=>37,'new'=>0,'featured'=>0,'short_description'=>'RTX 4060 Ti 16GB — double the VRAM over the 8GB model for content creation and future-proofing.','description'=>'<p>RTX 4060 Ti 16GB doubles the frame buffer of the 8GB version for workflows where VRAM is the limiting factor — large Stable Diffusion models, high-resolution video editing, and heavily modded games. The Lovelace architecture delivers efficient performance within a 160W power envelope.</p><ul><li><strong>CUDA Cores:</strong> 4,352</li><li><strong>VRAM:</strong> 16GB GDDR6</li><li><strong>TDP:</strong> 165W</li><li><strong>DLSS:</strong> DLSS 3</li><li><strong>Encoder:</strong> Dual AV1 hardware encode</li></ul>'],
        ];
    }

    private static function processors(): array
    {
        return [
            ['sku'=>'TH-CPU-001','name'=>'Intel Core i9-14900K (24-core, 6.0 GHz)','brand'=>'Intel','category'=>'processors','price'=>549.00,'special_price'=>499.00,'weight'=>0.05,'stock'=>21,'new'=>0,'featured'=>1,'short_description'=>'Intel Core i9-14900K — 24 cores (8P+16E), 6.0 GHz max boost, the fastest desktop gaming CPU from Intel.','description'=>'<p>Core i9-14900K is Intel\'s fastest consumer desktop CPU, with 8 Performance cores clocked up to 6.0 GHz and 16 Efficiency cores for multithreaded workloads. Requires a Z790 motherboard and DDR5 for best performance. Intel\'s top single-threaded performance makes it the fastest gaming CPU available.</p><ul><li><strong>Architecture:</strong> Raptor Lake Refresh</li><li><strong>Cores/Threads:</strong> 24 (8P + 16E) / 32</li><li><strong>P-Core Base/Boost:</strong> 3.2 GHz / 6.0 GHz</li><li><strong>E-Core Base/Boost:</strong> 2.4 GHz / 4.4 GHz</li><li><strong>TDP:</strong> 125W (253W PL2)</li><li><strong>Cache:</strong> 36MB L3</li><li><strong>Socket:</strong> LGA1700</li><li><strong>Memory:</strong> DDR4 / DDR5</li></ul>'],
            ['sku'=>'TH-CPU-002','name'=>'AMD Ryzen 9 7950X (16-core, 5.7 GHz)','brand'=>'AMD','category'=>'processors','price'=>699.00,'special_price'=>599.00,'weight'=>0.05,'stock'=>14,'new'=>0,'featured'=>0,'short_description'=>'AMD Ryzen 9 7950X — 16 cores of Zen 4, 5.7 GHz boost, for workstation and creative professionals.','description'=>'<p>Ryzen 9 7950X is AMD\'s most powerful consumer desktop CPU — 16 Zen 4 cores with 5nm process technology deliver exceptional multithreaded performance for 3D rendering, compilation, video encoding, and scientific computing. PCIe 5.0 and DDR5 support future-proof the platform for years.</p><ul><li><strong>Architecture:</strong> Zen 4</li><li><strong>Cores/Threads:</strong> 16 / 32</li><li><strong>Base/Boost Clock:</strong> 4.5 GHz / 5.7 GHz</li><li><strong>TDP:</strong> 170W</li><li><strong>Cache:</strong> 64MB L3</li><li><strong>Socket:</strong> AM5</li><li><strong>Memory:</strong> DDR5 only</li><li><strong>PCIe:</strong> PCIe 5.0</li></ul>'],
            ['sku'=>'TH-CPU-003','name'=>'Intel Core i7-14700K (20-core, 5.6 GHz)','brand'=>'Intel','category'=>'processors','price'=>419.00,'special_price'=>null,'weight'=>0.05,'stock'=>31,'new'=>0,'featured'=>0,'short_description'=>'Intel Core i7-14700K — 20 cores, 5.6 GHz boost at a compelling price below the i9.','description'=>'<p>Core i7-14700K adds 4 additional Efficiency cores versus the i7-13700K while boosting to 5.6 GHz — delivering workstation-class multithreaded performance at a price significantly below the i9-14900K. The best value enthusiast CPU on Intel\'s LGA1700 platform for users who want speed without the i9 premium.</p><ul><li><strong>Cores/Threads:</strong> 20 (8P + 12E) / 28</li><li><strong>P-Core Boost:</strong> 5.6 GHz</li><li><strong>TDP:</strong> 125W (253W PL2)</li><li><strong>Cache:</strong> 33MB L3</li><li><strong>Socket:</strong> LGA1700</li><li><strong>Memory:</strong> DDR4 / DDR5</li></ul>'],
            ['sku'=>'TH-CPU-004','name'=>'AMD Ryzen 7 7800X3D (8-core, 5.0 GHz + 3D V-Cache)','brand'=>'AMD','category'=>'processors','price'=>449.00,'special_price'=>null,'weight'=>0.05,'stock'=>26,'new'=>1,'featured'=>1,'short_description'=>'AMD Ryzen 7 7800X3D — 96MB 3D V-Cache gaming CPU, the fastest gaming processor in the world.','description'=>'<p>Ryzen 7 7800X3D is definitively the fastest gaming CPU available in 2024. The 96MB 3D V-Cache eliminates the gap between L3 cache and system RAM for game data, resulting in higher frame rates and more consistent 1% lows than any competing Intel processor. The best gaming-specific CPU investment since the original 5800X3D.</p><ul><li><strong>Architecture:</strong> Zen 4 + 3D V-Cache</li><li><strong>Cores/Threads:</strong> 8 / 16</li><li><strong>Base/Boost:</strong> 4.2 GHz / 5.0 GHz</li><li><strong>L3 Cache:</strong> 96MB (3D stacked)</li><li><strong>TDP:</strong> 120W</li><li><strong>Socket:</strong> AM5</li><li><strong>Memory:</strong> DDR5</li></ul>'],
            ['sku'=>'TH-CPU-005','name'=>'Intel Core i5-14600K (14-core, 5.3 GHz)','brand'=>'Intel','category'=>'processors','price'=>319.00,'special_price'=>289.00,'weight'=>0.05,'stock'=>48,'new'=>0,'featured'=>0,'short_description'=>'Intel Core i5-14600K — 14 cores, 5.3 GHz boost, best-value gaming CPU on the Intel platform.','description'=>'<p>Core i5-14600K is the go-to recommendation for gaming builds that want Intel\'s fast P-cores without paying for the i7 or i9 premium. The 5.3 GHz single-core boost is competitive with the i9 in gaming, where single-threaded performance matters most, at a significantly lower price and power budget.</p><ul><li><strong>Cores/Threads:</strong> 14 (6P + 8E) / 20</li><li><strong>P-Core Boost:</strong> 5.3 GHz</li><li><strong>TDP:</strong> 125W</li><li><strong>Cache:</strong> 24MB L3</li><li><strong>Socket:</strong> LGA1700</li></ul>'],
            ['sku'=>'TH-CPU-006','name'=>'AMD Ryzen 5 7600X (6-core, 5.3 GHz)','brand'=>'AMD','category'=>'processors','price'=>299.00,'special_price'=>249.00,'weight'=>0.05,'stock'=>43,'new'=>0,'featured'=>0,'short_description'=>'AMD Ryzen 5 7600X — 6-core Zen 4, 5.3 GHz boost and DDR5 for a mid-range AM5 gaming build.','description'=>'<p>Ryzen 5 7600X is the entry point to AMD\'s AM5 platform. Zen 4 delivers substantial IPC gains over Zen 3, and the AM5 socket is supported through 2027 — meaning future Ryzen upgrades don\'t require a new motherboard. PCIe 5.0 and DDR5 make this a genuinely future-proof budget gaming CPU.</p><ul><li><strong>Architecture:</strong> Zen 4</li><li><strong>Cores/Threads:</strong> 6 / 12</li><li><strong>Base/Boost:</strong> 4.7 GHz / 5.3 GHz</li><li><strong>TDP:</strong> 105W</li><li><strong>Cache:</strong> 32MB L3</li><li><strong>Socket:</strong> AM5</li></ul>'],
        ];
    }

    private static function cooling(): array
    {
        return [
            ['sku'=>'TH-CO-001','name'=>'Corsair H150i Elite LCD 360mm AIO Cooler','brand'=>'Corsair','category'=>'cooling','price'=>249.00,'special_price'=>null,'weight'=>1.45,'stock'=>19,'new'=>1,'featured'=>1,'short_description'=>'Corsair H150i Elite LCD 360mm AIO — 2.1" IPS LCD display, three 120mm fans and iCUE integration.','description'=>'<p>H150i Elite LCD is the most feature-rich all-in-one cooler in Corsair\'s lineup. The cold plate-mounted 2.1" IPS LCD displays CPU temperature, clock speed, or custom images. Three 120mm AF120 Elite fans provide the airflow needed to keep the i9-14900K or Ryzen 9 7950X within thermal limits under sustained load.</p><ul><li><strong>Radiator:</strong> 360mm (3× 120mm)</li><li><strong>Pump Head:</strong> 2.1" IPS LCD display</li><li><strong>Fans:</strong> 3× Corsair AF120 Elite (2100 RPM)</li><li><strong>TDP Rated:</strong> Up to 350W</li><li><strong>Socket Support:</strong> LGA1700, LGA1200, AM5, AM4</li><li><strong>Software:</strong> Corsair iCUE</li></ul>'],
            ['sku'=>'TH-CO-002','name'=>'Noctua NH-D15 Chromax Black Air Cooler','brand'=>'Corsair','category'=>'cooling','price'=>99.00,'special_price'=>null,'weight'=>1.32,'stock'=>33,'new'=>0,'featured'=>0,'short_description'=>'Noctua NH-D15 Chromax Black — dual-tower air cooler with 2× NF-A15 fans, quiet and extremely effective.','description'=>'<p>NH-D15 in Chromax Black is Noctua\'s best air cooler and competes with most 240mm AIOs in thermal performance. Two NF-A15 fans in a push-pull configuration maximise airflow through the dual-tower heatsink. At 1500 RPM the fans are nearly inaudible — ideal for quiet workstation and content creation builds.</p><ul><li><strong>Configuration:</strong> Dual-tower, dual-fan</li><li><strong>Fans:</strong> 2× NF-A15 PWM (1500 RPM max)</li><li><strong>TDP Rated:</strong> 250W+</li><li><strong>Height:</strong> 165mm</li><li><strong>Socket Support:</strong> LGA1700, LGA1200, AM5, AM4</li><li><strong>Colour:</strong> Chromax Black</li><li><strong>Warranty:</strong> 6 years</li></ul>'],
            ['sku'=>'TH-CO-003','name'=>'be quiet! Dark Rock Pro 5 Air Cooler','brand'=>'Corsair','category'=>'cooling','price'=>89.00,'special_price'=>null,'weight'=>1.27,'stock'=>24,'new'=>1,'featured'=>0,'short_description'=>'be quiet! Dark Rock Pro 5 — 250W TDP dual-tower cooler with Silent Wings PWM fans for premium quiet builds.','description'=>'<p>Dark Rock Pro 5 is be quiet!\'s new flagship air cooler. Three Silent Wings 4 PWM fans in a push-pull-push configuration deliver outstanding thermal performance while maintaining near-silent operation at 1550 RPM. The blacked-out premium finish suits builds with dark or minimalist aesthetics.</p><ul><li><strong>Configuration:</strong> Dual-tower, triple-fan</li><li><strong>Fans:</strong> 3× Silent Wings 4 PWM (1550 RPM)</li><li><strong>TDP Rated:</strong> 250W</li><li><strong>Height:</strong> 163mm</li><li><strong>Socket Support:</strong> LGA1700, AM5, AM4</li><li><strong>Colour:</strong> All black</li></ul>'],
            ['sku'=>'TH-CO-004','name'=>'NZXT Kraken 240 RGB AIO Liquid Cooler','brand'=>'Corsair','category'=>'cooling','price'=>129.00,'special_price'=>null,'weight'=>1.02,'stock'=>38,'new'=>0,'featured'=>0,'short_description'=>'NZXT Kraken 240 RGB — 240mm AIO with Infinity Mirror pump head display and two F120 RGB fans.','description'=>'<p>Kraken 240 RGB is the mid-range AIO for builders who want strong thermal performance plus a visual centrepiece. The Infinity Mirror pump head creates a hypnotic depth effect with ARGB lighting. Two Aer P 120mm fans in the push configuration cool the 240mm radiator effectively for CPUs up to 230W TDP.</p><ul><li><strong>Radiator:</strong> 240mm (2× 120mm)</li><li><strong>Pump Head:</strong> Infinity Mirror ARGB display</li><li><strong>Fans:</strong> 2× Aer P 120 ARGB (2000 RPM)</li><li><strong>TDP Rated:</strong> Up to 230W</li><li><strong>Socket Support:</strong> LGA1700, LGA1200, AM5, AM4</li><li><strong>Software:</strong> NZXT CAM</li></ul>'],
            ['sku'=>'TH-CO-005','name'=>'Corsair A115 Air Cooler','brand'=>'Corsair','category'=>'cooling','price'=>79.00,'special_price'=>null,'weight'=>1.10,'stock'=>28,'new'=>1,'featured'=>0,'short_description'=>'Corsair A115 single-tower air cooler — 220W TDP with 140mm AF140 fan, excellent value for mid-range builds.','description'=>'<p>A115 is Corsair\'s best-value high-performance air cooler. The single-tower design with a 140mm fan delivers 220W TDP cooling — enough for Core i7 and Ryzen 7 chips under normal operating conditions. A low-contact direct touch heat pipe array maximises heat transfer without the complexity of a dual-tower build.</p><ul><li><strong>Configuration:</strong> Single-tower</li><li><strong>Fan:</strong> 1× AF140 PWM (1500 RPM)</li><li><strong>TDP Rated:</strong> 220W</li><li><strong>Height:</strong> 158mm</li><li><strong>Socket Support:</strong> LGA1700, LGA1200, AM5, AM4</li></ul>'],
            ['sku'=>'TH-CO-006','name'=>'Corsair H60x 120mm AIO Cooler','brand'=>'Corsair','category'=>'cooling','price'=>59.00,'special_price'=>null,'weight'=>0.68,'stock'=>47,'new'=>0,'featured'=>0,'short_description'=>'Corsair H60x 120mm AIO — compact all-in-one cooler for small form-factor and budget builds.','description'=>'<p>H60x offers all-in-one cooler convenience at air-cooler pricing. The 120mm radiator fits cases that cannot accommodate larger radiators, and the included 120mm PWM fan provides enough cooling for 65–95W TDP processors like Core i5 and Ryzen 5 at stock settings.</p><ul><li><strong>Radiator:</strong> 120mm (1× 120mm)</li><li><strong>Fan:</strong> 1× 120mm PWM (1800 RPM)</li><li><strong>TDP Rated:</strong> Up to 150W</li><li><strong>Socket Support:</strong> LGA1700, LGA1200, AM5, AM4</li><li><strong>Installation:</strong> Tool-free AM4/AM5 bracket</li></ul>'],
        ];
    }
}
