<?php

namespace Database\Seeders\ProductData;

class KeyboardData
{
    public static function get(): array
    {
        return array_merge(
            self::mechanical(),
            self::wireless(),
            self::gaming(),
        );
    }

    private static function mechanical(): array
    {
        return [
            ['sku'=>'TH-MK-001','name'=>'Keychron Q3 Max QMK TKL Keyboard','brand'=>'Keychron','category'=>'mechanical-keyboards','price'=>199.00,'special_price'=>null,'weight'=>1.55,'stock'=>38,'new'=>1,'featured'=>1,'short_description'=>'Keychron Q3 Max TKL — aluminum CNC body, QMK/VIA support, hot-swap, Bluetooth 5.1 and 2.4 GHz wireless.','description'=>'<p>Q3 Max is Keychron\'s flagship TKL mechanical keyboard, combining a CNC-machined aluminium body with full wireless connectivity and QMK/VIA programmability. The gasket-mount design and sound-dampening foam produce a deep, thocky typing sound preferred by enthusiasts. Hot-swap sockets accept any MX-compatible switch.</p><ul><li><strong>Layout:</strong> TKL (87-key)</li><li><strong>Body:</strong> CNC aluminium, gasket-mount</li><li><strong>Switches:</strong> Keychron K Pro Brown (hot-swap)</li><li><strong>Wireless:</strong> Bluetooth 5.1 + 2.4 GHz USB dongle</li><li><strong>Battery:</strong> 4000mAh</li><li><strong>RGB:</strong> South-facing per-key RGB</li><li><strong>Software:</strong> QMK / VIA</li></ul>'],
            ['sku'=>'TH-MK-002','name'=>'Keychron K8 Pro QMK TKL Keyboard','brand'=>'Keychron','category'=>'mechanical-keyboards','price'=>99.00,'special_price'=>89.00,'weight'=>0.90,'stock'=>62,'new'=>0,'featured'=>0,'short_description'=>'Keychron K8 Pro TKL — hot-swap, QMK/VIA, Bluetooth and 2.4 GHz in a tenkeyless layout.','description'=>'<p>K8 Pro bridges the gap between enthusiast and mainstream mechanical keyboards. QMK/VIA programmability opens up full macro and layer customisation, while hot-swap sockets let you change switches without soldering. Compatible with Mac and Windows from the factory.</p><ul><li><strong>Layout:</strong> TKL (87-key)</li><li><strong>Body:</strong> Plastic, sound-dampening foam</li><li><strong>Switches:</strong> Gateron G Pro 3.0 Brown (hot-swap)</li><li><strong>Wireless:</strong> Bluetooth 5.1 + USB-C wired</li><li><strong>Battery:</strong> 4000mAh</li><li><strong>RGB:</strong> Per-key RGB</li><li><strong>Software:</strong> QMK / VIA</li></ul>'],
            ['sku'=>'TH-MK-003','name'=>'Logitech MX Mechanical Full-Size','brand'=>'Logitech','category'=>'mechanical-keyboards','price'=>169.00,'special_price'=>139.00,'weight'=>0.96,'stock'=>41,'new'=>0,'featured'=>0,'short_description'=>'Logitech MX Mechanical full-size — quiet Tactile Quiet switches, backlit keys and 15-day battery.','description'=>'<p>MX Mechanical targets professionals who want mechanical feel without the noise of gaming keyboards. The Tactile Quiet switches provide tactile feedback with significantly reduced sound versus Cherry MX Browns. Multi-device Bluetooth (3 profiles) and flow cross-computer control integrate with the MX Master ecosystem.</p><ul><li><strong>Layout:</strong> Full-size with numpad</li><li><strong>Switches:</strong> Logitech Tactile Quiet (Brown-alike)</li><li><strong>Wireless:</strong> Bluetooth + Logi Bolt USB receiver</li><li><strong>Battery:</strong> 15 days (backlit) / 5 months (no backlight)</li><li><strong>Multi-device:</strong> Yes (3 devices, Easy-Switch)</li><li><strong>OS Flow:</strong> Yes (copy-paste between computers)</li></ul>'],
            ['sku'=>'TH-MK-004','name'=>'Keychron Q1 Pro 75% QMK Keyboard','brand'=>'Keychron','category'=>'mechanical-keyboards','price'=>199.00,'special_price'=>null,'weight'=>1.35,'stock'=>27,'new'=>1,'featured'=>0,'short_description'=>'Keychron Q1 Pro 75% — CNC aluminium gasket-mount with wireless and QMK/VIA in a compact layout.','description'=>'<p>Q1 Pro brings Keychron\'s premium construction to a 75% layout that fits on crowded desks while retaining function and navigation keys. The CNC-machined aluminium body and gasket mount deliver premium build quality and sound that rivals custom keyboards costing 3–5× more.</p><ul><li><strong>Layout:</strong> 75% (82-key)</li><li><strong>Body:</strong> CNC aluminium, gasket-mount</li><li><strong>Switches:</strong> Keychron K Pro Brown (hot-swap)</li><li><strong>Wireless:</strong> Bluetooth 5.1 + 2.4 GHz</li><li><strong>Battery:</strong> 4000mAh</li><li><strong>RGB:</strong> South-facing per-key RGB</li><li><strong>Software:</strong> QMK / VIA</li></ul>'],
            ['sku'=>'TH-MK-005','name'=>'Ducky One 3 SF 65% Mechanical Keyboard','brand'=>'Keychron','category'=>'mechanical-keyboards','price'=>119.00,'special_price'=>null,'weight'=>0.75,'stock'=>33,'new'=>0,'featured'=>0,'short_description'=>'Ducky One 3 SF 65% with Cherry MX switches, hot-swap PCB and double-shot PBT keycaps.','description'=>'<p>Ducky One 3 SF is Ducky\'s most compact productivity layout, retaining arrow keys and a small navigation cluster at 65% size. Double-shot PBT keycaps are legends that will never fade, and the hot-swap PCB accepts any MX-compatible switch for future upgrades.</p><ul><li><strong>Layout:</strong> 65% (67-key)</li><li><strong>Switches:</strong> Cherry MX Brown (hot-swap)</li><li><strong>Keycaps:</strong> Double-shot PBT</li><li><strong>Connection:</strong> USB-C detachable</li><li><strong>RGB:</strong> Per-key RGB</li><li><strong>Software:</strong> DUCKY Macro 3.0</li></ul>'],
            ['sku'=>'TH-MK-006','name'=>'Keychron C3 Pro TKL Wired Keyboard','brand'=>'Keychron','category'=>'mechanical-keyboards','price'=>39.00,'special_price'=>null,'weight'=>0.60,'stock'=>88,'new'=>0,'featured'=>0,'short_description'=>'Keychron C3 Pro TKL — budget mechanical keyboard with QMK/VIA, hot-swap and Gateron switches.','description'=>'<p>C3 Pro is Keychron\'s most affordable hot-swap mechanical keyboard with QMK/VIA support. At this price, no competitor offers hot-swap sockets AND open-source firmware customisation. The ideal entry point into mechanical keyboards for users who want to experiment with switches.</p><ul><li><strong>Layout:</strong> TKL (87-key)</li><li><strong>Switches:</strong> Gateron G Pro Red (hot-swap)</li><li><strong>Connection:</strong> USB-C wired</li><li><strong>RGB:</strong> Per-key RGB</li><li><strong>Software:</strong> QMK / VIA</li><li><strong>Compatibility:</strong> Mac / Windows</li></ul>'],
            ['sku'=>'TH-MK-007','name'=>'Logitech G PRO X TKL Wired Keyboard','brand'=>'Logitech','category'=>'mechanical-keyboards','price'=>129.00,'special_price'=>99.00,'weight'=>0.98,'stock'=>45,'new'=>0,'featured'=>0,'short_description'=>'Logitech G PRO X TKL — tournament-grade swappable GX switches and LIGHTSYNC RGB for esports.','description'=>'<p>G PRO X is the keyboard Logitech builds for professional esports players. The swappable GX switch system lets you change switch feel without tools — ideal for players who want tactile switches for typing but linear switches for gaming. LIGHTSYNC RGB integrates with G HUB for reactive lighting effects.</p><ul><li><strong>Layout:</strong> TKL (87-key)</li><li><strong>Switches:</strong> GX Brown Tactile (swappable)</li><li><strong>Connection:</strong> USB-A wired (detachable)</li><li><strong>RGB:</strong> LIGHTSYNC RGB, per-key</li><li><strong>Software:</strong> Logitech G HUB</li><li><strong>Build:</strong> Aircraft-grade aluminium top plate</li></ul>'],
        ];
    }

    private static function wireless(): array
    {
        return [
            ['sku'=>'TH-WK-001','name'=>'Logitech MX Keys S Full-Size Wireless','brand'=>'Logitech','category'=>'wireless-keyboards','price'=>119.00,'special_price'=>null,'weight'=>0.81,'stock'=>67,'new'=>1,'featured'=>1,'short_description'=>'Logitech MX Keys S — smart backlighting, fast charging, multi-device and Logitech Flow cross-computer typing.','description'=>'<p>MX Keys S is Logitech\'s premium productivity keyboard, featuring backlit spherical keys with per-finger curvature that speeds up typing accuracy. Smart Backlighting activates only when your hands are near the keyboard. Logitech Flow lets you copy-paste text and files between two computers by simply moving the cursor across screens.</p><ul><li><strong>Layout:</strong> Full-size with numpad</li><li><strong>Keys:</strong> Spherical, backlighted, scissor mechanism</li><li><strong>Wireless:</strong> Bluetooth (3 devices) + Logi Bolt 2.4 GHz</li><li><strong>Battery:</strong> 10 days (backlit) / 5 months (unlit)</li><li><strong>Charging:</strong> USB-C, 1-min charge = 30 min use</li><li><strong>OS Flow:</strong> Yes</li></ul>'],
            ['sku'=>'TH-WK-002','name'=>'Apple Magic Keyboard with Touch ID (USB-C)','brand'=>'Apple','category'=>'wireless-keyboards','price'=>99.00,'special_price'=>null,'weight'=>0.24,'stock'=>52,'new'=>1,'featured'=>0,'short_description'=>'Apple Magic Keyboard with Touch ID — scissor-mechanism keys, Touch ID and USB-C charging.','description'=>'<p>Magic Keyboard with Touch ID enables instant, secure login to your Mac with a fingerprint — no more typing passwords every time you wake the display. The slim, wireless design pairs instantly with any Mac, iPad Pro or iPad Air. Now with USB-C charging (updated from Lightning).</p><ul><li><strong>Layout:</strong> Compact (no numpad)</li><li><strong>Wireless:</strong> Bluetooth 5.0</li><li><strong>Touch ID:</strong> Yes</li><li><strong>Battery:</strong> ~1 month (rechargeable)</li><li><strong>Charging:</strong> USB-C to USB-C cable included</li><li><strong>Compatibility:</strong> Mac (M1 or later), iPad Pro, iPad Air</li></ul>'],
            ['sku'=>'TH-WK-003','name'=>'Logitech K850 Multi-Device Wireless Keyboard','brand'=>'Logitech','category'=>'wireless-keyboards','price'=>49.00,'special_price'=>null,'weight'=>0.56,'stock'=>84,'new'=>0,'featured'=>0,'short_description'=>'Logitech K850 — connects to 3 devices simultaneously, instant switch with Easy-Switch button and palm rest.','description'=>'<p>K850 is the practical multi-device keyboard for users who work across a PC, laptop, and tablet. The Easy-Switch button on the top right instantly re-pairs the keyboard to whichever device you\'re switching to — no menu navigation required. Integrated wrist rest reduces fatigue during long typing sessions.</p><ul><li><strong>Layout:</strong> Full-size with numpad</li><li><strong>Multi-device:</strong> 3 devices simultaneously</li><li><strong>Wireless:</strong> Bluetooth + Logi Bolt USB</li><li><strong>Battery:</strong> 24 months (2× AA)</li><li><strong>Wrist rest:</strong> Integrated</li><li><strong>OS:</strong> Windows, macOS, Chrome OS</li></ul>'],
            ['sku'=>'TH-WK-004','name'=>'Keychron K3 Ultra-Slim Low-Profile TKL','brand'=>'Keychron','category'=>'wireless-keyboards','price'=>89.00,'special_price'=>null,'weight'=>0.53,'stock'=>48,'new'=>0,'featured'=>0,'short_description'=>'Keychron K3 ultra-slim TKL — low-profile optical switches, hot-swap and Bluetooth/USB-C in 75% layout.','description'=>'<p>K3 delivers the mechanical keyboard experience in a slim profile suitable for users who prefer low-profile keys resembling a laptop keyboard. Low-Profile Optical Banana switches provide tactile feedback with extremely fast actuation — no mechanical contact point means near-zero debounce delay.</p><ul><li><strong>Layout:</strong> 75% ultra-slim TKL</li><li><strong>Switches:</strong> Low-Profile Optical Banana (hot-swap)</li><li><strong>Wireless:</strong> Bluetooth 5.1 + USB-C</li><li><strong>Battery:</strong> 4000mAh</li><li><strong>RGB:</strong> Per-key RGB</li><li><strong>Height:</strong> 14.7mm (with feet extended)</li></ul>'],
            ['sku'=>'TH-WK-005','name'=>'Microsoft Sculpt Ergonomic Desktop Keyboard','brand'=>'Dell','category'=>'wireless-keyboards','price'=>99.00,'special_price'=>79.00,'weight'=>0.85,'stock'=>36,'new'=>0,'featured'=>0,'short_description'=>'Microsoft Sculpt Ergonomic Keyboard — split-key layout, dome keys and detachable numpad for wrist health.','description'=>'<p>Sculpt Ergonomic Keyboard uses a split-key layout and domed keyboard bed to maintain a natural hand position and reduce wrist strain. The detachable numpad can be repositioned independently — great for right-handed mouse users who want the numpad on their left. Microsoft\'s most ergonomic keyboard for office professionals.</p><ul><li><strong>Layout:</strong> Split ergonomic with detachable numpad</li><li><strong>Keys:</strong> Sculpted dome</li><li><strong>Wireless:</strong> 2.4 GHz USB nano receiver</li><li><strong>Battery:</strong> ~12 months (AAA)</li><li><strong>Wrist pad:</strong> Included</li></ul>'],
        ];
    }

    private static function gaming(): array
    {
        return [
            ['sku'=>'TH-GK-001','name'=>'Razer Huntsman V3 Pro TKL Analog Keyboard','brand'=>'Razer','category'=>'gaming-keyboards','price'=>249.00,'special_price'=>null,'weight'=>1.31,'stock'=>19,'new'=>1,'featured'=>1,'short_description'=>'Razer Huntsman V3 Pro TKL — Analog optical switches with Rapid Trigger for per-0.1mm actuation control.','description'=>'<p>Huntsman V3 Pro TKL is the most technically advanced gaming keyboard Razer has built. Analog optical switches sense key position continuously — Rapid Trigger mode can actuate at any point from 0.1mm, giving competitive players a decisive edge in games where early key registration matters. The analog input also enables controller-like joystick mapping for any key.</p><ul><li><strong>Switches:</strong> Razer Analog Optical (magnetic sensing)</li><li><strong>Rapid Trigger:</strong> Yes, per-key, 0.1mm precision</li><li><strong>Actuation:</strong> Adjustable 0.1–4.0mm</li><li><strong>Polling Rate:</strong> 8000 Hz</li><li><strong>RGB:</strong> Razer Chroma RGB per-key</li><li><strong>Connection:</strong> USB-C (SpeedFlex cable)</li></ul>'],
            ['sku'=>'TH-GK-002','name'=>'SteelSeries Apex Pro TKL Gen 3 Wireless','brand'=>'SteelSeries','category'=>'gaming-keyboards','price'=>229.00,'special_price'=>null,'weight'=>0.98,'stock'=>24,'new'=>1,'featured'=>1,'short_description'=>'SteelSeries Apex Pro TKL Gen 3 Wireless — OmniPoint 3.0 magnetic switches with 8000 Hz polling.','description'=>'<p>Apex Pro TKL Gen 3 is the first wireless keyboard with 8000 Hz polling rate, ensuring that key presses are registered with sub-0.125ms precision. OmniPoint 3.0 magnetic switches allow per-key actuation adjustment from 0.1mm to 4.0mm. The included OLED display shows profile, actuation, and Discord notifications.</p><ul><li><strong>Switches:</strong> OmniPoint 3.0 Adjustable (0.1–4.0mm)</li><li><strong>Polling Rate:</strong> 8000 Hz (wired) / 4000 Hz (wireless)</li><li><strong>Wireless:</strong> 2.4 GHz Quantum 2.0 + USB-C</li><li><strong>Battery:</strong> 50 hours</li><li><strong>OLED Display:</strong> Yes</li><li><strong>RGB:</strong> Per-key Prism Sync RGB</li></ul>'],
            ['sku'=>'TH-GK-003','name'=>'Corsair K70 RGB Pro TKL Gaming Keyboard','brand'=>'Corsair','category'=>'gaming-keyboards','price'=>109.00,'special_price'=>89.00,'weight'=>0.96,'stock'=>47,'new'=>0,'featured'=>0,'short_description'=>'Corsair K70 RGB Pro TKL — Cherry MX Speed switches, aircraft-grade aluminium frame and iCUE RGB.','description'=>'<p>K70 RGB Pro TKL is Corsair\'s workhorse gaming keyboard — reliable Cherry MX Speed Silver linear switches, solid aluminium frame, and full iCUE software integration for macros, lighting, and dynamic media controls. A trusted choice for competitive gamers who prioritise reliability.</p><ul><li><strong>Layout:</strong> TKL (87-key)</li><li><strong>Switches:</strong> Cherry MX Speed Silver (linear, 1.2mm actuation)</li><li><strong>Frame:</strong> Aircraft-grade anodised aluminium</li><li><strong>RGB:</strong> Per-key iCUE LIGHTSYNC</li><li><strong>Connection:</strong> USB-A (braided cable)</li><li><strong>Software:</strong> Corsair iCUE</li></ul>'],
            ['sku'=>'TH-GK-004','name'=>'Logitech G915 TKL LIGHTSPEED Wireless','brand'=>'Logitech','category'=>'gaming-keyboards','price'=>229.00,'special_price'=>199.00,'weight'=>0.82,'stock'=>31,'new'=>0,'featured'=>0,'short_description'=>'Logitech G915 TKL LIGHTSPEED — ultra-slim wireless gaming keyboard with GL low-profile switches and 40-hour battery.','description'=>'<p>G915 TKL LIGHTSPEED is one of the few wireless gaming keyboards with a genuinely ultra-slim profile — at 22mm it is barely taller than a laptop keyboard. LIGHTSPEED wireless delivers sub-1ms latency, making it indistinguishable from wired in gaming scenarios. Battery life of 40 hours in lit mode is exceptional for a wireless gaming keyboard.</p><ul><li><strong>Switches:</strong> GL Tactile low-profile</li><li><strong>Wireless:</strong> LIGHTSPEED 2.4 GHz + Bluetooth</li><li><strong>Battery:</strong> 40 hours (RGB) / 135 hours (no RGB)</li><li><strong>Height:</strong> 22mm (ultra-slim)</li><li><strong>RGB:</strong> LIGHTSYNC RGB per-key</li></ul>'],
            ['sku'=>'TH-GK-005','name'=>'Razer BlackWidow V4 Pro Wireless Full-Size','brand'=>'Razer','category'=>'gaming-keyboards','price'=>229.00,'special_price'=>null,'weight'=>1.45,'stock'=>22,'new'=>1,'featured'=>0,'short_description'=>'Razer BlackWidow V4 Pro Wireless — multi-function roller, media keys, magnetic wrist rest and Razer Yellow switches.','description'=>'<p>BlackWidow V4 Pro Wireless is Razer\'s feature-maximalist full-size gaming keyboard. The multi-function dial controls volume, media, and in-game settings. Razer Yellow linear switches actuate at 1.2mm for rapid key repeats. The magnetic memory foam wrist rest attaches magnetically without clips or screws.</p><ul><li><strong>Switches:</strong> Razer Yellow Linear (1.2mm actuation)</li><li><strong>Wireless:</strong> HyperSpeed 2.4 GHz + Bluetooth 5.0</li><li><strong>Battery:</strong> 200 hours (no RGB)</li><li><strong>Multi-function dial:</strong> Yes</li><li><strong>Wrist Rest:</strong> Magnetic memory foam included</li><li><strong>RGB:</strong> Razer Chroma per-key</li></ul>'],
            ['sku'=>'TH-GK-006','name'=>'SteelSeries Apex 9 Mini 60% Gaming Keyboard','brand'=>'SteelSeries','category'=>'gaming-keyboards','price'=>79.00,'special_price'=>null,'weight'=>0.63,'stock'=>53,'new'=>0,'featured'=>0,'short_description'=>'SteelSeries Apex 9 Mini 60% — OptiPoint optical switches, Rapid Trigger and compact layout for travel gaming.','description'=>'<p>Apex 9 Mini delivers rapid-trigger optical switch technology in a compact 60% form factor. At just 308g it\'s the lightest keyboard in the Apex Pro family, ideal for LAN parties and travel. OptiPoint optical switches with adjustable actuation from 0.2–3.8mm provide competitive advantages in time-critical titles.</p><ul><li><strong>Layout:</strong> 60% (61-key)</li><li><strong>Switches:</strong> OptiPoint optical (0.2–3.8mm actuation)</li><li><strong>Rapid Trigger:</strong> Yes</li><li><strong>Connection:</strong> USB-C detachable</li><li><strong>RGB:</strong> Per-key RGB illumination</li><li><strong>Weight:</strong> 308g</li></ul>'],
        ];
    }
}
