<?php

namespace Database\Seeders\ProductData;

class LaptopData
{
    public static function get(): array
    {
        return array_merge(
            self::ultrabooks(),
            self::professionalLaptops(),
            self::gamingLaptops(),
            self::businessLaptops(),
            self::budgetLaptops(),
        );
    }

    private static function ultrabooks(): array
    {
        return [
            ['sku'=>'TH-UB-001','name'=>'Apple MacBook Air 13" M3','brand'=>'Apple','category'=>'ultrabooks','price'=>1099.00,'special_price'=>null,'weight'=>1.24,'stock'=>52,'new'=>1,'featured'=>1,'short_description'=>'Fanless MacBook Air with M3 chip, 18-hour battery and Liquid Retina display.','description'=>'<p>MacBook Air 13-inch with M3 is a powerhouse in a featherweight design. Completely silent with no fan, it handles demanding workloads all day on a single charge. Available in Midnight, Starlight, Space Gray, and Silver.</p><ul><li><strong>Chip:</strong> Apple M3 (8-core CPU, 10-core GPU)</li><li><strong>Memory:</strong> 8GB unified memory</li><li><strong>Storage:</strong> 256GB SSD</li><li><strong>Display:</strong> 13.6" Liquid Retina, 2560×1664, 224ppi</li><li><strong>Battery:</strong> Up to 18 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 3, MagSafe 3, 3.5mm</li><li><strong>Wireless:</strong> Wi-Fi 6E, Bluetooth 5.3</li><li><strong>Weight:</strong> 1.24 kg</li></ul>'],
            ['sku'=>'TH-UB-002','name'=>'Apple MacBook Air 15" M3','brand'=>'Apple','category'=>'ultrabooks','price'=>1299.00,'special_price'=>null,'weight'=>1.51,'stock'=>38,'new'=>1,'featured'=>0,'short_description'=>'Bigger screen, same M3 power — the largest MacBook Air ever with 15-inch Liquid Retina display.','description'=>'<p>MacBook Air 15-inch brings M3 performance to a spacious 15.3-inch canvas. Perfect for multitasking, spreadsheets, and media, all without a fan or charger anxiety.</p><ul><li><strong>Chip:</strong> Apple M3 (8-core CPU, 10-core GPU)</li><li><strong>Memory:</strong> 8GB unified memory</li><li><strong>Storage:</strong> 256GB SSD</li><li><strong>Display:</strong> 15.3" Liquid Retina, 2880×1864, 224ppi</li><li><strong>Battery:</strong> Up to 18 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 3, MagSafe 3, 3.5mm</li><li><strong>Weight:</strong> 1.51 kg</li></ul>'],
            ['sku'=>'TH-UB-003','name'=>'Dell XPS 13 Plus 9320 (i7-1360P)','brand'=>'Dell','category'=>'ultrabooks','price'=>1349.00,'special_price'=>1199.00,'weight'=>1.26,'stock'=>29,'new'=>0,'featured'=>0,'short_description'=>'Dell\'s most advanced 13-inch laptop with edge-to-edge keyboard, OLED display option and 12th-gen Intel Core i7.','description'=>'<p>The XPS 13 Plus redefines the ultrabook with a capacitive function row, seamless haptic touchpad and stunning InfinityEdge display. Premium build quality in machined aluminium and Gorilla Glass.</p><ul><li><strong>Processor:</strong> Intel Core i7-1360P (12-core)</li><li><strong>Memory:</strong> 16GB LPDDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 13.4" OLED Touch, 3.5K (3456×2160), 60Hz</li><li><strong>Battery:</strong> Up to 13 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 3.5mm</li><li><strong>Wireless:</strong> Wi-Fi 6E, Bluetooth 5.2</li><li><strong>Weight:</strong> 1.26 kg</li></ul>'],
            ['sku'=>'TH-UB-004','name'=>'HP Spectre x360 14" OLED (i7-1355U)','brand'=>'HP','category'=>'ultrabooks','price'=>1449.00,'special_price'=>null,'weight'=>1.40,'stock'=>24,'new'=>0,'featured'=>0,'short_description'=>'2-in-1 ultrabook with 13th-gen Intel Core i7, stunning OLED touch display and 360° hinge.','description'=>'<p>The Spectre x360 14 combines luxury design with versatile 2-in-1 functionality. The OLED display delivers breathtaking colour accuracy for content creators, while the 360° hinge enables tent, stand and tablet modes.</p><ul><li><strong>Processor:</strong> Intel Core i7-1355U (10-core)</li><li><strong>Memory:</strong> 16GB LPDDR4x</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 13.5" 3K2K OLED Touch (2880×1920), 60Hz, 100% DCI-P3</li><li><strong>Pen:</strong> HP Tilt Pen included</li><li><strong>Battery:</strong> Up to 17 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 1× USB-A, microSD, 3.5mm</li><li><strong>Weight:</strong> 1.40 kg</li></ul>'],
            ['sku'=>'TH-UB-005','name'=>'Lenovo ThinkPad X1 Carbon Gen 12 (i7-1365U)','brand'=>'Lenovo','category'=>'ultrabooks','price'=>1649.00,'special_price'=>null,'weight'=>1.12,'stock'=>18,'new'=>1,'featured'=>0,'short_description'=>'The world\'s lightest 14" business ultrabook at 1.12 kg, with MIL-SPEC durability and Intel vPro security.','description'=>'<p>ThinkPad X1 Carbon Gen 12 is engineered for professionals who demand performance without compromise. At just 1.12 kg, it survives drop tests, temperature extremes, and humidity — all while delivering all-day battery life.</p><ul><li><strong>Processor:</strong> Intel Core i7-1365U (10-core) with vPro</li><li><strong>Memory:</strong> 16GB LPDDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" IPS 2.8K (2880×1800), 90Hz, 400 nits</li><li><strong>Battery:</strong> Up to 15 hours</li><li><strong>Security:</strong> ThinkShield, IR camera, fingerprint reader, TPM 2.0</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 2× USB-A, HDMI 2.1, SD, 3.5mm</li><li><strong>Weight:</strong> 1.12 kg</li></ul>'],
            ['sku'=>'TH-UB-006','name'=>'ASUS ZenBook 14 OLED (Ryzen 7 7745HX)','brand'=>'ASUS','category'=>'ultrabooks','price'=>999.00,'special_price'=>null,'weight'=>1.39,'stock'=>35,'new'=>0,'featured'=>0,'short_description'=>'ASUS ZenBook 14 with AMD Ryzen 7, brilliant 2.8K OLED display and 1,000,000:1 contrast ratio.','description'=>'<p>ZenBook 14 OLED delivers professional-grade visuals on a 2.8K OLED display certified PANTONE Validated with 100% DCI-P3 coverage — ideal for design, photo editing and film. All wrapped in a slim 15.9mm aluminium chassis.</p><ul><li><strong>Processor:</strong> AMD Ryzen 7 7745HX (8-core)</li><li><strong>Memory:</strong> 16GB LPDDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" 2.8K OLED (2880×1800), 90Hz, 600 nits, 100% DCI-P3</li><li><strong>Battery:</strong> Up to 10 hours</li><li><strong>Ports:</strong> 1× USB4, 1× USB-C 3.2, 2× USB-A, HDMI, microSD, 3.5mm</li><li><strong>Weight:</strong> 1.39 kg</li></ul>'],
            ['sku'=>'TH-UB-007','name'=>'HP Envy x360 14" (Ryzen 7 7730U)','brand'=>'HP','category'=>'ultrabooks','price'=>799.00,'special_price'=>699.00,'weight'=>1.49,'stock'=>43,'new'=>0,'featured'=>0,'short_description'=>'Versatile 2-in-1 with AMD Ryzen 7, OLED touch display and all-day battery at an accessible price.','description'=>'<p>The Envy x360 14 brings premium 2-in-1 features to a more accessible price point. With an OLED display and Ryzen 7 processor, it handles creative work, video calls, and entertainment with ease.</p><ul><li><strong>Processor:</strong> AMD Ryzen 7 7730U (8-core)</li><li><strong>Memory:</strong> 16GB DDR4</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" OLED Touch (1920×1200), 90Hz</li><li><strong>Battery:</strong> Up to 17 hours</li><li><strong>Ports:</strong> 1× USB4, 1× USB-C, 2× USB-A, microSD, 3.5mm</li><li><strong>Weight:</strong> 1.49 kg</li></ul>'],
            ['sku'=>'TH-UB-008','name'=>'LG Gram 14 (i7-1360P)','brand'=>'LG','category'=>'ultrabooks','price'=>1099.00,'special_price'=>null,'weight'=>0.99,'stock'=>27,'new'=>0,'featured'=>0,'short_description'=>'Sub-1 kg ultrabook with MIL-STD-810H certification, 16:10 IPS display and 80Wh battery.','description'=>'<p>LG Gram 14 weighs under 1 kg yet passes 7 MIL-STD-810H durability tests. The huge 80Wh battery provides all-day runtime, and the 16:10 display ratio gives you more vertical screen space for productivity.</p><ul><li><strong>Processor:</strong> Intel Core i7-1360P (12-core)</li><li><strong>Memory:</strong> 16GB LPDDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" IPS (1920×1200), 60Hz, 350 nits</li><li><strong>Battery:</strong> 80Wh, up to 22 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 2× USB-A, HDMI, microSD, 3.5mm</li><li><strong>Weight:</strong> 0.99 kg</li></ul>'],
            ['sku'=>'TH-UB-009','name'=>'Samsung Galaxy Book3 Pro 14" (i7-1360P)','brand'=>'Samsung','category'=>'ultrabooks','price'=>1199.00,'special_price'=>null,'weight'=>1.17,'stock'=>21,'new'=>0,'featured'=>0,'short_description'=>'Ultra-slim Samsung ultrabook with Dynamic AMOLED 2X display and seamless Galaxy ecosystem integration.','description'=>'<p>Galaxy Book3 Pro integrates perfectly into the Samsung ecosystem — unlock with your Galaxy Watch, continue apps from your phone, and share files wirelessly. The Dynamic AMOLED 2X display covers 120% DCI-P3 with HDR support.</p><ul><li><strong>Processor:</strong> Intel Core i7-1360P (12-core)</li><li><strong>Memory:</strong> 16GB LPDDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" Dynamic AMOLED 2X (1920×1200), 120Hz, 400 nits</li><li><strong>Battery:</strong> 63Wh, up to 22 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 1× USB-A, HDMI, microSD, 3.5mm</li><li><strong>Weight:</strong> 1.17 kg</li></ul>'],
            ['sku'=>'TH-UB-010','name'=>'Lenovo Yoga 9i 14" OLED (i7-1355U)','brand'=>'Lenovo','category'=>'ultrabooks','price'=>1399.00,'special_price'=>null,'weight'=>1.39,'stock'=>19,'new'=>0,'featured'=>0,'short_description'=>'Premium 2-in-1 with 14" OLED Dolby Vision display, rotating soundbar and 360-degree rotating hinge.','description'=>'<p>Yoga 9i 14 is Lenovo\'s flagship 2-in-1, featuring a rotating soundbar with Dolby Atmos, OLED touch display, and a 360° hinge wrapped in genuine Italian leather palm rest. A statement laptop for executives and creatives.</p><ul><li><strong>Processor:</strong> Intel Core i7-1355U (10-core)</li><li><strong>Memory:</strong> 16GB LPDDR5x</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 14" OLED Touch (2880×1800), 90Hz, 100% DCI-P3, Dolby Vision</li><li><strong>Audio:</strong> Rotating soundbar with Bowers & Wilkins speakers</li><li><strong>Battery:</strong> 75Wh, up to 13 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 2× USB-A, HDMI, 3.5mm</li><li><strong>Weight:</strong> 1.39 kg</li></ul>'],
            ['sku'=>'TH-UB-011','name'=>'ASUS ZenBook Pro 14 OLED (i9-13900H)','brand'=>'ASUS','category'=>'ultrabooks','price'=>1399.00,'special_price'=>null,'weight'=>1.65,'stock'=>15,'new'=>0,'featured'=>0,'short_description'=>'Creator ultrabook with Intel Core i9 CPU, dedicated RTX 3050 GPU and ScreenPad Plus secondary display.','description'=>'<p>ZenBook Pro 14 OLED delivers workstation-class performance in a portable form. The innovative ScreenPad Plus secondary display doubles your workflow with drag-and-drop app control, while the OLED main panel delivers reference-grade colour accuracy.</p><ul><li><strong>Processor:</strong> Intel Core i9-13900H (14-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 3050 6GB</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 14.5" 2.8K OLED (2880×1800), 120Hz, 600 nits, 100% DCI-P3</li><li><strong>Battery:</strong> 76Wh, up to 7 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 2× USB-A, HDMI 2.1, SD, 3.5mm</li><li><strong>Weight:</strong> 1.65 kg</li></ul>'],
            ['sku'=>'TH-UB-012','name'=>'Dell XPS 13 9315 (i5-1230U)','brand'=>'Dell','category'=>'ultrabooks','price'=>899.00,'special_price'=>749.00,'weight'=>1.17,'stock'=>33,'new'=>0,'featured'=>0,'short_description'=>'Entry-level XPS 13 with Intel Core i5, compact design and InfinityEdge display — premium quality at an accessible price.','description'=>'<p>The XPS 13 9315 brings Dell\'s iconic InfinityEdge design to a more accessible price point. Compact enough to slip into any bag, yet powerful enough to handle everyday productivity tasks and video streaming with ease.</p><ul><li><strong>Processor:</strong> Intel Core i5-1230U (10-core)</li><li><strong>Memory:</strong> 8GB LPDDR5</li><li><strong>Storage:</strong> 256GB NVMe SSD</li><li><strong>Display:</strong> 13.4" FHD+ (1920×1200), 60Hz, 500 nits</li><li><strong>Battery:</strong> 51Wh, up to 12 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 3.5mm</li><li><strong>Weight:</strong> 1.17 kg</li></ul>'],
        ];
    }

    private static function professionalLaptops(): array
    {
        return [
            ['sku'=>'TH-PL-001','name'=>'Apple MacBook Pro 14" M4','brand'=>'Apple','category'=>'professional-laptops','price'=>1999.00,'special_price'=>null,'weight'=>1.55,'stock'=>47,'new'=>1,'featured'=>1,'short_description'=>'M4 chip with 10-core CPU, 10-core GPU and up to 24 hours battery — the most capable 14" laptop.','description'=>'<p>MacBook Pro 14-inch with M4 delivers unprecedented performance for pro workflows. Whether rendering 3D, compiling large codebases, or editing ProRes video, M4 handles it all while staying cool and silent thanks to an advanced thermal system.</p><ul><li><strong>Chip:</strong> Apple M4 (10-core CPU, 10-core GPU, 16-core Neural Engine)</li><li><strong>Memory:</strong> 16GB unified memory</li><li><strong>Storage:</strong> 512GB SSD</li><li><strong>Display:</strong> 14.2" Liquid Retina XDR (3024×1964, 254ppi), ProMotion 120Hz</li><li><strong>Camera:</strong> 12MP Center Stage</li><li><strong>Battery:</strong> Up to 24 hours</li><li><strong>Ports:</strong> 3× Thunderbolt 4, HDMI 2.1, SDXC, MagSafe 3, 3.5mm</li><li><strong>Weight:</strong> 1.55 kg</li></ul>'],
            ['sku'=>'TH-PL-002','name'=>'Apple MacBook Pro 14" M4 Pro','brand'=>'Apple','category'=>'professional-laptops','price'=>2499.00,'special_price'=>null,'weight'=>1.61,'stock'=>29,'new'=>1,'featured'=>1,'short_description'=>'M4 Pro with 14-core CPU and 20-core GPU — for intensive pro workflows in audio, video, and 3D.','description'=>'<p>MacBook Pro 14-inch with M4 Pro takes performance to a new level. The 14-core CPU and 20-core GPU deliver up to 2× faster performance than the previous generation, making it the go-to machine for music producers, 3D artists, and developers.</p><ul><li><strong>Chip:</strong> Apple M4 Pro (14-core CPU, 20-core GPU)</li><li><strong>Memory:</strong> 24GB unified memory</li><li><strong>Storage:</strong> 512GB SSD</li><li><strong>Display:</strong> 14.2" Liquid Retina XDR, ProMotion 120Hz</li><li><strong>Battery:</strong> Up to 22 hours</li><li><strong>Ports:</strong> 3× Thunderbolt 5, HDMI 2.1, SDXC, MagSafe 3, 3.5mm</li><li><strong>Weight:</strong> 1.61 kg</li></ul>'],
            ['sku'=>'TH-PL-003','name'=>'Apple MacBook Pro 16" M4 Max','brand'=>'Apple','category'=>'professional-laptops','price'=>3499.00,'special_price'=>null,'weight'=>2.14,'stock'=>12,'new'=>1,'featured'=>1,'short_description'=>'M4 Max with 16-core CPU, 40-core GPU and 128GB memory option — the ultimate professional workstation.','description'=>'<p>MacBook Pro 16-inch with M4 Max is the most powerful Mac laptop ever made. Capable of running full DaVinci Resolve projects natively, handling 8K ProRes video, and compiling million-line codebases — all on battery power for up to 22 hours.</p><ul><li><strong>Chip:</strong> Apple M4 Max (16-core CPU, 40-core GPU)</li><li><strong>Memory:</strong> 48GB unified memory (upgradeable to 128GB)</li><li><strong>Storage:</strong> 1TB SSD</li><li><strong>Display:</strong> 16.2" Liquid Retina XDR (3456×2234, 254ppi), ProMotion 120Hz</li><li><strong>Battery:</strong> Up to 22 hours</li><li><strong>Ports:</strong> 3× Thunderbolt 5, HDMI 2.1, SDXC, MagSafe 3, 3.5mm</li><li><strong>Weight:</strong> 2.14 kg</li></ul>'],
            ['sku'=>'TH-PL-004','name'=>'Dell XPS 15 9530 (i9-13900H, RTX 4060)','brand'=>'Dell','category'=>'professional-laptops','price'=>1899.00,'special_price'=>null,'weight'=>1.86,'stock'=>22,'new'=>0,'featured'=>0,'short_description'=>'Dell\'s flagship 15-inch laptop with 13th-gen Intel Core i9, RTX 4060 and 3.5K OLED display.','description'=>'<p>XPS 15 9530 is built for creatives and developers who need discrete GPU power in a portable form. The stunning 3.5K OLED touch display and 13th-gen Intel CPU deliver workstation-class performance without workstation weight.</p><ul><li><strong>Processor:</strong> Intel Core i9-13900H (14-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4060 8GB</li><li><strong>Memory:</strong> 32GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 15.6" OLED Touch (3456×2160), 60Hz, 400 nits, 100% DCI-P3</li><li><strong>Battery:</strong> 86Wh, up to 13 hours</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 1× USB-A, SD, HDMI 2.1, 3.5mm</li><li><strong>Weight:</strong> 1.86 kg</li></ul>'],
            ['sku'=>'TH-PL-005','name'=>'ASUS ProArt Studiobook 16 OLED (i9-13980HX)','brand'=>'ASUS','category'=>'professional-laptops','price'=>2199.00,'special_price'=>null,'weight'=>2.40,'stock'=>14,'new'=>0,'featured'=>0,'short_description'=>'ASUS creator laptop with OLED ProArt display, RTX 4060 GPU and PANTONE Validated colour accuracy.','description'=>'<p>ProArt Studiobook 16 is purpose-built for digital artists and content creators. PANTONE Validated with 100% DCI-P3, the OLED display ensures colours are accurate right out of the box — no calibration required.</p><ul><li><strong>Processor:</strong> Intel Core i9-13980HX (24-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4060 8GB</li><li><strong>Memory:</strong> 32GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 16" 4K OLED (3840×2400), 120Hz, 550 nits, 100% DCI-P3</li><li><strong>Stylus:</strong> ASUS Pen 2.0 included</li><li><strong>Ports:</strong> 1× Thunderbolt 4, 3× USB-A, HDMI 2.1, SD, 3.5mm</li><li><strong>Weight:</strong> 2.40 kg</li></ul>'],
            ['sku'=>'TH-PL-006','name'=>'HP ZBook Studio G10 (i9-13900H, RTX A2000)','brand'=>'HP','category'=>'professional-laptops','price'=>2799.00,'special_price'=>null,'weight'=>1.79,'stock'=>9,'new'=>0,'featured'=>0,'short_description'=>'HP mobile workstation with ISV-certified NVIDIA RTX A2000 and DreamColor OLED display.','description'=>'<p>ZBook Studio G10 is ISV-certified for professional applications including AutoCAD, SolidWorks, and Adobe Creative Cloud. The NVIDIA RTX A2000 professional GPU provides certified stability and ECC memory support.</p><ul><li><strong>Processor:</strong> Intel Core i9-13900H (14-core)</li><li><strong>GPU:</strong> NVIDIA RTX A2000 8GB (Professional)</li><li><strong>Memory:</strong> 32GB DDR5 ECC</li><li><strong>Storage:</strong> 1TB Z Turbo SSD</li><li><strong>Display:</strong> 16" DreamColor OLED (3840×2400), 120Hz, 600 nits, 100% DCI-P3</li><li><strong>Security:</strong> HP Wolf Security, Fingerprint, IR camera</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 2× USB-A, HDMI 2.1, SD, 3.5mm</li><li><strong>Weight:</strong> 1.79 kg</li></ul>'],
            ['sku'=>'TH-PL-007','name'=>'MSI Creator Z16P B12UHST (i7-12700H, RTX 3080 Ti)','brand'=>'MSI','category'=>'professional-laptops','price'=>2999.00,'special_price'=>null,'weight'=>2.45,'stock'=>7,'new'=>0,'featured'=>0,'short_description'=>'MSI creator powerhouse with RTX 3080 Ti, 4K UHD+ mini LED display and True Pixel calibration.','description'=>'<p>Creator Z16P B12UHST delivers workstation GPU power with the mobility of a laptop. The 16" mini LED display with True Pixel calibration comes pre-calibrated to Delta E&lt;2 accuracy from the factory.</p><ul><li><strong>Processor:</strong> Intel Core i7-12700H (14-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 3080 Ti 16GB</li><li><strong>Memory:</strong> 64GB DDR5</li><li><strong>Storage:</strong> 2TB NVMe SSD</li><li><strong>Display:</strong> 16" QHD+ mini LED (2560×1600), 165Hz, 1000 nits, 100% DCI-P3</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 3× USB-A, HDMI 2.1, SD, 3.5mm</li><li><strong>Weight:</strong> 2.45 kg</li></ul>'],
            ['sku'=>'TH-PL-008','name'=>'Lenovo ThinkPad X1 Extreme Gen 5 (i9-12900H)','brand'=>'Lenovo','category'=>'professional-laptops','price'=>3199.00,'special_price'=>null,'weight'=>1.82,'stock'=>6,'new'=>0,'featured'=>0,'short_description'=>'Business-class performance laptop with Intel Core i9, RTX 3080 Ti and enterprise security features.','description'=>'<p>ThinkPad X1 Extreme Gen 5 bridges the gap between enterprise durability and creator performance. MIL-SPEC tested, with ThinkShield security stack and optional 4K OLED display for visual professionals.</p><ul><li><strong>Processor:</strong> Intel Core i9-12900H (14-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 3080 Ti 16GB</li><li><strong>Memory:</strong> 64GB DDR5</li><li><strong>Storage:</strong> 2TB NVMe SSD</li><li><strong>Display:</strong> 16" IPS UHD+ (3840×2400), 60Hz, 600 nits</li><li><strong>Security:</strong> ThinkShield, Match-on-Chip fingerprint, IR camera, dTPM 2.0</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 3× USB-A, HDMI 2.1, SD, 3.5mm</li><li><strong>Weight:</strong> 1.82 kg</li></ul>'],
        ];
    }

    private static function gamingLaptops(): array
    {
        return [
            ['sku'=>'TH-GL-001','name'=>'ASUS ROG Zephyrus G14 2024 (Ryzen 9 8945HS, RTX 4060)','brand'=>'ASUS','category'=>'gaming-laptops','price'=>1499.00,'special_price'=>null,'weight'=>1.65,'stock'=>31,'new'=>1,'featured'=>1,'short_description'=>'Ultra-portable gaming laptop with AMD Ryzen 9, RTX 4060 and mini LED AniMe Matrix display.','description'=>'<p>ROG Zephyrus G14 2024 packs RTX 4060 performance into one of the most portable gaming laptops available. The AniMe Matrix mini LED dot-matrix display on the lid is fully customisable, while the internals remain whisper-quiet thanks to ROG\'s liquid metal thermal solution.</p><ul><li><strong>Processor:</strong> AMD Ryzen 9 8945HS (8-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4060 8GB</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 14" QHD+ ROG Nebula Display (2560×1600), 165Hz, 500 nits</li><li><strong>Battery:</strong> 73Wh</li><li><strong>Ports:</strong> 1× USB4, 1× USB-C 3.2, 2× USB-A, HDMI 2.1, SD, 3.5mm</li><li><strong>Weight:</strong> 1.65 kg</li></ul>'],
            ['sku'=>'TH-GL-002','name'=>'ASUS ROG Strix SCAR 16 (i9-14900HX, RTX 4080)','brand'=>'ASUS','category'=>'gaming-laptops','price'=>2799.00,'special_price'=>null,'weight'=>2.50,'stock'=>12,'new'=>1,'featured'=>0,'short_description'=>'ROG flagship gaming laptop with Intel Core i9, RTX 4080 and 240Hz QHD+ ROG Nebula HDR display.','description'=>'<p>ROG Strix SCAR 16 is built for esports pros and enthusiast gamers. The 16" QHD+ 240Hz display with Nebula HDR technology reaches 1100 nits peak brightness, while the ROG MUX Switch eliminates GPU switching latency for maximum frame rates.</p><ul><li><strong>Processor:</strong> Intel Core i9-14900HX (24-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4080 12GB</li><li><strong>Memory:</strong> 32GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 16" QHD+ (2560×1600), 240Hz ROG Nebula HDR, 1100 nits</li><li><strong>Cooling:</strong> Tri-fan with Pulsar heatsink</li><li><strong>Weight:</strong> 2.50 kg</li></ul>'],
            ['sku'=>'TH-GL-003','name'=>'MSI Titan GT77 HX (i9-13980HX, RTX 4090)','brand'=>'MSI','category'=>'gaming-laptops','price'=>4999.00,'special_price'=>null,'weight'=>3.30,'stock'=>5,'new'=>0,'featured'=>0,'short_description'=>'Desktop-replacement powerhouse with RTX 4090 16GB, Cherry MX Ultra-Low Profile keyboard and 4K 144Hz display.','description'=>'<p>MSI Titan GT77 HX is the closest thing to a desktop PC in laptop form. The full 175W TGP RTX 4090 is the same GPU you\'d find in a high-end desktop build, delivering uncompromising 4K gaming performance.</p><ul><li><strong>Processor:</strong> Intel Core i9-13980HX (24-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4090 16GB (175W TGP)</li><li><strong>Memory:</strong> 64GB DDR5</li><li><strong>Storage:</strong> 2× 1TB NVMe SSD (RAID 0)</li><li><strong>Display:</strong> 17.3" 4K UHD (3840×2160), 144Hz, mini LED, 1000 nits</li><li><strong>Keyboard:</strong> Cherry MX Ultra Low Profile mechanical</li><li><strong>Weight:</strong> 3.30 kg</li></ul>'],
            ['sku'=>'TH-GL-004','name'=>'Razer Blade 16 (i9-13950HX, RTX 4090)','brand'=>'Razer','category'=>'gaming-laptops','price'=>4499.00,'special_price'=>null,'weight'=>2.63,'stock'=>8,'new'=>0,'featured'=>0,'short_description'=>'Razer\'s flagship with dual-mode OLED/mini LED display, RTX 4090 and CNC-machined aluminium chassis.','description'=>'<p>Razer Blade 16 features the world\'s first dual-mode display — switch between 4K 60Hz OLED mode for creative work and 1080p 240Hz mini LED mode for competitive gaming, all in one panel. The CNC-machined aluminium body is a design masterpiece.</p><ul><li><strong>Processor:</strong> Intel Core i9-13950HX (24-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4090 16GB</li><li><strong>Memory:</strong> 32GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 16" Dual-Mode OLED/mini LED (4K OLED 60Hz / FHD 240Hz)</li><li><strong>Chassis:</strong> CNC-machined anodised aluminium</li><li><strong>Weight:</strong> 2.63 kg</li></ul>'],
            ['sku'=>'TH-GL-005','name'=>'Lenovo Legion Pro 7i Gen 9 (i9-14900HX, RTX 4080)','brand'=>'Lenovo','category'=>'gaming-laptops','price'=>2499.00,'special_price'=>null,'weight'=>2.85,'stock'=>18,'new'=>1,'featured'=>0,'short_description'=>'Lenovo Legion flagship with Intel Core i9, RTX 4080 Super and coldfront 5.0 cooling system.','description'=>'<p>Legion Pro 7i Gen 9 combines extreme processing power with Lenovo\'s most advanced Coldfront 5.0 cooling, maintaining peak GPU and CPU performance simultaneously under sustained load. The 2.5K 240Hz display gives competitive gamers a decisive edge.</p><ul><li><strong>Processor:</strong> Intel Core i9-14900HX (24-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4080 Super 12GB</li><li><strong>Memory:</strong> 32GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 16" 2.5K IPS (2560×1600), 240Hz, 500 nits</li><li><strong>Cooling:</strong> Coldfront 5.0, Legion AI Engine+</li><li><strong>Weight:</strong> 2.85 kg</li></ul>'],
            ['sku'=>'TH-GL-006','name'=>'HP OMEN 16 (i7-13700H, RTX 4070)','brand'=>'HP','category'=>'gaming-laptops','price'=>1599.00,'special_price'=>1399.00,'weight'=>2.29,'stock'=>24,'new'=>0,'featured'=>0,'short_description'=>'HP OMEN 16 with Intel Core i7, RTX 4070 and 165Hz QHD display — serious gaming without the flagship price.','description'=>'<p>OMEN 16 delivers high-refresh QHD gaming performance at a compelling price. The RTX 4070 handles modern games at 1440p with ease, while OMEN Command Center gives you control over performance, lighting and network prioritisation.</p><ul><li><strong>Processor:</strong> Intel Core i7-13700H (14-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4070 8GB</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 16.1" QHD (2560×1440), 165Hz, IPS</li><li><strong>Cooling:</strong> OMEN Tempest Cooling</li><li><strong>Weight:</strong> 2.29 kg</li></ul>'],
            ['sku'=>'TH-GL-007','name'=>'Dell Alienware m18 R2 (i9-14900HX, RTX 4090)','brand'=>'Dell','category'=>'gaming-laptops','price'=>3999.00,'special_price'=>null,'weight'=>4.20,'stock'=>6,'new'=>1,'featured'=>0,'short_description'=>'Alienware\'s largest gaming laptop with an 18" 1200p 480Hz display and full-power RTX 4090.','description'=>'<p>Alienware m18 R2 is the desktop replacement for gamers who refuse to compromise. The 18-inch display with 480Hz refresh rate gives you a frame rate ceiling most games cannot reach. Quad-zone RGB keyboard and Cherry MX Ultra Low Profile switches complete the experience.</p><ul><li><strong>Processor:</strong> Intel Core i9-14900HX (24-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4090 16GB</li><li><strong>Memory:</strong> 64GB DDR5</li><li><strong>Storage:</strong> 2× 1TB NVMe SSD</li><li><strong>Display:</strong> 18" FHD+ (1920×1200), 480Hz, IPS</li><li><strong>Keyboard:</strong> Cherry MX Ultra Low Profile mechanical</li><li><strong>Weight:</strong> 4.20 kg</li></ul>'],
            ['sku'=>'TH-GL-008','name'=>'Acer Predator Helios Neo 16 (i7-13700HX, RTX 4060)','brand'=>'ASUS','category'=>'gaming-laptops','price'=>1299.00,'special_price'=>null,'weight'=>2.60,'stock'=>28,'new'=>0,'featured'=>0,'short_description'=>'Best-value gaming laptop with Intel Core i7, RTX 4060 and 165Hz WQXGA IPS display.','description'=>'<p>Predator Helios Neo 16 offers excellent gaming performance for the money. The RTX 4060 drives high-refresh 1440p gaming, while Predator Sense software manages performance modes and fan curves. Great entry point into enthusiast gaming.</p><ul><li><strong>Processor:</strong> Intel Core i7-13700HX (16-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4060 8GB</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 16" WQXGA (2560×1600), 165Hz, IPS</li><li><strong>Weight:</strong> 2.60 kg</li></ul>'],
            ['sku'=>'TH-GL-009','name'=>'MSI Vector GP68HX (i9-13980HX, RTX 4070 Ti)','brand'=>'MSI','category'=>'gaming-laptops','price'=>2199.00,'special_price'=>null,'weight'=>2.65,'stock'=>11,'new'=>0,'featured'=>0,'short_description'=>'MSI gaming laptop with Intel Core i9, RTX 4070 Ti Super and 240Hz QHD display — for demanding gamers.','description'=>'<p>Vector GP68HX targets enthusiast gamers who want near-flagship GPU power without the flagship price. The RTX 4070 Ti Super delivers excellent 1440p and capable 4K performance in current games.</p><ul><li><strong>Processor:</strong> Intel Core i9-13980HX (24-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4070 Ti Super 16GB</li><li><strong>Memory:</strong> 32GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 16" QHD (2560×1440), 240Hz</li><li><strong>Weight:</strong> 2.65 kg</li></ul>'],
            ['sku'=>'TH-GL-010','name'=>'ASUS TUF Gaming A15 (Ryzen 9 7940HS, RTX 4060)','brand'=>'ASUS','category'=>'gaming-laptops','price'=>1049.00,'special_price'=>null,'weight'=>2.29,'stock'=>36,'new'=>0,'featured'=>0,'short_description'=>'Durable, MIL-SPEC certified gaming laptop with AMD Ryzen 9 and RTX 4060 at an accessible price point.','description'=>'<p>TUF Gaming A15 is built to last, with MIL-STD-810H certification covering temperature, shock, vibration, altitude and humidity. It\'s the smart choice for students and budget-conscious gamers who don\'t want to sacrifice GPU performance.</p><ul><li><strong>Processor:</strong> AMD Ryzen 9 7940HS (8-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4060 8GB</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 15.6" FHD (1920×1080), 144Hz, IPS</li><li><strong>Durability:</strong> MIL-STD-810H</li><li><strong>Weight:</strong> 2.29 kg</li></ul>'],
            ['sku'=>'TH-GL-011','name'=>'Razer Blade 14 (Ryzen 9 7940HX, RTX 4070)','brand'=>'Razer','category'=>'gaming-laptops','price'=>2499.00,'special_price'=>null,'weight'=>1.78,'stock'=>14,'new'=>0,'featured'=>0,'short_description'=>'The most powerful 14" gaming laptop — AMD Ryzen 9, RTX 4070 and 165Hz QHD display in a 1.78 kg chassis.','description'=>'<p>Razer Blade 14 is the ultimate compact gaming laptop for travellers and esports competitors. The AMD-powered platform delivers exceptional gaming performance while the premium anodised aluminium build remains remarkably thin.</p><ul><li><strong>Processor:</strong> AMD Ryzen 9 7940HX (8-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4070 8GB</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 14" QHD (2560×1440), 165Hz</li><li><strong>Chassis:</strong> CNC-machined aluminium, 14mm thin</li><li><strong>Weight:</strong> 1.78 kg</li></ul>'],
            ['sku'=>'TH-GL-012','name'=>'Lenovo IdeaPad Gaming 3 (Ryzen 5 7535HS, RTX 3050)','brand'=>'Lenovo','category'=>'gaming-laptops','price'=>699.00,'special_price'=>null,'weight'=>2.20,'stock'=>42,'new'=>0,'featured'=>0,'short_description'=>'Entry gaming laptop with AMD Ryzen 5, RTX 3050 and 144Hz FHD display — ideal first gaming laptop.','description'=>'<p>IdeaPad Gaming 3 is the perfect entry point into PC gaming. RTX 3050 handles popular titles like Fortnite, Minecraft, and Valorant at 1080p with ease, while the 144Hz display makes gaming feel noticeably smoother than 60Hz alternatives.</p><ul><li><strong>Processor:</strong> AMD Ryzen 5 7535HS (6-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 3050 6GB</li><li><strong>Memory:</strong> 8GB DDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 15.6" FHD (1920×1080), 144Hz, IPS</li><li><strong>Weight:</strong> 2.20 kg</li></ul>'],
            ['sku'=>'TH-GL-013','name'=>'ASUS ROG Flow X16 (Ryzen 9 7940HX, RTX 4070)','brand'=>'ASUS','category'=>'gaming-laptops','price'=>1999.00,'special_price'=>null,'weight'=>2.00,'stock'=>16,'new'=>1,'featured'=>0,'short_description'=>'2-in-1 gaming laptop with 360° hinge, mini LED QHD+ 240Hz display and eGPU expansion slot.','description'=>'<p>ROG Flow X16 is the first gaming 2-in-1 with a 360° hinge and mini LED display. Use it as a laptop for gaming, flip it to tent mode for shared viewing, or connect the ROG XG eGPU for desktop-class performance.</p><ul><li><strong>Processor:</strong> AMD Ryzen 9 7940HX (8-core)</li><li><strong>GPU:</strong> NVIDIA GeForce RTX 4070 8GB</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 1TB NVMe SSD</li><li><strong>Display:</strong> 16" QHD+ mini LED (2560×1600), 240Hz, 1100 nits</li><li><strong>Form factor:</strong> 360° 2-in-1 with active stylus</li><li><strong>Weight:</strong> 2.00 kg</li></ul>'],
        ];
    }

    private static function businessLaptops(): array
    {
        return [
            ['sku'=>'TH-BL-001','name'=>'Dell Latitude 7440 (i7-1365U)','brand'=>'Dell','category'=>'business-laptops','price'=>1499.00,'special_price'=>null,'weight'=>1.28,'stock'=>22,'new'=>0,'featured'=>0,'short_description'=>'Dell\'s premier business ultrabook with Intel vPro, 13th-gen Core i7 and comprehensive security stack.','description'=>'<p>Latitude 7440 is engineered for enterprise IT departments — vPro-certified for remote management, MIL-SPEC tested for durability, and loaded with Dell SafeGuard security features. Thin, light, and reliable for road warriors.</p><ul><li><strong>Processor:</strong> Intel Core i7-1365U (10-core) with vPro</li><li><strong>Memory:</strong> 16GB LPDDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" FHD+ (1920×1200), 60Hz, 400 nits</li><li><strong>Security:</strong> Dell SafeGuard, IR camera, fingerprint, TPM 2.0, optional 4G LTE</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 2× USB-A, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.28 kg</li></ul>'],
            ['sku'=>'TH-BL-002','name'=>'Lenovo ThinkPad T14s Gen 4 AMD (Ryzen 7 PRO 7840U)','brand'=>'Lenovo','category'=>'business-laptops','price'=>1299.00,'special_price'=>null,'weight'=>1.25,'stock'=>19,'new'=>0,'featured'=>0,'short_description'=>'ThinkPad business laptop with AMD Ryzen 7 PRO, enterprise security and legendary keyboard quality.','description'=>'<p>ThinkPad T14s Gen 4 AMD is the choice of corporate IT for good reason — AMD PRO platform for enterprise manageability, ThinkShield security, and the industry-favourite ThinkPad keyboard for hours of comfortable typing.</p><ul><li><strong>Processor:</strong> AMD Ryzen 7 PRO 7840U (8-core)</li><li><strong>Memory:</strong> 16GB LPDDR5x</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" IPS 2.8K (2880×1800), 90Hz, 400 nits</li><li><strong>Security:</strong> ThinkShield, IR camera, fingerprint, TPM 2.0</li><li><strong>Ports:</strong> 2× USB4, 2× USB-A, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.25 kg</li></ul>'],
            ['sku'=>'TH-BL-003','name'=>'HP EliteBook 840 G10 (i7-1365U)','brand'=>'HP','category'=>'business-laptops','price'=>1449.00,'special_price'=>null,'weight'=>1.35,'stock'=>16,'new'=>0,'featured'=>0,'short_description'=>'HP elite business laptop with HP Wolf Security, 13th-gen Intel Core i7 and Sure View privacy screen option.','description'=>'<p>EliteBook 840 G10 is HP\'s security-forward business laptop. HP Wolf Security runs below the OS to protect against firmware attacks, while optional Sure View Reflect privacy screen prevents shoulder surfing in open offices and airports.</p><ul><li><strong>Processor:</strong> Intel Core i7-1365U (10-core) with vPro</li><li><strong>Memory:</strong> 16GB DDR5</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" IPS FHD+ (1920×1200), 60Hz, 400 nits</li><li><strong>Security:</strong> HP Wolf Security, IR camera, fingerprint, TPM 2.0</li><li><strong>Ports:</strong> 2× Thunderbolt 4, 2× USB-A, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.35 kg</li></ul>'],
            ['sku'=>'TH-BL-004','name'=>'Microsoft Surface Laptop 5 15" (i7-1265U)','brand'=>'Dell','category'=>'business-laptops','price'=>1699.00,'special_price'=>null,'weight'=>1.56,'stock'=>13,'new'=>0,'featured'=>0,'short_description'=>'Microsoft\'s premium 15" business laptop with PixelSense display, Alcantara keyboard and Windows 11.','description'=>'<p>Surface Laptop 5 15" brings Microsoft\'s signature premium build quality to a larger canvas. The PixelSense display with Dolby Vision supports pen input, and the Alcantara fabric keyboard is uniquely comfortable for all-day typing.</p><ul><li><strong>Processor:</strong> Intel Core i7-1265U (10-core)</li><li><strong>Memory:</strong> 16GB LPDDR5x</li><li><strong>Storage:</strong> 512GB SSD</li><li><strong>Display:</strong> 15" PixelSense (2496×1664), 60Hz, touch, Dolby Vision</li><li><strong>Ports:</strong> 1× Thunderbolt 4, 1× USB-A, Surface Connect, 3.5mm</li><li><strong>Weight:</strong> 1.56 kg</li></ul>'],
            ['sku'=>'TH-BL-005','name'=>'Dell Latitude 5540 (i5-1345U)','brand'=>'Dell','category'=>'business-laptops','price'=>1049.00,'special_price'=>null,'weight'=>1.58,'stock'=>25,'new'=>0,'featured'=>0,'short_description'=>'Mid-range business laptop with Intel Core i5, vPro Essentials and comprehensive port selection.','description'=>'<p>Latitude 5540 provides everything most business users need — reliable Intel Core i5 performance, enterprise security features, and the full port selection professionals depend on — at a sensible price point.</p><ul><li><strong>Processor:</strong> Intel Core i5-1345U (10-core)</li><li><strong>Memory:</strong> 16GB DDR4</li><li><strong>Storage:</strong> 256GB NVMe SSD</li><li><strong>Display:</strong> 15.6" FHD (1920×1080), 60Hz, 250 nits</li><li><strong>Ports:</strong> 1× Thunderbolt 4, 2× USB-A, USB-C, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.58 kg</li></ul>'],
            ['sku'=>'TH-BL-006','name'=>'Lenovo ThinkPad E14 Gen 5 (Ryzen 5 7530U)','brand'=>'Lenovo','category'=>'business-laptops','price'=>849.00,'special_price'=>null,'weight'=>1.56,'stock'=>31,'new'=>0,'featured'=>0,'short_description'=>'Affordable ThinkPad with AMD Ryzen 5, backlit keyboard and spill-resistant design for everyday business use.','description'=>'<p>ThinkPad E14 Gen 5 brings ThinkPad quality to a budget-conscious price. AMD Ryzen 5 handles business applications comfortably, and the spill-resistant keyboard with backlight provides practical durability for office environments.</p><ul><li><strong>Processor:</strong> AMD Ryzen 5 7530U (6-core)</li><li><strong>Memory:</strong> 8GB DDR4</li><li><strong>Storage:</strong> 256GB NVMe SSD</li><li><strong>Display:</strong> 14" IPS FHD (1920×1080), 60Hz, 300 nits</li><li><strong>Ports:</strong> 1× USB-C 3.2, 2× USB-A, HDMI, 3.5mm</li><li><strong>Weight:</strong> 1.56 kg</li></ul>'],
        ];
    }

    private static function budgetLaptops(): array
    {
        return [
            ['sku'=>'TH-BU-001','name'=>'Lenovo IdeaPad Slim 5 (i5-12450H)','brand'=>'Lenovo','category'=>'budget-laptops','price'=>699.00,'special_price'=>null,'weight'=>1.46,'stock'=>48,'new'=>0,'featured'=>0,'short_description'=>'Slim everyday laptop with Intel Core i5, OLED option and 15-hour battery life at a great price.','description'=>'<p>IdeaPad Slim 5 punches well above its price with optional OLED display and capable Intel Core i5 performance. Lightweight enough for commuters and students, powerful enough for everyday computing tasks.</p><ul><li><strong>Processor:</strong> Intel Core i5-12450H (8-core)</li><li><strong>Memory:</strong> 8GB DDR4</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 14" IPS FHD (1920×1080), 60Hz, 300 nits</li><li><strong>Battery:</strong> Up to 15 hours</li><li><strong>Ports:</strong> 1× USB-C 3.2, 2× USB-A, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.46 kg</li></ul>'],
            ['sku'=>'TH-BU-002','name'=>'ASUS VivoBook 15 (Ryzen 7 7730U)','brand'=>'ASUS','category'=>'budget-laptops','price'=>649.00,'special_price'=>null,'weight'=>1.65,'stock'=>39,'new'=>0,'featured'=>0,'short_description'=>'Capable everyday laptop with AMD Ryzen 7, OLED display and numeric keypad at an affordable price.','description'=>'<p>VivoBook 15 proves you don\'t need a premium budget for a great laptop experience. AMD Ryzen 7 handles multitasking smoothly, and the OLED display option offers colour quality typically found in laptops costing twice as much.</p><ul><li><strong>Processor:</strong> AMD Ryzen 7 7730U (8-core)</li><li><strong>Memory:</strong> 8GB DDR4</li><li><strong>Storage:</strong> 512GB NVMe SSD</li><li><strong>Display:</strong> 15.6" OLED FHD (1920×1080), 60Hz, 600 nits</li><li><strong>Battery:</strong> Up to 8 hours</li><li><strong>Ports:</strong> 1× USB-C, 2× USB-A, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.65 kg</li></ul>'],
            ['sku'=>'TH-BU-003','name'=>'HP Pavilion 15 (i5-1335U)','brand'=>'HP','category'=>'budget-laptops','price'=>599.00,'special_price'=>549.00,'weight'=>1.75,'stock'=>54,'new'=>0,'featured'=>0,'short_description'=>'HP Pavilion 15 with 13th-gen Intel Core i5 delivers reliable everyday performance at an entry-level price.','description'=>'<p>HP Pavilion 15 is a solid choice for students, home users and light office workers. Intel Core i5 handles web browsing, Office apps and video streaming without breaking a sweat, and the full HD display produces sharp visuals for content consumption.</p><ul><li><strong>Processor:</strong> Intel Core i5-1335U (10-core)</li><li><strong>Memory:</strong> 8GB DDR4</li><li><strong>Storage:</strong> 256GB NVMe SSD</li><li><strong>Display:</strong> 15.6" FHD IPS (1920×1080), 60Hz, 250 nits</li><li><strong>Battery:</strong> Up to 8 hours</li><li><strong>Ports:</strong> 1× USB-C, 2× USB-A, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.75 kg</li></ul>'],
            ['sku'=>'TH-BU-004','name'=>'Acer Aspire 5 (Ryzen 5 7530U)','brand'=>'ASUS','category'=>'budget-laptops','price'=>479.00,'special_price'=>null,'weight'=>1.80,'stock'=>61,'new'=>0,'featured'=>0,'short_description'=>'Budget-friendly Acer Aspire 5 with AMD Ryzen 5, aluminium lid and 1080p IPS display.','description'=>'<p>Aspire 5 remains one of the best laptops under $500. The AMD Ryzen 5 processor delivers genuine multitasking performance, the IPS display is sharp and comfortable for extended use, and the aluminium lid feels more premium than the price suggests.</p><ul><li><strong>Processor:</strong> AMD Ryzen 5 7530U (6-core)</li><li><strong>Memory:</strong> 8GB DDR4</li><li><strong>Storage:</strong> 256GB NVMe SSD</li><li><strong>Display:</strong> 15.6" IPS FHD (1920×1080), 60Hz, 300 nits</li><li><strong>Battery:</strong> Up to 9 hours</li><li><strong>Ports:</strong> 1× USB-C, 2× USB-A, HDMI, SD, 3.5mm</li><li><strong>Weight:</strong> 1.80 kg</li></ul>'],
        ];
    }
}
