<?php

namespace Database\Seeders\ProductData;

class MemoryData
{
    public static function get(): array
    {
        return array_merge(
            self::desktopRam(),
            self::laptopRam(),
        );
    }

    private static function desktopRam(): array
    {
        return [
            ['sku'=>'TH-DR-001','name'=>'Corsair Vengeance DDR5-6000 32GB (2×16GB)','brand'=>'Corsair','category'=>'desktop-ram','price'=>99.00,'special_price'=>89.00,'weight'=>0.12,'stock'=>78,'new'=>1,'featured'=>1,'short_description'=>'Corsair Vengeance DDR5 32GB dual-channel kit running at 6000 MT/s — the sweet spot for Intel 13th/14th Gen.','description'=>'<p>Vengeance DDR5-6000 CL30 is specifically tuned for Intel 13th/14th Gen platforms (Z790/Z690) and AMD Ryzen 7000 (X670E). DDR5-6000 with CL30 latency represents the optimal frequency/latency trade-off for gaming and productivity, offering measurably better performance than stock DDR5-4800.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR5-6000 (6000 MT/s)</li><li><strong>Latency:</strong> CL30-36-36-76</li><li><strong>Voltage:</strong> 1.35V</li><li><strong>XMP 3.0 / EXPO:</strong> Yes</li><li><strong>Heatspreader:</strong> Black aluminium</li><li><strong>Form Factor:</strong> DIMM (288-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-DR-002','name'=>'Kingston Fury Beast DDR5-5600 64GB (2×32GB)','brand'=>'Kingston','category'=>'desktop-ram','price'=>149.00,'special_price'=>null,'weight'=>0.13,'stock'=>42,'new'=>1,'featured'=>0,'short_description'=>'Kingston Fury Beast DDR5 64GB dual-channel kit — maximum capacity for workstations and content creation.','description'=>'<p>Fury Beast DDR5-5600 64GB provides the memory headroom needed for virtual machines, 3D rendering, video editing, and AI/ML workloads. The low-profile heatspreader fits in systems with large CPU coolers, and Intel XMP 3.0 / AMD EXPO ensures plug-and-play overclocking.</p><ul><li><strong>Capacity:</strong> 64GB (2× 32GB)</li><li><strong>Speed:</strong> DDR5-5600 (5600 MT/s)</li><li><strong>Latency:</strong> CL40-40-40-80</li><li><strong>Voltage:</strong> 1.25V</li><li><strong>XMP 3.0 / EXPO:</strong> Yes</li><li><strong>Form Factor:</strong> DIMM (288-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-DR-003','name'=>'G.Skill Trident Z5 RGB DDR5-6400 32GB (2×16GB)','brand'=>'Corsair','category'=>'desktop-ram','price'=>139.00,'special_price'=>null,'weight'=>0.14,'stock'=>29,'new'=>1,'featured'=>0,'short_description'=>'G.Skill Trident Z5 RGB DDR5-6400 — high-frequency kit with addressable RGB for enthusiast builds.','description'=>'<p>Trident Z5 RGB DDR5-6400 is engineered for enthusiasts who want maximum DDR5 performance. The dual-channel kit features individually addressable RGB LEDs controllable via Asus Aura Sync, MSI Mystic Light, ASRock Polychrome, or Gigabyte RGB Fusion 2.0.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR5-6400 (6400 MT/s)</li><li><strong>Latency:</strong> CL32-39-39-102</li><li><strong>Voltage:</strong> 1.4V</li><li><strong>XMP 3.0:</strong> Yes</li><li><strong>RGB:</strong> Individually addressable, dual-zone</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-DR-004','name'=>'Crucial Pro DDR4-3200 32GB (2×16GB)','brand'=>'Crucial','category'=>'desktop-ram','price'=>59.00,'special_price'=>null,'weight'=>0.10,'stock'=>96,'new'=>0,'featured'=>0,'short_description'=>'Crucial Pro DDR4-3200 32GB dual-channel — reliable, no-frills RAM for DDR4 motherboards.','description'=>'<p>Crucial Pro DDR4-3200 provides straightforward, reliable memory for any DDR4 system. Micron DRAM chips ensure consistency across production batches. XMP 2.0 support for one-click 3200 MHz activation — no manual tuning required.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR4-3200 (3200 MT/s)</li><li><strong>Latency:</strong> CL22-22-22-52</li><li><strong>Voltage:</strong> 1.35V</li><li><strong>XMP 2.0:</strong> Yes</li><li><strong>Form Factor:</strong> DIMM (288-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-DR-005','name'=>'Corsair Vengeance RGB Pro DDR4-3600 32GB (2×16GB)','brand'=>'Corsair','category'=>'desktop-ram','price'=>89.00,'special_price'=>79.00,'weight'=>0.14,'stock'=>53,'new'=>0,'featured'=>0,'short_description'=>'Corsair Vengeance RGB Pro DDR4-3600 32GB — premium DDR4 kit with dynamic RGB for gaming builds.','description'=>'<p>Vengeance RGB Pro DDR4-3600 has been a fan favourite for AMD Ryzen builds for years. The 10-zone dynamic RGB illumination, aluminium heatspreader, and tight XMP profile make it a top pick for enthusiasts building DDR4 systems.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR4-3600 (3600 MT/s)</li><li><strong>Latency:</strong> CL18-22-22-42</li><li><strong>Voltage:</strong> 1.35V</li><li><strong>XMP 2.0:</strong> Yes</li><li><strong>RGB:</strong> 10-zone dynamic per module</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-DR-006','name'=>'Kingston Fury Beast DDR4-3200 16GB (2×8GB)','brand'=>'Kingston','category'=>'desktop-ram','price'=>39.00,'special_price'=>null,'weight'=>0.08,'stock'=>114,'new'=>0,'featured'=>0,'short_description'=>'Kingston Fury Beast DDR4-3200 16GB — budget-friendly entry-level kit for everyday desktop builds.','description'=>'<p>Fury Beast DDR4-3200 is the most affordable DDR4 dual-channel kit in the TechHeaven lineup. Intel XMP support enables 3200 MT/s with a single BIOS toggle. Low-profile heatspreader fits under large air coolers without clearance issues.</p><ul><li><strong>Capacity:</strong> 16GB (2× 8GB)</li><li><strong>Speed:</strong> DDR4-3200 (3200 MT/s)</li><li><strong>Latency:</strong> CL16-18-18-36</li><li><strong>Voltage:</strong> 1.35V</li><li><strong>XMP 2.0:</strong> Yes</li><li><strong>Form Factor:</strong> DIMM (288-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-DR-007','name'=>'Corsair Dominator Titanium DDR5-7200 32GB (2×16GB)','brand'=>'Corsair','category'=>'desktop-ram','price'=>249.00,'special_price'=>null,'weight'=>0.18,'stock'=>14,'new'=>1,'featured'=>0,'short_description'=>'Corsair Dominator Titanium DDR5-7200 — extreme-overclocking DDR5 kit with brushed aluminium and PMIC.','description'=>'<p>Dominator Titanium DDR5-7200 represents the pinnacle of consumer DDR5. The CORSAIR PMIC (Power Management IC) on each module ensures stable voltage delivery at extreme frequencies, while iCUE addressable RGB illumination and brushed aluminium construction make it a visual centrepiece.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR5-7200 (7200 MT/s)</li><li><strong>Latency:</strong> CL34-42-42-96</li><li><strong>Voltage:</strong> 1.45V</li><li><strong>XMP 3.0:</strong> Yes</li><li><strong>RGB:</strong> iCUE individually addressable</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-DR-008','name'=>'Crucial 48GB DDR5-5600 (2×24GB) Mac Compatible','brand'=>'Crucial','category'=>'desktop-ram','price'=>119.00,'special_price'=>null,'weight'=>0.12,'stock'=>26,'new'=>1,'featured'=>0,'short_description'=>'Crucial 48GB DDR5 kit — specific capacity for Mac Pro and Mac Studio maximum memory configurations.','description'=>'<p>This 48GB (2× 24GB) DDR5-5600 kit is purpose-designed for Mac Pro (2023) and Mac Studio (M2 Ultra) users who require the maximum amount of user-installable memory. Crucially, 24GB DIMMs are not interchangeable with standard 16GB or 32GB modules at this capacity.</p><ul><li><strong>Capacity:</strong> 48GB (2× 24GB)</li><li><strong>Speed:</strong> DDR5-5600 (5600 MT/s)</li><li><strong>Latency:</strong> CL46</li><li><strong>Voltage:</strong> 1.1V</li><li><strong>Compatibility:</strong> Mac Pro (2023), Mac Studio (M2 Ultra)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
        ];
    }

    private static function laptopRam(): array
    {
        return [
            ['sku'=>'TH-LR-001','name'=>'Crucial 32GB DDR4-3200 SO-DIMM (2×16GB)','brand'=>'Crucial','category'=>'laptop-ram','price'=>59.00,'special_price'=>null,'weight'=>0.04,'stock'=>87,'new'=>0,'featured'=>1,'short_description'=>'Crucial 32GB DDR4-3200 SO-DIMM kit — the most popular laptop RAM upgrade for DDR4-era notebooks.','description'=>'<p>Crucial 32GB DDR4-3200 SO-DIMM kit is the definitive laptop memory upgrade for machines with DDR4 SODIMM slots. Micron-manufactured chips ensure consistent, reliable performance. Fully compatible with Intel and AMD laptops from 2019–2022 with user-upgradable RAM.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR4-3200 (3200 MT/s)</li><li><strong>Latency:</strong> CL22</li><li><strong>Voltage:</strong> 1.2V</li><li><strong>Form Factor:</strong> SO-DIMM (260-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-LR-002','name'=>'Kingston Fury Impact DDR5-4800 32GB SO-DIMM (2×16GB)','brand'=>'Kingston','category'=>'laptop-ram','price'=>79.00,'special_price'=>null,'weight'=>0.04,'stock'=>52,'new'=>1,'featured'=>0,'short_description'=>'Kingston Fury Impact DDR5-4800 32GB SO-DIMM — DDR5 upgrade for Intel 12th/13th Gen and AMD Ryzen 7000 laptops.','description'=>'<p>Fury Impact DDR5-4800 is engineered for laptops with DDR5 SO-DIMM slots, including Intel 12th/13th Gen (Alder Lake/Raptor Lake) and AMD Ryzen 7000 series notebooks. Plug-and-play DDR5 upgrade for compatible machines with user-accessible memory slots.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR5-4800 (4800 MT/s)</li><li><strong>Latency:</strong> CL38</li><li><strong>Voltage:</strong> 1.1V</li><li><strong>Form Factor:</strong> SO-DIMM (262-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-LR-003','name'=>'Corsair Vengeance DDR5-5600 32GB SO-DIMM (2×16GB)','brand'=>'Corsair','category'=>'laptop-ram','price'=>89.00,'special_price'=>79.00,'weight'=>0.05,'stock'=>38,'new'=>1,'featured'=>0,'short_description'=>'Corsair Vengeance DDR5-5600 SO-DIMM — high-frequency laptop DDR5 for maximum performance upgrades.','description'=>'<p>Vengeance DDR5-5600 SO-DIMM offers faster-than-stock DDR5 speeds for laptops that support XMP or EXPO memory profiles. For compatible platforms, the step from JEDEC DDR5-4800 to XMP DDR5-5600 delivers noticeably better memory-bandwidth-sensitive workload performance.</p><ul><li><strong>Capacity:</strong> 32GB (2× 16GB)</li><li><strong>Speed:</strong> DDR5-5600 (5600 MT/s)</li><li><strong>Latency:</strong> CL36</li><li><strong>Voltage:</strong> 1.1V</li><li><strong>Form Factor:</strong> SO-DIMM (262-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-LR-004','name'=>'Crucial 16GB DDR4-3200 SO-DIMM Single','brand'=>'Crucial','category'=>'laptop-ram','price'=>29.00,'special_price'=>null,'weight'=>0.02,'stock'=>134,'new'=>0,'featured'=>0,'short_description'=>'Crucial 16GB DDR4-3200 single SO-DIMM module — add a second stick for 24GB or 32GB total.','description'=>'<p>Single 16GB DDR4-3200 SO-DIMM for pairing with an existing 8GB module to reach 24GB, or with another 16GB to hit 32GB in dual-channel. Fully compatible with any DDR4 laptop using SO-DIMM slots at DDR4-2133, 2400, 2666, or 3200 speeds.</p><ul><li><strong>Capacity:</strong> 16GB</li><li><strong>Speed:</strong> DDR4-3200 (3200 MT/s)</li><li><strong>Latency:</strong> CL22</li><li><strong>Voltage:</strong> 1.2V</li><li><strong>Form Factor:</strong> SO-DIMM (260-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-LR-005','name'=>'Kingston 64GB DDR5-4800 SO-DIMM (2×32GB)','brand'=>'Kingston','category'=>'laptop-ram','price'=>139.00,'special_price'=>null,'weight'=>0.06,'stock'=>19,'new'=>1,'featured'=>0,'short_description'=>'Kingston 64GB DDR5 SO-DIMM kit — maximum capacity upgrade for DDR5 mobile workstations.','description'=>'<p>64GB DDR5 SO-DIMM dual-channel kit for mobile workstations, mini-PCs and laptops with two DDR5 SO-DIMM slots. Ideal for running virtual machines, large Docker environments, or heavy multitasking on portable platforms.</p><ul><li><strong>Capacity:</strong> 64GB (2× 32GB)</li><li><strong>Speed:</strong> DDR5-4800 (4800 MT/s)</li><li><strong>Latency:</strong> CL40</li><li><strong>Voltage:</strong> 1.1V</li><li><strong>Form Factor:</strong> SO-DIMM (262-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-LR-006','name'=>'Crucial 8GB DDR4-2666 SO-DIMM Single','brand'=>'Crucial','category'=>'laptop-ram','price'=>17.00,'special_price'=>null,'weight'=>0.02,'stock'=>178,'new'=>0,'featured'=>0,'short_description'=>'Entry-level Crucial 8GB DDR4-2666 SO-DIMM — budget upgrade for older DDR4 laptops.','description'=>'<p>Single 8GB DDR4-2666 module for older laptops with a single populated slot. Upgrading from 4GB to 8GB is one of the most noticeable computing improvements possible — Chrome tabs stop crashing, multitasking becomes viable, and the system stops leaning on virtual memory.</p><ul><li><strong>Capacity:</strong> 8GB</li><li><strong>Speed:</strong> DDR4-2666 (2666 MT/s)</li><li><strong>Latency:</strong> CL19</li><li><strong>Voltage:</strong> 1.2V</li><li><strong>Form Factor:</strong> SO-DIMM (260-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-LR-007','name'=>'Corsair 32GB DDR4-3200 SO-DIMM Single','brand'=>'Corsair','category'=>'laptop-ram','price'=>49.00,'special_price'=>null,'weight'=>0.03,'stock'=>44,'new'=>0,'featured'=>0,'short_description'=>'Corsair 32GB DDR4-3200 single SO-DIMM — maximize single-slot laptops to 32GB.','description'=>'<p>32GB DDR4 single-module SO-DIMM for laptops with only one physical slot. Upgrading to a 32GB single-rank or dual-rank module provides the maximum capacity these single-slot machines can accept, ensuring future-proofing without requiring a new system purchase.</p><ul><li><strong>Capacity:</strong> 32GB</li><li><strong>Speed:</strong> DDR4-3200 (3200 MT/s)</li><li><strong>Latency:</strong> CL22</li><li><strong>Voltage:</strong> 1.2V</li><li><strong>Form Factor:</strong> SO-DIMM (260-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-LR-008','name'=>'Kingston 16GB DDR5-5600 SO-DIMM Single','brand'=>'Kingston','category'=>'laptop-ram','price'=>39.00,'special_price'=>null,'weight'=>0.02,'stock'=>68,'new'=>1,'featured'=>0,'short_description'=>'Kingston 16GB DDR5-5600 single SO-DIMM — high-speed upgrade for DDR5 laptops with one free slot.','description'=>'<p>16GB DDR5-5600 single SO-DIMM to pair with an existing 8GB or 16GB module for 24GB or 32GB dual-channel DDR5 configurations. Ideal for users who want to upgrade a single slot on recently purchased DDR5 laptops.</p><ul><li><strong>Capacity:</strong> 16GB</li><li><strong>Speed:</strong> DDR5-5600 (5600 MT/s)</li><li><strong>Latency:</strong> CL40</li><li><strong>Voltage:</strong> 1.1V</li><li><strong>Form Factor:</strong> SO-DIMM (262-pin)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
        ];
    }
}
