<?php

namespace Database\Seeders\ProductData;

class MobileData
{
    public static function get(): array
    {
        return array_merge(
            self::phoneCases(),
            self::chargersCables(),
            self::screenProtectors(),
        );
    }

    private static function phoneCases(): array
    {
        return [
            ['sku'=>'TH-PC-001','name'=>'Apple MagSafe Clear Case for iPhone 15 Pro','brand'=>'Apple','category'=>'phone-cases','price'=>59.00,'special_price'=>null,'weight'=>0.02,'stock'=>87,'new'=>1,'featured'=>1,'short_description'=>'Apple MagSafe Clear Case for iPhone 15 Pro — anti-yellowing optical clarity and MagSafe charging passthrough.','description'=>'<p>Apple\'s official MagSafe Clear Case uses a two-piece design with a soft microfibre interior that protects the iPhone\'s camera ring from scratches. The optically clear polycarbonate stays clear over time — Apple\'s anti-yellowing treatment significantly outperforms generic alternatives. MagSafe ecosystem accessories snap and charge at full 15W.</p><ul><li><strong>Compatibility:</strong> iPhone 15 Pro</li><li><strong>Material:</strong> Optically clear polycarbonate + soft microfibre lining</li><li><strong>MagSafe:</strong> Full 15W MagSafe passthrough</li><li><strong>Drop Protection:</strong> 1 metre (MIL-STD-810G)</li><li><strong>Anti-yellowing:</strong> Yes</li></ul>'],
            ['sku'=>'TH-PC-002','name'=>'Apple Silicone Case with MagSafe iPhone 15','brand'=>'Apple','category'=>'phone-cases','price'=>49.00,'special_price'=>null,'weight'=>0.03,'stock'=>76,'new'=>1,'featured'=>0,'short_description'=>'Apple Silicone MagSafe Case iPhone 15 — soft-touch silicone with colour-matched microfibre lining and MagSafe.','description'=>'<p>Apple Silicone Case provides a tactile, grippy surface that stays comfortable in hand without added bulk. The colour-matched microfibre lining prevents the back of the iPhone from scratching. Available in a wide range of colours coordinated with Apple\'s accessory lineup.</p><ul><li><strong>Compatibility:</strong> iPhone 15</li><li><strong>Material:</strong> Silicone exterior, microfibre lining</li><li><strong>MagSafe:</strong> Full 15W MagSafe</li><li><strong>Drop Protection:</strong> 1 metre</li><li><strong>Colours:</strong> 10 colour options</li></ul>'],
            ['sku'=>'TH-PC-003','name'=>'Belkin SheerForce Pro Kevlar Case Samsung S24 Ultra','brand'=>'Belkin','category'=>'phone-cases','price'=>44.00,'special_price'=>null,'weight'=>0.04,'stock'=>52,'new'=>1,'featured'=>0,'short_description'=>'Belkin KeVlar Sheerforce Pro for Galaxy S24 Ultra — military-grade protection without bulk, Qi2 compatible.','description'=>'<p>Belkin\'s SheerForce Pro uses DuPont Kevlar fibre reinforcement in the case body — the same material in bulletproof vests — to provide exceptional strength with minimal added thickness. Air Cushion Corner Technology absorbs drop impacts. Compatible with Samsung Wireless Charging Pad and third-party Qi2 chargers.</p><ul><li><strong>Compatibility:</strong> Samsung Galaxy S24 Ultra</li><li><strong>Material:</strong> Kevlar fibre + polycarbonate</li><li><strong>Drop Protection:</strong> MIL-STD-810G (4 metres)</li><li><strong>Wireless Charging:</strong> Qi2 / Samsung Wireless</li></ul>'],
            ['sku'=>'TH-PC-004','name'=>'Anker 360 Case for iPhone 15 Pro Max','brand'=>'Anker','category'=>'phone-cases','price'=>35.00,'special_price'=>null,'weight'=>0.03,'stock'=>64,'new'=>1,'featured'=>0,'short_description'=>'Anker 360 Magnetic Case iPhone 15 Pro Max — MagSafe compatible, 360° protection with raised camera bezel.','description'=>'<p>Anker 360 provides MagSafe ecosystem compatibility at a more accessible price than the Apple branded case. The raised camera bezel prevents lenses from touching surfaces when the phone is placed face-up. The 5000D aramid fibre pattern on the back provides grip without a sticky silicone texture.</p><ul><li><strong>Compatibility:</strong> iPhone 15 Pro Max</li><li><strong>MagSafe:</strong> MagSafe magnet array</li><li><strong>Material:</strong> Polycarbonate + TPU bumper</li><li><strong>Drop Protection:</strong> 4 metres</li><li><strong>Camera:</strong> Raised 0.5mm bezel protection</li></ul>'],
            ['sku'=>'TH-PC-005','name'=>'Belkin Boost Charge Pro Case with MagSafe Stand iPhone 15','brand'=>'Belkin','category'=>'phone-cases','price'=>69.00,'special_price'=>null,'weight'=>0.06,'stock'=>39,'new'=>0,'featured'=>0,'short_description'=>'Belkin 2-in-1 MagSafe case — built-in kickstand that doubles as a phone ring for secure grip.','description'=>'<p>Boost Charge Pro converts the phone ring grip into a functional kickstand — extend it to watch video in landscape mode, or use it as a secure finger loop while photographing. Full MagSafe pass-through ensures you don\'t need to remove the case for 15W wireless charging.</p><ul><li><strong>Compatibility:</strong> iPhone 15</li><li><strong>Features:</strong> Built-in kickstand ring</li><li><strong>MagSafe:</strong> Full 15W passthrough</li><li><strong>Material:</strong> PC + TPU hybrid</li><li><strong>Drop Protection:</strong> 2 metres</li></ul>'],
        ];
    }

    private static function chargersCables(): array
    {
        return [
            ['sku'=>'TH-CC-001','name'=>'Anker 747 GaN Prime 150W Desktop Charger','brand'=>'Anker','category'=>'chargers-cables','price'=>79.00,'special_price'=>null,'weight'=>0.26,'stock'=>53,'new'=>1,'featured'=>1,'short_description'=>'Anker 747 GaN Prime 150W — charges 4 devices simultaneously with 100W USB-C for MacBook Pro.','description'=>'<p>Anker 747 GaN Prime replaces a laptop charger, phone charger, tablet charger, and earbuds charger with a single compact GaN adapter. The 100W USB-C port 1 delivers enough power for 16" MacBook Pro charging at full speed. Smart power distribution automatically allocates wattage as devices connect and disconnect.</p><ul><li><strong>Total Power:</strong> 150W</li><li><strong>Ports:</strong> 2× USB-C (100W + 22.5W) + 2× USB-A (22.5W total)</li><li><strong>Technology:</strong> GaN Prime</li><li><strong>Smart Distribution:</strong> ActiveShield auto power allocation</li><li><strong>Size:</strong> 84 × 55 × 30mm</li></ul>'],
            ['sku'=>'TH-CC-002','name'=>'Anker 3-in-1 MagSafe Cube Wireless Charger','brand'=>'Anker','category'=>'chargers-cables','price'=>59.00,'special_price'=>null,'weight'=>0.18,'stock'=>68,'new'=>1,'featured'=>1,'short_description'=>'Anker 3-in-1 MagSafe Cube — foldable wireless charger for iPhone (MagSafe 15W), Apple Watch, and AirPods.','description'=>'<p>Anker 3-in-1 MagSafe Cube simultaneously charges iPhone, Apple Watch, and AirPods in a compact foldable form. It folds flat for travel and opens into a watch stand and phone mount. Apple Watch fast charging delivers 0–80% in 45 minutes. MFi certified and made with recycled materials.</p><ul><li><strong>iPhone:</strong> MagSafe 15W</li><li><strong>Apple Watch:</strong> Fast Charging (0–80% in 45 min)</li><li><strong>AirPods:</strong> Qi wireless pad</li><li><strong>Foldable:</strong> Yes (travel-friendly)</li><li><strong>Power Adapter:</strong> Not included (USB-C)</li></ul>'],
            ['sku'=>'TH-CC-003','name'=>'Apple USB-C to MagSafe 3 Cable 2m','brand'=>'Apple','category'=>'chargers-cables','price'=>49.00,'special_price'=>null,'weight'=>0.06,'stock'=>91,'new'=>0,'featured'=>0,'short_description'=>'Apple USB-C to MagSafe 3 cable 2m — for MacBook Air and MacBook Pro fast charging via USB-C PD charger.','description'=>'<p>The USB-C to MagSafe 3 cable allows MacBook Air and MacBook Pro owners to charge from any USB-C Power Delivery charger or power bank, adding flexibility beyond the included MagSafe adapter. The 2m length provides comfortable reach from desk or wall outlets. MagSafe 3 provides 60–140W depending on MacBook model.</p><ul><li><strong>Compatibility:</strong> MacBook Air M2/M3, MacBook Pro 14"/16"</li><li><strong>Length:</strong> 2 metres</li><li><strong>Connector:</strong> USB-C to MagSafe 3</li><li><strong>Max Power:</strong> 140W (MBP 16")</li></ul>'],
            ['sku'=>'TH-CC-004','name'=>'Belkin BoostCharge Pro Flex USB-C Cable 3m','brand'=>'Belkin','category'=>'chargers-cables','price'=>29.00,'special_price'=>null,'weight'=>0.08,'stock'=>104,'new'=>0,'featured'=>0,'short_description'=>'Belkin USB-C to USB-C 100W braided cable 3m — coils without kinking, 100W charging and 10Gbps data.','description'=>'<p>BoostCharge Pro Flex cable uses a proprietary silicone jacket that coils and uncoils repeatedly without memory kinking — it stays flat when extended. The 100W Power Delivery rating supports charging MacBook Pro and compatible laptops at full speed. 10Gbps data transfer for USB 3.2 Gen 2 devices.</p><ul><li><strong>Type:</strong> USB-C to USB-C</li><li><strong>Power:</strong> 100W USB PD (20V/5A)</li><li><strong>Data:</strong> 10 Gbps (USB 3.2 Gen 2)</li><li><strong>Length:</strong> 3 metres</li><li><strong>Material:</strong> Silicone jacket (no kinking)</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-CC-005','name'=>'Anker Nano II 65W GaN USB-C Charger','brand'=>'Anker','category'=>'chargers-cables','price'=>35.00,'special_price'=>null,'weight'=>0.10,'stock'=>79,'new'=>0,'featured'=>0,'short_description'=>'Anker Nano II 65W GaN — smallest 65W laptop charger with foldable pins, replaces most laptop power adapters.','description'=>'<p>Anker Nano II 65W is one of the smallest 65W chargers available, enabled by GaN III technology. It charges most 13-15" laptops via USB-C at full speed and fast-charges iPhones and Android phones in the same port. Foldable US pins make it compact for travel.</p><ul><li><strong>Total Power:</strong> 65W</li><li><strong>Ports:</strong> 1× USB-C (65W)</li><li><strong>Technology:</strong> GaN III</li><li><strong>Plug:</strong> Foldable US pins</li><li><strong>Dimensions:</strong> 40 × 40 × 35mm</li><li><strong>Compatibility:</strong> MacBook Air, Dell XPS 13, iPad Pro</li></ul>'],
            ['sku'=>'TH-CC-006','name'=>'Belkin 15W Qi2 Wireless Charging Pad','brand'=>'Belkin','category'=>'chargers-cables','price'=>39.00,'special_price'=>null,'weight'=>0.10,'stock'=>62,'new'=>1,'featured'=>0,'short_description'=>'Belkin Qi2 15W wireless charging pad — MagSafe-speed charging for iPhone 13/14/15 and Qi2 devices.','description'=>'<p>Qi2 is the new open wireless charging standard co-developed by Apple, achieving the same 15W charging speed as MagSafe for a fraction of the cost of Apple-branded alternatives. Belkin\'s Qi2 pad works with any Qi2 device including iPhone 13, 14, and 15 series, and upcoming Android Qi2 phones.</p><ul><li><strong>Standard:</strong> Qi2 (15W for iPhone 13+)</li><li><strong>Power:</strong> 15W Qi2 / 10W standard Qi</li><li><strong>Connection:</strong> USB-C (12W adapter included)</li><li><strong>Compatibility:</strong> iPhone 13/14/15, Qi2 Android devices</li></ul>'],
        ];
    }

    private static function screenProtectors(): array
    {
        return [
            ['sku'=>'TH-SP-101','name'=>'Belkin UltraGlass Screen Protector iPhone 15 Pro Max','brand'=>'Belkin','category'=>'screen-protectors','price'=>44.00,'special_price'=>null,'weight'=>0.02,'stock'=>88,'new'=>1,'featured'=>1,'short_description'=>'Belkin UltraGlass 2 for iPhone 15 Pro Max — 2× harder than standard tempered glass, optical clarity.','description'=>'<p>UltraGlass 2 uses a proprietary ion exchange process to achieve hardness 2× that of standard tempered glass while maintaining optical clarity. The EasyAlign installation tray ensures perfect alignment on the first attempt. Anti-microbial coating reduces bacteria growth on the screen surface.</p><ul><li><strong>Compatibility:</strong> iPhone 15 Pro Max</li><li><strong>Material:</strong> Tempered glass (ion-exchanged, 2× harder than standard)</li><li><strong>Hardness:</strong> 10H</li><li><strong>Coating:</strong> Anti-microbial, oleophobic</li><li><strong>Installation:</strong> EasyAlign tray included</li><li><strong>Thickness:</strong> 0.3mm</li></ul>'],
            ['sku'=>'TH-SP-102','name'=>'Anker Privacy Screen Protector iPhone 15 Plus','brand'=>'Anker','category'=>'screen-protectors','price'=>29.00,'special_price'=>null,'weight'=>0.02,'stock'=>61,'new'=>1,'featured'=>0,'short_description'=>'Anker Privacy Screen Protector iPhone 15 Plus — 30° privacy angle, anti-glare and 9H hardness.','description'=>'<p>Anker Privacy protector limits screen visibility to a 30° viewing angle — the person directly in front can see clearly, but anyone beside or behind you sees only a dark screen. Anti-glare coating reduces reflections for comfortable outdoor viewing. Aligns with the iPhone\'s Face ID sensor without interfering with biometric authentication.</p><ul><li><strong>Compatibility:</strong> iPhone 15 Plus</li><li><strong>Privacy Angle:</strong> 30° (only visible directly in front)</li><li><strong>Hardness:</strong> 9H tempered glass</li><li><strong>Coating:</strong> Anti-glare, oleophobic</li><li><strong>Face ID:</strong> Compatible (no interference)</li></ul>'],
            ['sku'=>'TH-SP-103','name'=>'Samsung Galaxy S24 Ultra Screen Protector (2-Pack)','brand'=>'Samsung','category'=>'screen-protectors','price'=>24.00,'special_price'=>null,'weight'=>0.03,'stock'=>73,'new'=>1,'featured'=>0,'short_description'=>'Samsung official Galaxy S24 Ultra glass screen protector 2-pack — designed around S Pen cutout.','description'=>'<p>Samsung\'s official screen protector for Galaxy S24 Ultra includes the precision cutout for the S Pen slot, ensuring the S Pen can be inserted and ejected without lifting the protector edge. Two protectors in the pack provide a replacement if the first is damaged during installation.</p><ul><li><strong>Compatibility:</strong> Samsung Galaxy S24 Ultra</li><li><strong>S Pen:</strong> Precision cutout for S Pen slot</li><li><strong>Quantity:</strong> 2 protectors per pack</li><li><strong>Hardness:</strong> 9H tempered glass</li><li><strong>Touch Sensitivity:</strong> S Pen compatible</li></ul>'],
            ['sku'=>'TH-SP-104','name'=>'Belkin TemperedCurve iPad Pro 12.9" Screen Protector','brand'=>'Belkin','category'=>'screen-protectors','price'=>34.00,'special_price'=>null,'weight'=>0.04,'stock'=>45,'new'=>0,'featured'=>0,'short_description'=>'Belkin TemperedCurve for iPad Pro 12.9" (M4) — curved edge glass with pencil sensitivity optimised.','description'=>'<p>TemperedCurve for iPad Pro M4 12.9" is engineered to preserve Apple Pencil Pro sensitivity and palm rejection accuracy. The curved glass edges prevent lifting and peeling at the corners, while precise cutouts align with the iPad\'s front camera, speakers, and smart connector.</p><ul><li><strong>Compatibility:</strong> iPad Pro 12.9" M4</li><li><strong>Apple Pencil:</strong> Pro sensitivity preserved</li><li><strong>Edge:</strong> Curved glass edges</li><li><strong>Hardness:</strong> 9H tempered glass</li><li><strong>Installation:</strong> Guided installation frame</li></ul>'],
            ['sku'=>'TH-SP-105','name'=>'Anker EasyFit for iPad Air 11" M2 (2-Pack)','brand'=>'Anker','category'=>'screen-protectors','price'=>19.00,'special_price'=>null,'weight'=>0.03,'stock'=>59,'new'=>1,'featured'=>0,'short_description'=>'Anker EasyFit for iPad Air 11" M2 — guided installation frame, 2-pack tempered glass for Apple Pencil Pro.','description'=>'<p>EasyFit includes a plastic installation frame that holds the protector in perfect alignment before you commit — simply position the frame, peel the film, and press down for bubble-free application. Two protectors included for installation mistakes or future replacement.</p><ul><li><strong>Compatibility:</strong> iPad Air 11" M2</li><li><strong>Quantity:</strong> 2 protectors + 2 installation frames</li><li><strong>Apple Pencil:</strong> Compatible with Apple Pencil Pro</li><li><strong>Hardness:</strong> 9H tempered glass</li></ul>'],
        ];
    }
}
