<?php

namespace Database\Seeders\ProductData;

class MonitorData
{
    public static function get(): array
    {
        return array_merge(
            self::gaming(),
            self::professional(),
            self::ultrawide(),
            self::homeOffice(),
        );
    }

    private static function gaming(): array
    {
        return [
            ['sku'=>'TH-GM-001','name'=>'LG 27GP950-B 27" 4K Nano IPS 144Hz','brand'=>'LG','category'=>'gaming-monitors','price'=>799.00,'special_price'=>649.00,'weight'=>5.90,'stock'=>28,'new'=>0,'featured'=>1,'short_description'=>'27" 4K Nano IPS gaming monitor with 144Hz, 1ms GtG response, HDMI 2.1 and G-Sync Compatible.','description'=>'<p>LG UltraGear 27GP950-B delivers true 4K gaming at high refresh rates. HDMI 2.1 with 4K@144Hz enables the full bandwidth of PS5 and Xbox Series X, while Nano IPS technology provides wide colour gamut coverage (98% DCI-P3) for stunning HDR visuals.</p><ul><li><strong>Panel:</strong> 27" Nano IPS, 4K UHD (3840×2160)</li><li><strong>Refresh Rate:</strong> 144Hz (OC 160Hz)</li><li><strong>Response Time:</strong> 1ms GtG</li><li><strong>HDR:</strong> VESA DisplayHDR 600</li><li><strong>Colour:</strong> 98% DCI-P3</li><li><strong>Ports:</strong> 2× HDMI 2.1, 1× DisplayPort 1.4, 2× USB-A</li><li><strong>Sync:</strong> G-Sync Compatible, FreeSync Premium Pro</li></ul>'],
            ['sku'=>'TH-GM-002','name'=>'Samsung Odyssey G7 32" 4K QLED 165Hz','brand'=>'Samsung','category'=>'gaming-monitors','price'=>799.00,'special_price'=>null,'weight'=>6.10,'stock'=>19,'new'=>0,'featured'=>0,'short_description'=>'Samsung Odyssey G7 with 32" 4K QLED panel, 165Hz refresh and 1ms response time.','description'=>'<p>Odyssey G7 combines Samsung\'s QLED colour technology with a flat 4K panel and ultrafast 165Hz refresh rate. Quantum Dot technology delivers 90% DCI-P3 colour volume for rich, accurate colours in both SDR and HDR content.</p><ul><li><strong>Panel:</strong> 32" QLED VA, 4K UHD (3840×2160)</li><li><strong>Refresh Rate:</strong> 165Hz</li><li><strong>Response Time:</strong> 1ms (MPRT)</li><li><strong>HDR:</strong> HDR600</li><li><strong>Colour:</strong> 90% DCI-P3, Quantum Dot</li><li><strong>Ports:</strong> 1× HDMI 2.1, 1× DisplayPort 1.4, 2× USB-A</li><li><strong>Sync:</strong> G-Sync Compatible, FreeSync Premium Pro</li></ul>'],
            ['sku'=>'TH-GM-003','name'=>'Samsung Odyssey Neo G9 57" Dual 4K 240Hz','brand'=>'Samsung','category'=>'gaming-monitors','price'=>2499.00,'special_price'=>null,'weight'=>17.40,'stock'=>6,'new'=>1,'featured'=>1,'short_description'=>'Industry-first Dual 4K 57" mini LED gaming monitor — equivalent to two 4K monitors side by side.','description'=>'<p>Odyssey Neo G9 57" is the most ambitious gaming monitor ever made. The Dual UHD (7680×2160) resolution delivers the equivalent of two 4K displays in a single ultrawide panel, with Mini LED local dimming for HDR performance that rivals OLED.</p><ul><li><strong>Panel:</strong> 57" VA Quantum Mini LED, 7680×2160 (Dual 4K)</li><li><strong>Refresh Rate:</strong> 240Hz</li><li><strong>Response Time:</strong> 1ms</li><li><strong>HDR:</strong> DisplayHDR 1000, 2048 dimming zones</li><li><strong>Colour:</strong> 95% DCI-P3</li><li><strong>Ports:</strong> 1× HDMI 2.1, 2× DisplayPort 1.4, 4× USB-A, 1× USB-C</li></ul>'],
            ['sku'=>'TH-GM-004','name'=>'ASUS ROG Swift PG27AQDM 27" QHD OLED 240Hz','brand'=>'ASUS','category'=>'gaming-monitors','price'=>799.00,'special_price'=>null,'weight'=>5.40,'stock'=>22,'new'=>1,'featured'=>1,'short_description'=>'ASUS ROG 27" QHD OLED gaming monitor with 240Hz, 0.03ms response and true 1,000,000:1 contrast.','description'=>'<p>ROG Swift PG27AQDM brings OLED technology to competitive gaming. The 0.03ms GtG response time is unmatchable by any LCD technology, while perfect blacks and infinite contrast deliver a visual advantage in dark gaming environments.</p><ul><li><strong>Panel:</strong> 27" OLED, QHD (2560×1440)</li><li><strong>Refresh Rate:</strong> 240Hz</li><li><strong>Response Time:</strong> 0.03ms GtG</li><li><strong>Contrast:</strong> 1,000,000:1</li><li><strong>HDR:</strong> HDR True Black 400</li><li><strong>Colour:</strong> 99% DCI-P3</li><li><strong>Ports:</strong> 2× HDMI 2.0, 1× DisplayPort 1.4, 2× USB-A, 1× USB-C</li><li><strong>Sync:</strong> G-Sync Compatible</li></ul>'],
            ['sku'=>'TH-GM-005','name'=>'LG 27GR95QE-B 27" QHD OLED 240Hz','brand'=>'LG','category'=>'gaming-monitors','price'=>699.00,'special_price'=>599.00,'weight'=>4.60,'stock'=>17,'new'=>0,'featured'=>0,'short_description'=>'LG UltraGear 27" OLED gaming monitor with 240Hz, 0.03ms response and 99% DCI-P3.','description'=>'<p>LG UltraGear OLED delivers the gaming monitor trifecta: speed, colour, and contrast. At 240Hz with sub-millisecond response, nothing moves faster in the pixel, while OLED\'s self-emissive pixels deliver perfect black and eye-catching HDR.</p><ul><li><strong>Panel:</strong> 27" OLED, QHD (2560×1440)</li><li><strong>Refresh Rate:</strong> 240Hz</li><li><strong>Response Time:</strong> 0.03ms GtG</li><li><strong>HDR:</strong> VESA DisplayHDR True Black 400</li><li><strong>Colour:</strong> 99% DCI-P3</li><li><strong>Ports:</strong> 2× HDMI 2.0, 1× DisplayPort 1.4, 2× USB-A</li><li><strong>Sync:</strong> G-Sync Compatible, FreeSync Premium</li></ul>'],
            ['sku'=>'TH-GM-006','name'=>'Acer Predator XB273U F 27" QHD 285Hz','brand'=>'ASUS','category'=>'gaming-monitors','price'=>499.00,'special_price'=>429.00,'weight'=>5.70,'stock'=>31,'new'=>0,'featured'=>0,'short_description'=>'Blazing-fast 285Hz QHD IPS gaming monitor with G-Sync certification and built-in USB hub.','description'=>'<p>Predator XB273U F is designed for competitive gamers who prioritise frame rate above all else. At 285Hz native, motions are rendered with exceptional clarity, and NVIDIA G-Sync certification guarantees tear-free performance.</p><ul><li><strong>Panel:</strong> 27" IPS, QHD (2560×1440)</li><li><strong>Refresh Rate:</strong> 285Hz</li><li><strong>Response Time:</strong> 0.5ms GtG</li><li><strong>HDR:</strong> HDR400</li><li><strong>Ports:</strong> 1× HDMI 2.0, 2× DisplayPort 1.4, 4× USB-A</li><li><strong>Sync:</strong> G-Sync</li></ul>'],
            ['sku'=>'TH-GM-007','name'=>'MSI MAG274QRF-QD 27" QHD 165Hz','brand'=>'MSI','category'=>'gaming-monitors','price'=>349.00,'special_price'=>null,'weight'=>4.60,'stock'=>37,'new'=>0,'featured'=>0,'short_description'=>'MSI gaming monitor with Quantum Dot IPS, 165Hz QHD resolution and FreeSync Premium.','description'=>'<p>MAG274QRF-QD provides excellent colour coverage thanks to Quantum Dot technology on an IPS panel — delivering 98% DCI-P3 colour volume at a competitive price. Great for gamers who also do colour-sensitive creative work.</p><ul><li><strong>Panel:</strong> 27" Rapid IPS Quantum Dot, QHD (2560×1440)</li><li><strong>Refresh Rate:</strong> 165Hz</li><li><strong>Response Time:</strong> 1ms</li><li><strong>Colour:</strong> 98% DCI-P3, Quantum Dot</li><li><strong>Ports:</strong> 1× HDMI 2.0b, 1× DisplayPort 1.4a, 2× USB-A</li><li><strong>Sync:</strong> FreeSync Premium</li></ul>'],
            ['sku'=>'TH-GM-008','name'=>'Dell Alienware AW2724HF 27" FHD 360Hz','brand'=>'Dell','category'=>'gaming-monitors','price'=>429.00,'special_price'=>null,'weight'=>4.10,'stock'=>25,'new'=>0,'featured'=>0,'short_description'=>'Alienware 360Hz FHD gaming monitor — the ultimate esports display with certified G-Sync and FreeSync.','description'=>'<p>Alienware AW2724HF targets competitive esports players who demand the absolute highest frame rates at 1080p. The 360Hz IPS display, combined with certified G-Sync and FreeSync Premium Pro compatibility, eliminates tearing and stuttering entirely.</p><ul><li><strong>Panel:</strong> 27" IPS, FHD (1920×1080)</li><li><strong>Refresh Rate:</strong> 360Hz</li><li><strong>Response Time:</strong> 0.5ms GtG</li><li><strong>Ports:</strong> 1× HDMI 2.0, 1× DisplayPort 1.4, 4× USB-A</li><li><strong>Sync:</strong> G-Sync Compatible, FreeSync Premium Pro</li></ul>'],
            ['sku'=>'TH-GM-009','name'=>'ASUS TUF Gaming VG27AQL3A 27" QHD 180Hz','brand'=>'ASUS','category'=>'gaming-monitors','price'=>279.00,'special_price'=>null,'weight'=>4.90,'stock'=>42,'new'=>0,'featured'=>0,'short_description'=>'ASUS TUF 27" QHD gaming monitor with 180Hz, ELMB Sync and ergonomic stand — great value.','description'=>'<p>VG27AQL3A delivers QHD gaming at an entry-level price. The 180Hz IPS panel with ELMB Sync (simultaneous backlight strobing + adaptive sync) reduces motion blur more effectively than standard monitors, giving you a competitive edge.</p><ul><li><strong>Panel:</strong> 27" IPS, QHD (2560×1440)</li><li><strong>Refresh Rate:</strong> 180Hz</li><li><strong>Response Time:</strong> 1ms (MPRT)</li><li><strong>HDR:</strong> HDR10</li><li><strong>Ports:</strong> 2× HDMI 2.0, 1× DisplayPort 1.2, 2× USB-A</li><li><strong>Sync:</strong> G-Sync Compatible, FreeSync Premium</li></ul>'],
            ['sku'=>'TH-GM-010','name'=>'BenQ MOBIUZ EX270QM 27" QHD 240Hz','brand'=>'ASUS','category'=>'gaming-monitors','price'=>499.00,'special_price'=>null,'weight'=>5.80,'stock'=>20,'new'=>0,'featured'=>0,'short_description'=>'BenQ MOBIUZ 27" QHD IPS gaming monitor with 240Hz, built-in 2.1 speakers and BenQ HDRi technology.','description'=>'<p>MOBIUZ EX270QM combines gaming performance with multimedia excellence. The built-in 2.1 channel speaker system with treVolo tuning delivers genuinely good sound, while the 240Hz IPS panel ensures silky-smooth gaming.</p><ul><li><strong>Panel:</strong> 27" IPS, QHD (2560×1440)</li><li><strong>Refresh Rate:</strong> 240Hz</li><li><strong>Response Time:</strong> 1ms GtG</li><li><strong>HDR:</strong> HDRi, DisplayHDR 400</li><li><strong>Audio:</strong> Built-in 2.1 speaker system with subwoofer</li><li><strong>Ports:</strong> 2× HDMI 2.0, 1× DisplayPort 1.4, 2× USB-A</li><li><strong>Sync:</strong> FreeSync Premium</li></ul>'],
        ];
    }

    private static function professional(): array
    {
        return [
            ['sku'=>'TH-PM-001','name'=>'ASUS ProArt PA32UCG-K 32" 4K Mini LED HDR1400','brand'=>'ASUS','category'=>'professional-monitors','price'=>3299.00,'special_price'=>null,'weight'=>13.60,'stock'=>5,'new'=>0,'featured'=>0,'short_description'=>'Reference-grade 32" 4K mini LED display with HDR1400, 1152 dimming zones and hardware calibration.','description'=>'<p>PA32UCG-K is ASUS\'s top-tier professional reference monitor for film colourists, photographers and digital artists who require uncompromising accuracy. The mini LED backlight with 1152 local dimming zones delivers HDR performance previously only available in cinema-grade displays.</p><ul><li><strong>Panel:</strong> 32" IPS with Mini LED, 4K UHD (3840×2160)</li><li><strong>Refresh Rate:</strong> 120Hz</li><li><strong>HDR:</strong> VESA DisplayHDR 1400, 1152 dimming zones</li><li><strong>Colour:</strong> 99.5% Adobe RGB, 99% DCI-P3, Delta E&lt;2 factory-calibrated</li><li><strong>Ports:</strong> 1× Thunderbolt 3, 1× HDMI 2.0, 2× DisplayPort 1.4, 4× USB-A</li><li><strong>Calibration:</strong> Built-in 14-bit 3D LUT, ProArt Calibration software</li></ul>'],
            ['sku'=>'TH-PM-002','name'=>'BenQ PD3220U 32" 4K IPS USB-C','brand'=>'ASUS','category'=>'professional-monitors','price'=>1099.00,'special_price'=>null,'weight'=>7.90,'stock'=>14,'new'=>0,'featured'=>0,'short_description'=>'BenQ DesignVue 32" 4K IPS monitor with 100% sRGB, 95% DCI-P3, USB-C 65W and KVM switch.','description'=>'<p>PD3220U is BenQ\'s flagship design monitor for Mac users and creative professionals. Thunderbolt 3 connectivity delivers 4K signal and 65W charging over a single cable, while the built-in KVM switch lets you share keyboard and mouse across two computers.</p><ul><li><strong>Panel:</strong> 32" IPS, 4K UHD (3840×2160)</li><li><strong>Colour:</strong> 100% sRGB, 95% DCI-P3, Delta E&lt;2, PANTONE Validated</li><li><strong>Ports:</strong> 2× Thunderbolt 3 (65W), 2× HDMI, 1× DisplayPort, 4× USB-A</li><li><strong>Features:</strong> Built-in KVM, Eye-Care, Black equaliser</li></ul>'],
            ['sku'=>'TH-PM-003','name'=>'Dell UltraSharp U2723D 27" 4K IPS USB-C','brand'=>'Dell','category'=>'professional-monitors','price'=>549.00,'special_price'=>null,'weight'=>6.30,'stock'=>26,'new'=>0,'featured'=>0,'short_description'=>'Dell UltraSharp 27" 4K IPS with 100% sRGB, 98% DCI-P3, USB-C 90W and factory-calibrated accuracy.','description'=>'<p>UltraSharp U2723D is Dell\'s best all-round professional monitor. Factory-calibrated to Delta E&lt;2, it covers 100% sRGB and 98% DCI-P3 out of the box. A single USB-C cable delivers 4K video and 90W charging to compatible laptops.</p><ul><li><strong>Panel:</strong> 27" ComfortView Plus IPS, 4K UHD (3840×2160)</li><li><strong>Colour:</strong> 100% sRGB, 98% DCI-P3, Delta E&lt;2</li><li><strong>Ports:</strong> 1× USB-C 3.2 (90W), 1× HDMI 2.0, 1× DisplayPort 1.4, 5× USB-A</li><li><strong>Certification:</strong> ENERGY STAR, EPEAT Gold, Eye Comfort</li></ul>'],
            ['sku'=>'TH-PM-004','name'=>'LG 27UP850N-W 27" 4K IPS USB-C','brand'=>'LG','category'=>'professional-monitors','price'=>449.00,'special_price'=>379.00,'weight'=>5.60,'stock'=>31,'new'=>0,'featured'=>0,'short_description'=>'LG 27" 4K IPS monitor with 95% DCI-P3, USB-C 96W charging and height-adjustable stand.','description'=>'<p>27UP850N-W offers 4K clarity with professional colour coverage at a mid-range price. The 96W USB-C Power Delivery can charge most laptops at full speed while displaying 4K content over a single cable.</p><ul><li><strong>Panel:</strong> 27" IPS, 4K UHD (3840×2160)</li><li><strong>Colour:</strong> 95% DCI-P3, 99% sRGB, Delta E&lt;2</li><li><strong>Ports:</strong> 1× USB-C (96W), 2× HDMI 2.0, 1× DisplayPort 1.4, 2× USB-A</li><li><strong>Stand:</strong> Height, tilt, pivot adjustable</li></ul>'],
            ['sku'=>'TH-PM-005','name'=>'Samsung ViewFinity S9 27" 5K IPS','brand'=>'Samsung','category'=>'professional-monitors','price'=>1299.00,'special_price'=>null,'weight'=>6.90,'stock'=>9,'new'=>1,'featured'=>0,'short_description'=>'Samsung\'s first 5K monitor with 218ppi pixel density, Thunderbolt 4 and built-in 4K webcam.','description'=>'<p>ViewFinity S9 targets Mac Studio and Mac Pro users needing a single ultra-high-resolution display. At 5120×2880, it matches the pixel density of Apple\'s Pro Display XDR at a fraction of the cost, and includes a detachable 4K Webex-certified webcam.</p><ul><li><strong>Panel:</strong> 27" IPS, 5K (5120×2880), 218ppi</li><li><strong>Colour:</strong> 99% DCI-P3, 99% Adobe RGB, Delta E&lt;2</li><li><strong>Ports:</strong> 1× Thunderbolt 4 (90W), 2× HDMI 2.0, 4× USB-A</li><li><strong>Features:</strong> Detachable 4K webcam, Eye-Care Plus</li></ul>'],
            ['sku'=>'TH-PM-006','name'=>'ASUS ProArt PA279CV 27" 4K IPS','brand'=>'ASUS','category'=>'professional-monitors','price'=>449.00,'special_price'=>null,'weight'=>6.10,'stock'=>22,'new'=>0,'featured'=>0,'short_description'=>'ASUS ProArt 27" 4K IPS with 100% sRGB, USB-C 65W and factory Delta E&lt;2 calibration.','description'=>'<p>PA279CV delivers professional colour accuracy at an accessible price. PANTONE Validated and Calman Verified, it arrives factory-calibrated with a report included, saving time for professionals who can\'t afford miscalibrated displays.</p><ul><li><strong>Panel:</strong> 27" IPS, 4K UHD (3840×2160)</li><li><strong>Colour:</strong> 100% sRGB, 100% Rec.709, Delta E&lt;2, PANTONE Validated</li><li><strong>Ports:</strong> 1× USB-C (65W), 1× HDMI 2.0, 1× DisplayPort 1.2, 4× USB-A</li></ul>'],
            ['sku'=>'TH-PM-007','name'=>'HP Z27xs G3 27" 4K DreamColor IPS','brand'=>'HP','category'=>'professional-monitors','price'=>649.00,'special_price'=>null,'weight'=>6.60,'stock'=>11,'new'=>0,'featured'=>0,'short_description'=>'HP DreamColor 27" 4K professional display with 99% Adobe RGB and ISF-certified calibration.','description'=>'<p>Z27xs G3 DreamColor is HP\'s professional reference display designed for video production and colour-critical workflows. ISF-certified calibration ensures consistency across multiple units in a production environment.</p><ul><li><strong>Panel:</strong> 27" IPS, 4K UHD (3840×2160)</li><li><strong>Colour:</strong> 99% Adobe RGB, 98% DCI-P3, Delta E&lt;2, ISF Certified</li><li><strong>Ports:</strong> 1× USB-C (65W), 1× HDMI 2.0, 1× DisplayPort 1.4, 4× USB-A</li></ul>'],
            ['sku'=>'TH-PM-008','name'=>'BenQ SW272Q 27" QHD IPS Photographer','brand'=>'ASUS','category'=>'professional-monitors','price'=>699.00,'special_price'=>null,'weight'=>6.20,'stock'=>13,'new'=>0,'featured'=>0,'short_description'=>'BenQ SW272Q photography monitor with 99% Adobe RGB, hardware calibration and hotkey puck.','description'=>'<p>SW272Q is purpose-built for photographers. The 99% Adobe RGB coverage ensures accurate print colours, hardware LUT calibration maintains accuracy over time, and the included hotkey puck lets you switch between colour modes without touching the monitor.</p><ul><li><strong>Panel:</strong> 27" IPS, QHD (2560×1440)</li><li><strong>Colour:</strong> 99% Adobe RGB, 95% DCI-P3, Delta E&lt;2</li><li><strong>Ports:</strong> 1× USB-C (60W), 1× HDMI 2.0, 1× DisplayPort 1.4, 4× USB-A, SD card</li><li><strong>Extras:</strong> Hotkey puck, anti-glare shield included</li></ul>'],
        ];
    }

    private static function ultrawide(): array
    {
        return [
            ['sku'=>'TH-UW-001','name'=>'LG 34GP950G-B 34" WQHD Nano IPS 160Hz','brand'=>'LG','category'=>'ultrawide-monitors','price'=>899.00,'special_price'=>749.00,'weight'=>7.30,'stock'=>16,'new'=>0,'featured'=>1,'short_description'=>'LG UltraGear 34" 21:9 Nano IPS gaming monitor with 160Hz, G-Sync and 98% DCI-P3.','description'=>'<p>34GP950G-B is the gold standard in ultrawide gaming monitors. The 34-inch 21:9 format provides an immersive field of view in games while offering superior multitasking capabilities — the equivalent of two 24" monitors placed side by side.</p><ul><li><strong>Panel:</strong> 34" Nano IPS, WQHD (3440×1440)</li><li><strong>Refresh Rate:</strong> 160Hz (OC 175Hz)</li><li><strong>Response Time:</strong> 1ms GtG</li><li><strong>Colour:</strong> 98% DCI-P3, Nano IPS</li><li><strong>Ports:</strong> 1× HDMI 2.0, 2× DisplayPort 1.4, 2× USB-A</li><li><strong>Sync:</strong> G-Sync</li></ul>'],
            ['sku'=>'TH-UW-002','name'=>'Samsung Odyssey OLED G9 49" 5120×1440 240Hz','brand'=>'Samsung','category'=>'ultrawide-monitors','price'=>1799.00,'special_price'=>null,'weight'=>16.40,'stock'=>7,'new'=>1,'featured'=>1,'short_description'=>'Samsung\'s 49" dual QHD OLED curved ultrawide — 240Hz, 0.03ms response and infinite contrast.','description'=>'<p>Odyssey OLED G9 combines the immersion of a 49-inch dual-QHD resolution with OLED\'s perfect black and infinite contrast. For the gamer or creative who truly wants the most expansive display experience possible.</p><ul><li><strong>Panel:</strong> 49" OLED, 5120×1440 (Dual QHD), 1800R curve</li><li><strong>Refresh Rate:</strong> 240Hz</li><li><strong>Response Time:</strong> 0.03ms GtG</li><li><strong>HDR:</strong> DisplayHDR True Black 400</li><li><strong>Ports:</strong> 2× HDMI 2.1, 1× DisplayPort 1.4, 4× USB-A, 1× USB-C</li><li><strong>Sync:</strong> G-Sync Compatible, FreeSync Premium Pro</li></ul>'],
            ['sku'=>'TH-UW-003','name'=>'Dell U3423WE 34" WQHD IPS USB-C','brand'=>'Dell','category'=>'ultrawide-monitors','price'=>849.00,'special_price'=>null,'weight'=>7.90,'stock'=>18,'new'=>0,'featured'=>0,'short_description'=>'Dell UltraSharp 34" WQHD IPS ultrawide with 90W USB-C, built-in KVM and 100Hz refresh.','description'=>'<p>U3423WE is the professional\'s ultrawide — with USB-C hub functionality, built-in KVM, and 100% sRGB colour accuracy. The 34-inch WQHD screen gives you the workspace to run multiple apps side by side without window management headaches.</p><ul><li><strong>Panel:</strong> 34" IPS, WQHD (3440×1440), 100Hz</li><li><strong>Colour:</strong> 100% sRGB, 98% DCI-P3, Delta E&lt;2</li><li><strong>Ports:</strong> 1× Thunderbolt 4 (90W), 1× USB-C (15W), 2× HDMI, 1× DP, 5× USB-A</li><li><strong>Features:</strong> Built-in KVM, Picture-in-Picture, Picture-by-Picture</li></ul>'],
            ['sku'=>'TH-UW-004','name'=>'LG 40WP95C-W 40" WQHD+ IPS Curved USB-C','brand'=>'LG','category'=>'ultrawide-monitors','price'=>1199.00,'special_price'=>null,'weight'=>9.40,'stock'=>9,'new'=>0,'featured'=>0,'short_description'=>'LG 40" 5:2 curved ultrawide with WQHD+ resolution, Thunderbolt 4 and 96W USB-C charging.','description'=>'<p>40WP95C-W fills the space between ultrawide and super-ultrawide with a 40-inch 5:2 aspect ratio that\'s surprisingly productive. Thunderbolt 4 delivers the full bandwidth needed for daisy-chaining and external GPU enclosures.</p><ul><li><strong>Panel:</strong> 40" IPS, WQHD+ (5120×2160), 72Hz, 2300R curve</li><li><strong>Colour:</strong> 98% DCI-P3</li><li><strong>Ports:</strong> 1× Thunderbolt 4 (96W), 1× USB-C, 2× HDMI, 1× DP, 4× USB-A</li></ul>'],
            ['sku'=>'TH-UW-005','name'=>'ASUS ProArt PA34VCNV 34" WQHD IPS','brand'=>'ASUS','category'=>'ultrawide-monitors','price'=>899.00,'special_price'=>null,'weight'=>9.00,'stock'=>11,'new'=>0,'featured'=>0,'short_description'=>'ASUS ProArt 34" WQHD ultrawide with 100% sRGB, USB-C 65W and PANTONE Validated calibration.','description'=>'<p>PA34VCNV is ASUS\'s professional ultrawide for content creators who need colour accuracy and screen real estate simultaneously. PANTONE Validated and Calman Verified with Delta E&lt;2, it\'s suitable for photo retouching and video production.</p><ul><li><strong>Panel:</strong> 34" IPS, WQHD (3440×1440), 100Hz, 1900R curve</li><li><strong>Colour:</strong> 100% sRGB, 99% DCI-P3, Delta E&lt;2, PANTONE Validated</li><li><strong>Ports:</strong> 1× USB-C (65W), 2× HDMI 2.0, 1× DisplayPort 1.4, 4× USB-A</li></ul>'],
            ['sku'=>'TH-UW-006','name'=>'Samsung Odyssey G8 34" WQHD OLED 175Hz','brand'=>'Samsung','category'=>'ultrawide-monitors','price'=>1199.00,'special_price'=>null,'weight'=>7.90,'stock'=>12,'new'=>1,'featured'=>0,'short_description'=>'Samsung 34" WQHD OLED ultrawide gaming monitor with 175Hz, 0.1ms response and HDMI 2.1.','description'=>'<p>Odyssey G8 34" OLED delivers the ultrawide gaming experience with OLED quality — perfect blacks, near-instant response, and brilliant colour. The 175Hz refresh rate makes it equally capable for competitive gaming and immersive single-player titles.</p><ul><li><strong>Panel:</strong> 34" OLED, WQHD (3440×1440), 175Hz, 1800R curve</li><li><strong>Response Time:</strong> 0.1ms GtG</li><li><strong>HDR:</strong> DisplayHDR True Black 400</li><li><strong>Ports:</strong> 1× HDMI 2.1, 1× DisplayPort 1.4, 2× USB-A, 1× USB-C</li></ul>'],
        ];
    }

    private static function homeOffice(): array
    {
        return [
            ['sku'=>'TH-HO-001','name'=>'Dell P2723D 27" QHD IPS USB-C','brand'=>'Dell','category'=>'home-office-monitors','price'=>349.00,'special_price'=>null,'weight'=>4.80,'stock'=>38,'new'=>0,'featured'=>0,'short_description'=>'Dell 27" QHD IPS monitor with USB-C 65W, 60Hz and height-adjustable ergonomic stand.','description'=>'<p>P2723D hits the sweet spot for home office users — QHD sharpness, USB-C docking convenience, and an ergonomic stand that adjusts to your height, all at an approachable price. ENERGY STAR and EPEAT Silver certified.</p><ul><li><strong>Panel:</strong> 27" IPS, QHD (2560×1440), 60Hz</li><li><strong>Colour:</strong> 99% sRGB, Delta E&lt;2</li><li><strong>Ports:</strong> 1× USB-C (65W), 2× HDMI, 1× DisplayPort, 4× USB-A</li><li><strong>Stand:</strong> Height, tilt, swivel, pivot</li></ul>'],
            ['sku'=>'TH-HO-002','name'=>'LG 32UN880-B 32" 4K IPS Ergo USB-C','brand'=>'LG','category'=>'home-office-monitors','price'=>699.00,'special_price'=>null,'weight'=>6.30,'stock'=>21,'new'=>0,'featured'=>0,'short_description'=>'LG 32" 4K IPS with innovative Ergo arm stand, 96W USB-C charging and front-facing USB hub.','description'=>'<p>32UN880-B includes LG\'s innovative Ergo stand that clamps to your desk and provides full range-of-motion adjustment — height, tilt, swivel, and arm extension — freeing up desk space and enabling ergonomic positioning that traditional stands can\'t achieve.</p><ul><li><strong>Panel:</strong> 32" IPS, 4K UHD (3840×2160), 60Hz</li><li><strong>Colour:</strong> 95% DCI-P3</li><li><strong>Ports:</strong> 1× USB-C (96W), 2× HDMI 2.0, 1× DisplayPort 1.4, 2× USB-A</li><li><strong>Stand:</strong> Ergo clamp-mount arm, full range of motion</li></ul>'],
            ['sku'=>'TH-HO-003','name'=>'HP M32f 32" FHD IPS','brand'=>'HP','category'=>'home-office-monitors','price'=>229.00,'special_price'=>199.00,'weight'=>5.10,'stock'=>52,'new'=>0,'featured'=>0,'short_description'=>'HP 32" Full HD IPS monitor with low blue light, AMD FreeSync and anti-glare coating.','description'=>'<p>HP M32f is a straightforward 32-inch productivity monitor with IPS colours, AMD FreeSync for smooth video playback, and HP Eye Ease low-blue-light technology for comfortable all-day use. Great value for remote workers and students.</p><ul><li><strong>Panel:</strong> 32" IPS, FHD (1920×1080), 75Hz</li><li><strong>Ports:</strong> 1× HDMI, 1× VGA</li><li><strong>Eye Care:</strong> HP Eye Ease (low blue light), Anti-Glare</li><li><strong>Sync:</strong> AMD FreeSync</li></ul>'],
            ['sku'=>'TH-HO-004','name'=>'ASUS VA27EHF 27" FHD IPS Eye Care','brand'=>'ASUS','category'=>'home-office-monitors','price'=>179.00,'special_price'=>null,'weight'=>3.20,'stock'=>63,'new'=>0,'featured'=>0,'short_description'=>'Compact ASUS 27" FHD IPS with near-frameless design, 100Hz and ASUS Eye Care Plus technology.','description'=>'<p>VA27EHF offers a clean, minimal setup with its near-frameless design and thin bezels. The 100Hz refresh rate makes scrolling and general desktop use noticeably smoother than standard 60Hz monitors.</p><ul><li><strong>Panel:</strong> 27" IPS, FHD (1920×1080), 100Hz</li><li><strong>Response Time:</strong> 1ms</li><li><strong>Eye Care:</strong> Blue Light Filter, Flicker-free</li><li><strong>Ports:</strong> 1× HDMI, 1× DisplayPort</li></ul>'],
            ['sku'=>'TH-HO-005','name'=>'Samsung S80PB 32" 4K IPS USB-C','brand'=>'Samsung','category'=>'home-office-monitors','price'=>449.00,'special_price'=>null,'weight'=>5.70,'stock'=>27,'new'=>0,'featured'=>0,'short_description'=>'Samsung 32" 4K IPS monitor with USB-C 65W, PiP/PbP and Samsung DeX desktop mode support.','description'=>'<p>S80PB 32" offers 4K productivity with Samsung ecosystem integration — Samsung DeX lets you use compatible Galaxy phones and tablets as a PC-like desktop experience on the monitor, all over a single USB-C cable.</p><ul><li><strong>Panel:</strong> 32" IPS, 4K UHD (3840×2160), 60Hz</li><li><strong>Colour:</strong> 99% sRGB</li><li><strong>Ports:</strong> 1× USB-C (65W), 2× HDMI, 1× DisplayPort, 3× USB-A</li><li><strong>Features:</strong> PiP, PbP, Samsung DeX, Eye Care+</li></ul>'],
            ['sku'=>'TH-HO-006','name'=>'BenQ GW2785TC 27" FHD IPS USB-C','brand'=>'ASUS','category'=>'home-office-monitors','price'=>249.00,'special_price'=>null,'weight'=>4.10,'stock'=>33,'new'=>0,'featured'=>0,'short_description'=>'BenQ 27" FHD IPS with USB-C, built-in microphone, speakers and Eye-Care Plus for home office comfort.','description'=>'<p>GW2785TC is designed specifically for video calls and remote work — the built-in microphone, front-facing speakers, and low blue light technology combine to make it the ideal home-office upgrade over a laptop screen.</p><ul><li><strong>Panel:</strong> 27" IPS, FHD (1920×1080), 75Hz</li><li><strong>Audio:</strong> Built-in microphone + dual 2.5W speakers</li><li><strong>Ports:</strong> 1× USB-C (65W), 1× HDMI, 1× DisplayPort, 2× USB-A</li><li><strong>Eye Care:</strong> BenQ Eye-Care Plus, Low Blue Light+</li></ul>'],
        ];
    }
}
