<?php

namespace Database\Seeders\ProductData;

class MouseData
{
    public static function get(): array
    {
        return array_merge(
            self::gaming(),
            self::productivity(),
        );
    }

    private static function gaming(): array
    {
        return [
            ['sku'=>'TH-GM-101','name'=>'Logitech G Pro X Superlight 2 DEX Wireless','brand'=>'Logitech','category'=>'gaming-mice','price'=>199.00,'special_price'=>null,'weight'=>0.06,'stock'=>43,'new'=>1,'featured'=>1,'short_description'=>'Logitech G Pro X Superlight 2 DEX — HERO 2 sensor, 32K DPI, LIGHTSPEED 2.4 GHz at only 60g.','description'=>'<p>Superlight 2 DEX is Logitech\'s finest esports mouse, weighing just 60g with the HERO 2 sensor delivering flawless 32,000 DPI tracking at up to 500 IPS. LIGHTSPEED 2.4 GHz wireless adds zero perceptible latency versus wired. Designed asymmetrically with optional right/left grips for professional right-hand ergonomic use.</p><ul><li><strong>Sensor:</strong> HERO 2 optical, 32,000 DPI</li><li><strong>Tracking Speed:</strong> 500 IPS</li><li><strong>Wireless:</strong> LIGHTSPEED 2.4 GHz</li><li><strong>Battery:</strong> 95 hours</li><li><strong>Weight:</strong> 60g</li><li><strong>Switches:</strong> Optical (100M click endurance)</li><li><strong>Polling Rate:</strong> 2000 Hz</li></ul>'],
            ['sku'=>'TH-GM-102','name'=>'Razer DeathAdder V3 HyperSpeed Wireless','brand'=>'Razer','category'=>'gaming-mice','price'=>129.00,'special_price'=>null,'weight'=>0.08,'stock'=>57,'new'=>1,'featured'=>0,'short_description'=>'Razer DeathAdder V3 HyperSpeed — ergonomic wireless gaming mouse with Focus Pro 30K sensor at 82g.','description'=>'<p>DeathAdder V3 HyperSpeed brings Razer\'s beloved ergonomic shape to wireless. The Focus Pro 30K optical sensor tracks on any surface with 99.8% tracking accuracy, and the asymmetric right-hand shape provides a secure palm grip without pressure points during long gaming sessions.</p><ul><li><strong>Sensor:</strong> Focus Pro 30K optical</li><li><strong>DPI:</strong> 100–30,000</li><li><strong>Wireless:</strong> Razer HyperSpeed 2.4 GHz</li><li><strong>Battery:</strong> 300 hours (no RGB)</li><li><strong>Weight:</strong> 82g</li><li><strong>Shape:</strong> Ergonomic right-hand</li></ul>'],
            ['sku'=>'TH-GM-103','name'=>'SteelSeries Aerox 9 Wireless Ultra-Light','brand'=>'SteelSeries','category'=>'gaming-mice','price'=>159.00,'special_price'=>139.00,'weight'=>0.09,'stock'=>28,'new'=>0,'featured'=>0,'short_description'=>'SteelSeries Aerox 9 Wireless — 18-button MMO/battle royale mouse with honeycomb shell at 89g.','description'=>'<p>Aerox 9 Wireless is built for MMO and battle royale players who need many programmable bindings at their fingertips. 18 independently programmable buttons include a 4-way scroll wheel, two thumb button clusters, and a precision clicker. The honeycomb shell keeps weight at 89g despite the button count.</p><ul><li><strong>Sensor:</strong> TrueMove Air 18,000 DPI</li><li><strong>Buttons:</strong> 18 programmable</li><li><strong>Wireless:</strong> 2.4 GHz + Bluetooth 5.0</li><li><strong>Battery:</strong> 180 hours (no RGB)</li><li><strong>Weight:</strong> 89g</li><li><strong>Shell:</strong> AquaBarrier honeycomb</li></ul>'],
            ['sku'=>'TH-GM-104','name'=>'Corsair Scimitar Elite RGB Wireless MMO Mouse','brand'=>'Corsair','category'=>'gaming-mice','price'=>99.00,'special_price'=>null,'weight'=>0.13,'stock'=>34,'new'=>0,'featured'=>0,'short_description'=>'Corsair Scimitar Elite RGB — 17-key adjustable side button cluster for MMO/MOBA mastery.','description'=>'<p>Scimitar Elite\'s Key Slider system lets you physically adjust the side button cluster forward or backward by up to 8mm — accommodating every hand size and grip style. All 17 side buttons are programmable via iCUE. The Slipstream wireless tech delivers 2000 Hz polling rate for responsive gameplay.</p><ul><li><strong>Sensor:</strong> Marksman optical 26,000 DPI</li><li><strong>Side Buttons:</strong> 17 (Key Slider adjustable)</li><li><strong>Wireless:</strong> Corsair Slipstream 2.4 GHz + USB-C</li><li><strong>Battery:</strong> 100 hours</li><li><strong>Polling Rate:</strong> 2000 Hz</li><li><strong>Software:</strong> Corsair iCUE</li></ul>'],
            ['sku'=>'TH-GM-105','name'=>'Razer Viper Mini Signature Edition Wireless','brand'=>'Razer','category'=>'gaming-mice','price'=>299.00,'special_price'=>null,'weight'=>0.05,'stock'=>11,'new'=>1,'featured'=>0,'short_description'=>'Razer Viper Mini Signature Edition — ultra-light 49g wireless mouse for claw/fingertip grip players.','description'=>'<p>Viper Mini Signature Edition is the lightest wireless gaming mouse Razer has produced at just 49g. The small form factor suits claw and fingertip grip players — especially those who play at very high sensitivity (400–800 DPI) and move the mouse with their fingers rather than wrist or arm.</p><ul><li><strong>Sensor:</strong> Focus Pro 30K optical</li><li><strong>Weight:</strong> 49g</li><li><strong>Wireless:</strong> HyperSpeed 2.4 GHz</li><li><strong>Battery:</strong> 80 hours</li><li><strong>Shape:</strong> Small symmetric</li><li><strong>Material:</strong> Magnesium alloy chassis</li></ul>'],
            ['sku'=>'TH-GM-106','name'=>'Logitech G305 Lightspeed Wireless Gaming Mouse','brand'=>'Logitech','category'=>'gaming-mice','price'=>39.00,'special_price'=>null,'weight'=>0.09,'stock'=>96,'new'=>0,'featured'=>0,'short_description'=>'Logitech G305 LIGHTSPEED — entry-level wireless gaming mouse with HERO sensor and 250-hour battery.','description'=>'<p>G305 proves you don\'t need to spend over $100 for wireless gaming mouse performance. HERO 16K sensor delivers the same tracking accuracy as Logitech\'s flagship sensors, LIGHTSPEED 2.4 GHz provides sub-1ms wireless performance, and 250-hour battery life means you\'ll rarely need to change the AA battery.</p><ul><li><strong>Sensor:</strong> HERO 16K optical, 200–16,000 DPI</li><li><strong>Wireless:</strong> LIGHTSPEED 2.4 GHz</li><li><strong>Battery:</strong> 250 hours (1× AA)</li><li><strong>Weight:</strong> 99g</li><li><strong>Polling Rate:</strong> 1000 Hz</li></ul>'],
            ['sku'=>'TH-GM-107','name'=>'SteelSeries Prime Wireless Gaming Mouse','brand'=>'SteelSeries','category'=>'gaming-mice','price'=>79.00,'special_price'=>69.00,'weight'=>0.10,'stock'=>51,'new'=>0,'featured'=>0,'short_description'=>'SteelSeries Prime Wireless — 100-hour battery, TrueMove Air sensor and magnetic switch optical buttons.','description'=>'<p>Prime Wireless balances features, performance, and price intelligently. Magnetic optical switches eliminate mechanical debounce for 0ms click latency, the TrueMove Air sensor tracks with sub-pixel precision, and 100-hour battery makes it one of the most practical wireless gaming mice in this price range.</p><ul><li><strong>Sensor:</strong> TrueMove Air 18,000 DPI</li><li><strong>Wireless:</strong> 2.4 GHz</li><li><strong>Battery:</strong> 100 hours</li><li><strong>Switches:</strong> Magnetic optical (0ms debounce)</li><li><strong>Weight:</strong> 98g</li></ul>'],
            ['sku'=>'TH-GM-108','name'=>'Razer Basilisk V3 Pro Wireless','brand'=>'Razer','category'=>'gaming-mice','price'=>159.00,'special_price'=>null,'weight'=>0.11,'stock'=>37,'new'=>0,'featured'=>0,'short_description'=>'Razer Basilisk V3 Pro — 11 programmable buttons, SmartReel scroll wheel, HyperSpeed and Chroma RGB.','description'=>'<p>Basilisk V3 Pro\'s SmartReel scroll wheel switches between tactile notched scrolling and free-spinning hyper-scroll mode, enabling both precise page navigation and rapid document scrolling. Eleven programmable buttons with on-board memory store 5 profiles locally — useful for competitive players switching between games.</p><ul><li><strong>Sensor:</strong> Focus Pro 30K optical</li><li><strong>Wireless:</strong> HyperSpeed 2.4 GHz + Bluetooth</li><li><strong>Battery:</strong> 90 hours</li><li><strong>Scroll:</strong> SmartReel dual-mode</li><li><strong>Buttons:</strong> 11 programmable</li><li><strong>RGB:</strong> Razer Chroma, 11 zones</li></ul>'],
        ];
    }

    private static function productivity(): array
    {
        return [
            ['sku'=>'TH-PM-101','name'=>'Logitech MX Master 3S Wireless Mouse','brand'=>'Logitech','category'=>'productivity-mice','price'=>99.00,'special_price'=>null,'weight'=>0.14,'stock'=>89,'new'=>1,'featured'=>1,'short_description'=>'Logitech MX Master 3S — 8K DPI precision, MagSpeed wheel, multi-device and Flow cross-computer control.','description'=>'<p>MX Master 3S is the benchmark for productivity mice. The MagSpeed electromagnetic scroll wheel shifts between precise click-to-click scrolling and free-spinning inertia mode — enabling you to scroll through 1000-line documents in a single flick. Flow cross-computer control lets you drag files between two computers using one mouse.</p><ul><li><strong>Sensor:</strong> 8,000 DPI optical</li><li><strong>Scroll:</strong> MagSpeed electromagnetic (click-to-click / freespin)</li><li><strong>Wireless:</strong> Bluetooth (3 devices) + Logi Bolt USB</li><li><strong>Battery:</strong> 70 days</li><li><strong>Buttons:</strong> 7 programmable</li><li><strong>OS Flow:</strong> Yes (cross-computer control)</li></ul>'],
            ['sku'=>'TH-PM-102','name'=>'Apple Magic Mouse (USB-C, Black)','brand'=>'Apple','category'=>'productivity-mice','price'=>79.00,'special_price'=>null,'weight'=>0.10,'stock'=>47,'new'=>1,'featured'=>0,'short_description'=>'Apple Magic Mouse USB-C with Multi-Touch surface — swipe, pinch and tap gestures for macOS.','description'=>'<p>Magic Mouse\'s entire top surface is a Multi-Touch surface that recognises macOS system gestures — swipe between desktops, switch between full-screen apps, and activate Mission Control without touching the keyboard. Now with USB-C charging (updated from Lightning) in Space Black and Silver.</p><ul><li><strong>Tracking:</strong> Multi-Touch optical</li><li><strong>Gestures:</strong> Swipe, pinch, Smart Zoom, Mission Control</li><li><strong>Wireless:</strong> Bluetooth 5.0</li><li><strong>Battery:</strong> ~1 month (rechargeable)</li><li><strong>Charging:</strong> USB-C</li><li><strong>Compatibility:</strong> Mac</li></ul>'],
            ['sku'=>'TH-PM-103','name'=>'Logitech MX Anywhere 3S Compact Wireless','brand'=>'Logitech','category'=>'productivity-mice','price'=>79.00,'special_price'=>null,'weight'=>0.10,'stock'=>63,'new'=>1,'featured'=>0,'short_description'=>'Logitech MX Anywhere 3S — compact productivity mouse with 8K DPI, MagSpeed scroll and multi-device.','description'=>'<p>MX Anywhere 3S packs MX Master-class features into a compact form factor that travels in a laptop bag without bulk. Works on glass surfaces where conventional optical mice fail. Three-device Bluetooth pairing with instant Easy-Switch button makes it ideal for road warriors with phone, laptop, and tablet.</p><ul><li><strong>Sensor:</strong> 8,000 DPI optical (works on glass)</li><li><strong>Scroll:</strong> MagSpeed (click-to-click / freespin)</li><li><strong>Wireless:</strong> Bluetooth (3 devices) + Logi Bolt</li><li><strong>Battery:</strong> 70 days (USB-C rechargeable)</li><li><strong>Weight:</strong> 99g</li></ul>'],
            ['sku'=>'TH-PM-104','name'=>'Logitech Lift Vertical Ergonomic Mouse','brand'=>'Logitech','category'=>'productivity-mice','price'=>69.00,'special_price'=>null,'weight'=>0.13,'stock'=>52,'new'=>0,'featured'=>0,'short_description'=>'Logitech Lift Vertical Mouse — natural 57° upright angle reduces forearm twisting and wrist pain.','description'=>'<p>Lift Vertical holds your hand in a natural handshake position at 57°, preventing the forearm twisting that causes wrist and elbow fatigue with conventional mice. Quiet Click buttons reduce noise by 90% versus standard mice — ideal for open-plan offices. Available in small/medium and medium/large sizes.</p><ul><li><strong>Angle:</strong> 57° vertical</li><li><strong>DPI:</strong> 400–4,000 (3 levels)</li><li><strong>Wireless:</strong> Bluetooth + Logi Bolt</li><li><strong>Battery:</strong> 24 months (AA)</li><li><strong>Buttons:</strong> 6 (quiet click)</li><li><strong>Sizes:</strong> Small/Medium, Medium/Large</li></ul>'],
            ['sku'=>'TH-PM-105','name'=>'Logitech MX Master 3 for Mac Wireless','brand'=>'Logitech','category'=>'productivity-mice','price'=>99.00,'special_price'=>null,'weight'=>0.14,'stock'=>44,'new'=>0,'featured'=>0,'short_description'=>'Logitech MX Master 3 for Mac — specifically tuned for macOS with Space Grey finish and USB-C.','description'=>'<p>MX Master 3 for Mac is tuned for macOS gesture integration — horizontal scroll moves between full-screen apps, Mission Control, Launchpad, and Notification Centre. The USB-C charging cable and Space Grey finish match Apple MacBooks and peripherals. iCloud sync keeps settings across Macs.</p><ul><li><strong>Sensor:</strong> 4,000 DPI optical</li><li><strong>Scroll:</strong> MagSpeed (click-to-click / freespin)</li><li><strong>Wireless:</strong> Bluetooth (3 Mac devices)</li><li><strong>Battery:</strong> 70 days (USB-C rechargeable)</li><li><strong>OS Tuning:</strong> macOS gestures, iCloud sync</li></ul>'],
            ['sku'=>'TH-PM-106','name'=>'Razer Pro Click Mini Wireless Mouse','brand'=>'Razer','category'=>'productivity-mice','price'=>79.00,'special_price'=>null,'weight'=>0.07,'stock'=>38,'new'=>0,'featured'=>0,'short_description'=>'Razer Pro Click Mini — silent productivity wireless mouse with 12K DPI, 4-device Bluetooth and compact build.','description'=>'<p>Pro Click Mini is Razer\'s office-focused mouse — no RGB, silent switches, compact form, and 4-device multi-pairing. The ultra-silent mechanical switches reduce noise by 90% versus standard mice while maintaining the precise tactile click feel professionals prefer over membrane alternatives.</p><ul><li><strong>Sensor:</strong> 12,000 DPI optical</li><li><strong>Switches:</strong> Silent mechanical</li><li><strong>Wireless:</strong> Bluetooth (4 devices) + 2.4 GHz dongle</li><li><strong>Battery:</strong> 725 hours (AA)</li><li><strong>Weight:</strong> 76g</li><li><strong>RGB:</strong> No</li></ul>'],
            ['sku'=>'TH-PM-107','name'=>'Microsoft Arc Mouse Bluetooth Foldable','brand'=>'Dell','category'=>'productivity-mice','price'=>79.00,'special_price'=>59.00,'weight'=>0.08,'stock'=>41,'new'=>0,'featured'=>0,'short_description'=>'Microsoft Arc Mouse — foldable flat-to-curved design with touch scroll strip and Bluetooth 4.1.','description'=>'<p>Arc Mouse folds completely flat for transport and snaps into a curved ergonomic shape during use — the physical snap signals the mouse to power on and pair. The touch scroll strip replaces a traditional scroll wheel with gesture-based scrolling. Weighs just 83g without batteries.</p><ul><li><strong>Design:</strong> Foldable flat/curved</li><li><strong>Scroll:</strong> Touch scroll strip</li><li><strong>Wireless:</strong> Bluetooth 4.1</li><li><strong>Battery:</strong> 6 months (2× AAA)</li><li><strong>Weight:</strong> 83g (without batteries)</li><li><strong>Compatibility:</strong> Windows / macOS</li></ul>'],
            ['sku'=>'TH-PM-108','name'=>'Logitech MX Ergo Plus Wireless Trackball','brand'=>'Logitech','category'=>'productivity-mice','price'=>129.00,'special_price'=>null,'weight'=>0.26,'stock'=>29,'new'=>0,'featured'=>0,'short_description'=>'Logitech MX Ergo Plus trackball — adjustable 0°/20° tilt, 2048 DPI and multi-device for wrist-pain sufferers.','description'=>'<p>MX Ergo Plus is the most ergonomic alternative to a mouse — the trackball stays stationary and you roll it with your thumb, eliminating the arm movement that causes RSI. The adjustable 20° tilt plate lets you position your hand between flat (like a mouse) and fully tilted for maximum natural posture.</p><ul><li><strong>Type:</strong> Trackball (thumb-controlled)</li><li><strong>DPI:</strong> 512–2,048 (2 levels, button toggle)</li><li><strong>Wireless:</strong> Bluetooth + Unifying USB receiver</li><li><strong>Battery:</strong> 4 months (rechargeable)</li><li><strong>Tilt:</strong> 0° / 20° adjustable</li><li><strong>Multi-device:</strong> Yes (2 devices)</li></ul>'],
        ];
    }
}
