<?php

namespace Database\Seeders\ProductData;

class NetworkingData
{
    public static function get(): array
    {
        return array_merge(
            self::wifiRouters(),
            self::meshSystems(),
            self::switches(),
        );
    }

    private static function wifiRouters(): array
    {
        return [
            ['sku'=>'TH-WR-001','name'=>'TP-Link Archer BE800 Wi-Fi 7 Router','brand'=>'TP-Link','category'=>'wifi-routers','price'=>499.00,'special_price'=>null,'weight'=>1.48,'stock'=>24,'new'=>1,'featured'=>1,'short_description'=>'TP-Link BE800 Wi-Fi 7 tri-band router — 19 Gbps combined, 2.5G WAN and 10G LAN ports.','description'=>'<p>Archer BE800 is one of the first consumer Wi-Fi 7 routers, supporting MLO (Multi-Link Operation) for simultaneous multi-band connections that dramatically reduce latency. The 10G LAN port future-proofs your wired backbone, while BE19000 aggregate speeds ensure bandwidth is never a bottleneck.</p><ul><li><strong>Wi-Fi Standard:</strong> Wi-Fi 7 (802.11be)</li><li><strong>Bands:</strong> Tri-band (2.4GHz + 5GHz + 6GHz)</li><li><strong>Aggregate Speed:</strong> BE19000 (up to 19 Gbps)</li><li><strong>WAN Port:</strong> 1× 2.5G</li><li><strong>LAN Ports:</strong> 1× 10G + 4× 1G</li><li><strong>USB:</strong> 1× USB 3.0</li><li><strong>Coverage:</strong> Up to 330 m²</li><li><strong>MLO:</strong> Yes (802.11be)</li></ul>'],
            ['sku'=>'TH-WR-002','name'=>'ASUS ROG Rapture GT-BE98 Wi-Fi 7 Gaming Router','brand'=>'ASUS','category'=>'wifi-routers','price'=>699.00,'special_price'=>null,'weight'=>1.68,'stock'=>12,'new'=>1,'featured'=>1,'short_description'=>'ASUS ROG Wi-Fi 7 gaming router with 2.5G + 10G multi-gig ports, AI-powered traffic prioritisation.','description'=>'<p>GT-BE98 is built for competitive gaming households. ASUS\'s GameFirst VI engine uses AI to detect gaming traffic and prioritise it over streaming and browsing — reducing in-game latency even when other household members are on Netflix. The 10G LAN port supports current and next-gen wired gaming equipment.</p><ul><li><strong>Wi-Fi Standard:</strong> Wi-Fi 7 (802.11be)</li><li><strong>Bands:</strong> Quad-band (2.4GHz + 5GHz + 5GHz + 6GHz)</li><li><strong>Aggregate Speed:</strong> BE98000</li><li><strong>WAN:</strong> 1× 10G + 1× 2.5G</li><li><strong>LAN:</strong> 4× 2.5G + 1× 10G</li><li><strong>Features:</strong> GameFirst VI, AiMesh, OFDMA, MU-MIMO</li></ul>'],
            ['sku'=>'TH-WR-003','name'=>'Netgear Nighthawk RS700S Wi-Fi 7 Router','brand'=>'Netgear','category'=>'wifi-routers','price'=>599.00,'special_price'=>null,'weight'=>1.22,'stock'=>9,'new'=>1,'featured'=>0,'short_description'=>'Netgear Nighthawk RS700S Wi-Fi 7 router with 19.3 Gbps speeds and 2.5G WAN for fibre homes.','description'=>'<p>Nighthawk RS700S delivers Wi-Fi 7 performance in Netgear\'s signature angular design. Optimised for multi-gig fibre connections, the 2.5G WAN port ensures you can take full advantage of 2.5 Gbps ISP plans without bottlenecking at the router. Armor cybersecurity subscription available for network-wide protection.</p><ul><li><strong>Wi-Fi Standard:</strong> Wi-Fi 7 (802.11be)</li><li><strong>Bands:</strong> Tri-band</li><li><strong>Aggregate Speed:</strong> BE19300</li><li><strong>WAN:</strong> 1× 2.5G</li><li><strong>LAN:</strong> 4× 1G + 1× 2.5G</li><li><strong>Security:</strong> WPA3, optional Netgear Armor</li></ul>'],
            ['sku'=>'TH-WR-004','name'=>'TP-Link Archer AXE300 Wi-Fi 6E Router','brand'=>'TP-Link','category'=>'wifi-routers','price'=>249.00,'special_price'=>199.00,'weight'=>0.89,'stock'=>38,'new'=>0,'featured'=>0,'short_description'=>'TP-Link AXE300 Wi-Fi 6E tri-band router with 6 GHz band and 2.5G WAN — best value Wi-Fi 6E router.','description'=>'<p>Archer AXE300 opens the 6 GHz Wi-Fi band to your home at an accessible price point. The 6 GHz band is cleaner and less congested than 2.4 GHz or 5 GHz, providing faster speeds and lower latency for compatible devices — including newer laptops, phones, and the PS5 and Xbox Series X.</p><ul><li><strong>Wi-Fi Standard:</strong> Wi-Fi 6E (802.11ax)</li><li><strong>Bands:</strong> Tri-band (2.4GHz + 5GHz + 6GHz)</li><li><strong>Aggregate Speed:</strong> AXE19000</li><li><strong>WAN:</strong> 1× 2.5G</li><li><strong>LAN:</strong> 4× 1G</li><li><strong>Coverage:</strong> Up to 280 m²</li></ul>'],
            ['sku'=>'TH-WR-005','name'=>'Ubiquiti UniFi Dream Router','brand'=>'Ubiquiti','category'=>'wifi-routers','price'=>199.00,'special_price'=>null,'weight'=>0.71,'stock'=>21,'new'=>0,'featured'=>0,'short_description'=>'Ubiquiti UniFi Dream Router — enterprise-grade Wi-Fi 6 with built-in UniFi controller for prosumer home networking.','description'=>'<p>UniFi Dream Router combines an enterprise-grade Wi-Fi 6 access point with a built-in UniFi Network controller, security gateway, and PoE switch in one device. For technically-minded users who want professional-grade visibility, VLAN segmentation, and precise traffic control without a rack full of equipment.</p><ul><li><strong>Wi-Fi Standard:</strong> Wi-Fi 6 (802.11ax)</li><li><strong>Bands:</strong> Dual-band (2.4GHz + 5GHz)</li><li><strong>WAN:</strong> 1× 1G (RJ45)</li><li><strong>LAN:</strong> 4× 1G (1× PoE out)</li><li><strong>Controller:</strong> UniFi OS built-in (no cloud key required)</li><li><strong>Features:</strong> IDS/IPS, DPI, VPN, VLAN, multiple SSIDs</li></ul>'],
            ['sku'=>'TH-WR-006','name'=>'TP-Link Archer AX73 Wi-Fi 6 Router','brand'=>'TP-Link','category'=>'wifi-routers','price'=>129.00,'special_price'=>99.00,'weight'=>0.80,'stock'=>53,'new'=>0,'featured'=>0,'short_description'=>'TP-Link AX5400 Wi-Fi 6 dual-band router — reliable high-speed Wi-Fi 6 at an entry-level price.','description'=>'<p>Archer AX73 is the pragmatic Wi-Fi 6 upgrade for homes that want faster speeds and reduced congestion without the cost of Wi-Fi 6E or Wi-Fi 7. OFDMA and MU-MIMO allow it to serve multiple devices simultaneously, ideal for households with many connected devices.</p><ul><li><strong>Wi-Fi Standard:</strong> Wi-Fi 6 (802.11ax)</li><li><strong>Bands:</strong> Dual-band (2.4GHz + 5GHz)</li><li><strong>Aggregate Speed:</strong> AX5400</li><li><strong>WAN:</strong> 1× Gigabit</li><li><strong>LAN:</strong> 4× Gigabit</li><li><strong>USB:</strong> 1× USB 3.0</li><li><strong>Coverage:</strong> Up to 230 m²</li></ul>'],
        ];
    }

    private static function meshSystems(): array
    {
        return [
            ['sku'=>'TH-MS-001','name'=>'TP-Link Deco XE75 Pro Wi-Fi 6E Mesh 3-Pack','brand'=>'TP-Link','category'=>'mesh-systems','price'=>399.00,'special_price'=>349.00,'weight'=>1.80,'stock'=>18,'new'=>1,'featured'=>1,'short_description'=>'TP-Link Deco XE75 Pro tri-band Wi-Fi 6E mesh system — 6 GHz backhaul delivers true whole-home coverage.','description'=>'<p>Deco XE75 Pro uses the 6 GHz band as a dedicated wireless backhaul, completely separating backhaul traffic from device traffic. This means the 5 GHz band can be fully dedicated to your devices without competition from the mesh backbone — delivering consistent gigabit speeds throughout a 680 m² home.</p><ul><li><strong>Coverage:</strong> Up to 680 m² (3-pack)</li><li><strong>Wi-Fi Standard:</strong> Wi-Fi 6E (802.11ax), tri-band</li><li><strong>Backhaul:</strong> Dedicated 6 GHz band</li><li><strong>Ports per node:</strong> 1× 2.5G WAN/LAN + 1× 1G LAN</li><li><strong>IoT Network:</strong> Separate IoT network support</li><li><strong>App:</strong> Deco app (iOS / Android)</li></ul>'],
            ['sku'=>'TH-MS-002','name'=>'Netgear Orbi RBK863S Wi-Fi 6E Mesh 3-Pack','brand'=>'Netgear','category'=>'mesh-systems','price'=>899.00,'special_price'=>null,'weight'=>3.60,'stock'=>7,'new'=>1,'featured'=>0,'short_description'=>'Netgear Orbi 960 Wi-Fi 6E quad-band mesh — 10.8 Gbps speeds for large homes and heavy users.','description'=>'<p>Orbi RBK863S is Netgear\'s premium quad-band Wi-Fi 6E mesh solution for large homes. The quad-band design allocates one 6 GHz band as a dedicated high-speed backhaul and another 6 GHz band for devices, ensuring all three radios are simultaneously available without interference.</p><ul><li><strong>Coverage:</strong> Up to 840 m² (3-pack)</li><li><strong>Wi-Fi Standard:</strong> Wi-Fi 6E (802.11ax), quad-band</li><li><strong>Aggregate Speed:</strong> BE10800</li><li><strong>Ports:</strong> 2.5G WAN + 4× 1G LAN per satellite</li><li><strong>Security:</strong> Armor by Bitdefender included</li></ul>'],
            ['sku'=>'TH-MS-003','name'=>'ASUS ZenWiFi Pro ET12 Wi-Fi 6E Mesh 2-Pack','brand'=>'ASUS','category'=>'mesh-systems','price'=>599.00,'special_price'=>null,'weight'=>2.40,'stock'=>11,'new'=>1,'featured'=>0,'short_description'=>'ASUS ZenWiFi Pro ET12 Wi-Fi 6E tri-band mesh with 2.5G multi-gig ports and AiMesh technology.','description'=>'<p>ZenWiFi Pro ET12 targets prosumer users who need both Wi-Fi 6E performance and advanced networking features (VPN, VLAN, parental controls, AiProtection Pro) in a mesh system. The 2.5G wired backhaul option ensures maximum performance in homes with pre-run ethernet.</p><ul><li><strong>Coverage:</strong> Up to 560 m² (2-pack)</li><li><strong>Wi-Fi Standard:</strong> Wi-Fi 6E (802.11ax), tri-band</li><li><strong>Ports:</strong> 1× 2.5G WAN + 1× 2.5G LAN + 1× 1G LAN per node</li><li><strong>Security:</strong> AiProtection Pro (lifetime, no subscription)</li><li><strong>App:</strong> ASUS Router app</li></ul>'],
            ['sku'=>'TH-MS-004','name'=>'TP-Link Deco BE65 Wi-Fi 7 Mesh 3-Pack','brand'=>'TP-Link','category'=>'mesh-systems','price'=>549.00,'special_price'=>null,'weight'=>2.10,'stock'=>9,'new'=>1,'featured'=>0,'short_description'=>'TP-Link Deco BE65 Wi-Fi 7 mesh system — MLO technology for ultra-low latency across whole home.','description'=>'<p>Deco BE65 brings Wi-Fi 7\'s MLO (Multi-Link Operation) technology to mesh networking. Each node can simultaneously transmit across multiple bands, improving reliability and reducing latency compared to Wi-Fi 6E. Ideal for households adopting Wi-Fi 7 devices like the latest iPhones, Samsung Galaxy S25, and Wi-Fi 7 laptops.</p><ul><li><strong>Coverage:</strong> Up to 600 m² (3-pack)</li><li><strong>Wi-Fi Standard:</strong> Wi-Fi 7 (802.11be), tri-band</li><li><strong>MLO:</strong> Yes</li><li><strong>Ports:</strong> 1× 2.5G + 1× 1G per node</li></ul>'],
            ['sku'=>'TH-MS-005','name'=>'Ubiquiti UniFi U6 Mesh (3-Pack)','brand'=>'Ubiquiti','category'=>'mesh-systems','price'=>369.00,'special_price'=>null,'weight'=>1.20,'stock'=>15,'new'=>0,'featured'=>0,'short_description'=>'Ubiquiti UniFi U6 Mesh access points — enterprise-grade Wi-Fi 6 APs for managed home and office networks.','description'=>'<p>UniFi U6 Mesh access points are ideal for users already running a UniFi gateway or Dream Machine. Each U6 Mesh AP delivers Wi-Fi 6 performance with up to 600 Mbps on 2.4 GHz and 4.8 Gbps on 5 GHz, manageable through the UniFi Network controller with per-SSID VLAN assignment.</p><ul><li><strong>Wi-Fi Standard:</strong> Wi-Fi 6 (802.11ax), dual-band</li><li><strong>2.4 GHz:</strong> 600 Mbps</li><li><strong>5 GHz:</strong> 4,804 Mbps</li><li><strong>PoE:</strong> 802.3af (48V)</li><li><strong>Management:</strong> UniFi Network controller</li><li><strong>Antenna:</strong> 4× 4 MU-MIMO</li></ul>'],
        ];
    }

    private static function switches(): array
    {
        return [
            ['sku'=>'TH-SW-001','name'=>'TP-Link TL-SG108 8-Port Gigabit Switch','brand'=>'TP-Link','category'=>'network-switches','price'=>24.00,'special_price'=>null,'weight'=>0.39,'stock'=>127,'new'=>0,'featured'=>0,'short_description'=>'TP-Link 8-port unmanaged gigabit switch — silent, plug-and-play desktop switch with fanless design.','description'=>'<p>TL-SG108 is the workhorse of home and small office wired networks. Eight gigabit ports, zero configuration, completely silent fanless operation, and a compact desktop form factor. QoS prioritises video streaming automatically without any setup.</p><ul><li><strong>Ports:</strong> 8× Gigabit RJ45</li><li><strong>Switching Capacity:</strong> 16 Gbps</li><li><strong>Forwarding Rate:</strong> 11.9 Mpps</li><li><strong>Power:</strong> External adapter</li><li><strong>Fanless:</strong> Yes</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-SW-002','name'=>'Netgear GS308PP 8-Port PoE+ Gigabit Switch','brand'=>'Netgear','category'=>'network-switches','price'=>79.00,'special_price'=>null,'weight'=>0.59,'stock'=>41,'new'=>0,'featured'=>0,'short_description'=>'Netgear ProSafe 8-port PoE+ unmanaged switch with 83W PoE budget — powers access points, IP cameras and VoIP.','description'=>'<p>GS308PP provides 83W of total PoE+ power across all 8 ports, making it practical for powering up to 4 access points, IP cameras, VoIP phones, or IoT devices without dedicated power supplies. All 8 ports support PoE+ (IEEE 802.3at) at up to 30W per port.</p><ul><li><strong>Ports:</strong> 8× Gigabit RJ45 with PoE+</li><li><strong>PoE Budget:</strong> 83W total</li><li><strong>PoE Standard:</strong> 802.3af/at (PoE/PoE+)</li><li><strong>Switching Capacity:</strong> 16 Gbps</li><li><strong>Fanless:</strong> Yes</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-SW-003','name'=>'TP-Link TL-SG2210P Managed 10-Port Switch','brand'=>'TP-Link','category'=>'network-switches','price'=>109.00,'special_price'=>null,'weight'=>0.90,'stock'=>29,'new'=>0,'featured'=>0,'short_description'=>'TP-Link 10-port managed smart switch with 8× PoE+ ports, 2× SFP uplinks and VLAN support.','description'=>'<p>TL-SG2210P bridges the gap between unmanaged and fully managed switching. Web-based management enables VLAN segmentation, port-based QoS, LACP trunking, and IGMP snooping — features that home lab enthusiasts and small businesses need without the complexity of enterprise switching.</p><ul><li><strong>Ports:</strong> 8× Gigabit PoE+ + 2× SFP</li><li><strong>PoE Budget:</strong> 61W total</li><li><strong>Management:</strong> Web GUI + SNMP</li><li><strong>VLAN:</strong> 802.1Q VLAN, port-based VLAN</li><li><strong>L2 Features:</strong> STP/RSTP, LACP, IGMP, QoS</li><li><strong>Warranty:</strong> Lifetime</li></ul>'],
            ['sku'=>'TH-SW-004','name'=>'Ubiquiti UniFi Switch Flex Mini 5-Port','brand'=>'Ubiquiti','category'=>'network-switches','price'=>29.00,'special_price'=>null,'weight'=>0.14,'stock'=>66,'new'=>0,'featured'=>0,'short_description'=>'Ubiquiti UniFi Flex Mini — compact 5-port USB-C powered managed switch for small desk deployments.','description'=>'<p>Flex Mini is UniFi\'s most compact managed switch, fitting anywhere a USB-C power source is available — ideal for small offices, conference rooms, and home office desk setups where a bulky switch would be impractical. Full VLAN support and UniFi controller management in a device smaller than a deck of cards.</p><ul><li><strong>Ports:</strong> 5× Gigabit RJ45 (1× PoE-in from upstream)</li><li><strong>Power:</strong> USB-C (5V/1A) or PoE from uplink</li><li><strong>Management:</strong> UniFi Network controller</li><li><strong>VLANs:</strong> 802.1Q</li><li><strong>Dimensions:</strong> 101 × 58 × 22 mm</li></ul>'],
        ];
    }
}
