<?php

namespace Database\Seeders\ProductData;

class PrinterData
{
    public static function get(): array
    {
        return array_merge(
            self::inkjetPrinters(),
            self::laserPrinters(),
        );
    }

    private static function inkjetPrinters(): array
    {
        return [
            ['sku'=>'TH-IP-001','name'=>'Canon PIXMA TS8370 All-in-One Inkjet Printer','brand'=>'Canon','category'=>'inkjet-printers','price'=>199.00,'special_price'=>149.00,'weight'=>6.40,'stock'=>31,'new'=>0,'featured'=>1,'short_description'=>'Canon PIXMA TS8370 — 6-colour Lucia system with photo lab quality prints, wireless and borderless up to A4.','description'=>'<p>PIXMA TS8370 uses Canon\'s 6-colour Lucia dye ink system to produce photo prints with 4800×1200 dpi that rival professional photo labs. The dedicated grey ink reduces metallic colour casts in black-and-white prints. CD/DVD disc printing support is built-in — useful for creating custom discs for presentations or media archives.</p><ul><li><strong>Print Resolution:</strong> 4800×1200 dpi</li><li><strong>Ink System:</strong> 6-colour Lucia (C, M, Y, Black, Grey, Photo Black)</li><li><strong>Borderless:</strong> Yes (up to A4)</li><li><strong>Functions:</strong> Print, Copy, Scan (all-in-one)</li><li><strong>Connectivity:</strong> Wi-Fi, USB, Bluetooth (for mobile)</li><li><strong>Special:</strong> CD/DVD disc printing</li><li><strong>Mobile:</strong> AirPrint, Google Cloud Print</li></ul>'],
            ['sku'=>'TH-IP-002','name'=>'Epson EcoTank ET-4850 All-in-One Ink Tank','brand'=>'Epson','category'=>'inkjet-printers','price'=>399.00,'special_price'=>349.00,'weight'=>6.60,'stock'=>24,'new'=>1,'featured'=>1,'short_description'=>'Epson EcoTank ET-4850 — refillable ink tanks for up to 2 years of printing without new cartridges.','description'=>'<p>EcoTank ET-4850 eliminates expensive cartridge replacements with refillable ink tanks. Each set of bottles included in the box contains enough ink for approximately 7,500 black pages and 5,500 colour pages — roughly 2 years of typical home office use. The per-page cost drops to pennies versus cartridge-based printers.</p><ul><li><strong>Print System:</strong> EcoTank refillable ink tanks</li><li><strong>Ink Included:</strong> ~7,500 black / ~5,500 colour pages per bottle set</li><li><strong>Functions:</strong> Print, Copy, Scan, Fax (all-in-one)</li><li><strong>ADF:</strong> 30-sheet auto document feeder</li><li><strong>Connectivity:</strong> Wi-Fi, Wi-Fi Direct, USB, Ethernet</li><li><strong>Mobile:</strong> AirPrint, Google Cloud Print, Epson Connect</li></ul>'],
            ['sku'=>'TH-IP-003','name'=>'Canon PIXMA MG3620 Wireless All-in-One','brand'=>'Canon','category'=>'inkjet-printers','price'=>69.00,'special_price'=>49.00,'weight'=>4.30,'stock'=>68,'new'=>0,'featured'=>0,'short_description'=>'Canon PIXMA MG3620 — budget wireless inkjet for basic home printing with AirPrint and Google Cloud Print.','description'=>'<p>PIXMA MG3620 is the practical choice for households that print occasionally — documents, shipping labels, and occasional photos. Auto-duplex printing saves paper for multi-page documents, and wireless printing from phone or laptop works without installing drivers via AirPrint or Google Cloud Print.</p><ul><li><strong>Print Resolution:</strong> 4800×1200 dpi</li><li><strong>Functions:</strong> Print, Copy, Scan</li><li><strong>Duplex:</strong> Auto duplex print</li><li><strong>Connectivity:</strong> Wi-Fi, USB</li><li><strong>Mobile:</strong> AirPrint, Google Cloud Print</li></ul>'],
            ['sku'=>'TH-IP-004','name'=>'Epson WorkForce WF-7840 Wide-Format All-in-One','brand'=>'Epson','category'=>'inkjet-printers','price'=>349.00,'special_price'=>null,'weight'=>17.30,'stock'=>11,'new'=>0,'featured'=>0,'short_description'=>'Epson WorkForce WF-7840 — A3+ wide-format inkjet with ADF, fax and fast duplex printing.','description'=>'<p>WF-7840 handles wide-format printing up to A3+ (13×19 inches) for architects, photographers, and small businesses needing oversized prints. The 35-sheet auto document feeder enables unattended multi-page copying and scanning of contracts and reports. Prints professional quality photo prints up to 13×19 inches without borders.</p><ul><li><strong>Max Print Width:</strong> A3+ (13×19 inches)</li><li><strong>Functions:</strong> Print, Copy, Scan, Fax</li><li><strong>ADF:</strong> 35-sheet auto document feeder</li><li><strong>Duplex:</strong> Auto duplex (all functions)</li><li><strong>Connectivity:</strong> Wi-Fi, Ethernet, USB</li></ul>'],
            ['sku'=>'TH-IP-005','name'=>'Canon MAXIFY GX6020 MegaTank Business Printer','brand'=>'Canon','category'=>'inkjet-printers','price'=>299.00,'special_price'=>null,'weight'=>7.00,'stock'=>18,'new'=>1,'featured'=>0,'short_description'=>'Canon MAXIFY GX6020 — megatank refillable ink, 6000 black/14000 colour pages, business inkjet speed.','description'=>'<p>MAXIFY GX6020 is Canon\'s business-focused megatank printer, printing at 24ipm in black — significantly faster than consumer inkjets. The pigment-based inks produce sharp, water-resistant text ideal for contracts, invoices, and business documents. Each refill bottle set produces up to 6,000 black and 14,000 colour pages.</p><ul><li><strong>Print Speed:</strong> 24 ipm (black) / 15.5 ipm (colour)</li><li><strong>Ink System:</strong> MegaTank refillable (pigment)</li><li><strong>Yield:</strong> ~6,000 black / ~14,000 colour pages per refill</li><li><strong>Functions:</strong> Print, Copy, Scan</li><li><strong>ADF:</strong> 50-sheet ADF</li><li><strong>Connectivity:</strong> Wi-Fi, USB, Ethernet</li></ul>'],
            ['sku'=>'TH-IP-006','name'=>'Epson SureColor P700 13" Photo Printer','brand'=>'Epson','category'=>'inkjet-printers','price'=>799.00,'special_price'=>null,'weight'=>9.90,'stock'=>7,'new'=>0,'featured'=>0,'short_description'=>'Epson SureColor P700 13" — 10-colour UltraChrome Pro10 pigment ink for museum-quality photo prints.','description'=>'<p>SureColor P700 is a professional photo printer for photographers, fine art printers, and print studios. The 10-colour UltraChrome Pro10 pigment ink set includes Violet and Green for a wider gamut than standard CMYK printers can achieve — covering 99% of the Pantone colour space. Prints archival-quality photos rated to 200+ years of display life.</p><ul><li><strong>Max Print Width:</strong> 13 inches</li><li><strong>Ink System:</strong> 10-colour UltraChrome Pro10 pigment</li><li><strong>Print Quality:</strong> 5760×1440 dpi</li><li><strong>Media:</strong> Fine art media, canvas, metallic, CD/DVD</li><li><strong>Connectivity:</strong> USB, Wi-Fi, Ethernet</li><li><strong>Archival Life:</strong> 200+ years (display life)</li></ul>'],
        ];
    }

    private static function laserPrinters(): array
    {
        return [
            ['sku'=>'TH-LP-001','name'=>'HP LaserJet Pro M404dn Monochrome Printer','brand'=>'HP','category'=>'laser-printers','price'=>329.00,'special_price'=>null,'weight'=>8.50,'stock'=>27,'new'=>0,'featured'=>1,'short_description'=>'HP LaserJet Pro M404dn — 40ppm monochrome laser, auto duplex, Ethernet and 250-sheet tray for offices.','description'=>'<p>LaserJet Pro M404dn is the workhorse of small office laser printing — 40 pages per minute, automatic duplex, and an Ethernet port for shared network access. HP\'s JetIntelligence toner cartridges include a chip that enables precise toner-level monitoring and genuine HP authentication. First-page-out time of 5.4 seconds keeps productivity high.</p><ul><li><strong>Technology:</strong> Monochrome laser</li><li><strong>Print Speed:</strong> 40 ppm</li><li><strong>First Page:</strong> 5.4 seconds</li><li><strong>Duplex:</strong> Automatic</li><li><strong>Paper Tray:</strong> 250 sheets</li><li><strong>Connectivity:</strong> USB, Ethernet</li><li><strong>Monthly Duty Cycle:</strong> Up to 80,000 pages</li></ul>'],
            ['sku'=>'TH-LP-002','name'=>'Brother HL-L8360CDW Colour Laser Printer','brand'=>'Brother','category'=>'laser-printers','price'=>399.00,'special_price'=>349.00,'weight'=>21.40,'stock'=>19,'new'=>0,'featured'=>0,'short_description'=>'Brother HL-L8360CDW — 33ppm colour laser, duplex, wireless and 250-sheet tray for small business colour printing.','description'=>'<p>HL-L8360CDW delivers sharp colour laser output for presentations, marketing materials, and reports at 33 pages per minute. Brother\'s high-yield replacement toners reduce per-page costs significantly versus entry-level colour lasers. Mobile printing via AirPrint, Google Cloud Print, and Brother\'s iPrint&Scan app provides wireless convenience.</p><ul><li><strong>Technology:</strong> Colour laser</li><li><strong>Print Speed:</strong> 33 ppm (colour and mono)</li><li><strong>Print Quality:</strong> 2400×600 dpi</li><li><strong>Duplex:</strong> Automatic</li><li><strong>Paper Tray:</strong> 250 sheets</li><li><strong>Connectivity:</strong> Wi-Fi, USB, Ethernet</li><li><strong>Mobile:</strong> AirPrint, Google Cloud Print</li></ul>'],
            ['sku'=>'TH-LP-003','name'=>'HP LaserJet MFP M236sdw All-in-One Laser','brand'=>'HP','category'=>'laser-printers','price'=>199.00,'special_price'=>169.00,'weight'=>7.80,'stock'=>44,'new'=>0,'featured'=>0,'short_description'=>'HP LaserJet MFP M236sdw — compact monochrome laser all-in-one with wireless, duplex and flatbed scanner.','description'=>'<p>LaserJet MFP M236sdw is HP\'s compact laser all-in-one for home offices and small teams. The flatbed scanner copies and scans documents at 1200dpi, while auto duplex printing reduces paper consumption for multi-page documents. HP Instant Ink subscription compatibility enables predictable monthly supply costs.</p><ul><li><strong>Functions:</strong> Print, Copy, Scan</li><li><strong>Technology:</strong> Monochrome laser</li><li><strong>Print Speed:</strong> 20 ppm</li><li><strong>Duplex:</strong> Automatic</li><li><strong>Scan Resolution:</strong> Up to 1200 dpi</li><li><strong>Connectivity:</strong> Wi-Fi, USB</li></ul>'],
            ['sku'=>'TH-LP-004','name'=>'Brother MFC-L8900CDW Colour Laser All-in-One','brand'=>'Brother','category'=>'laser-printers','price'=>599.00,'special_price'=>null,'weight'=>26.80,'stock'=>11,'new'=>0,'featured'=>0,'short_description'=>'Brother MFC-L8900CDW — colour laser all-in-one with 50-sheet ADF, fax and NFC tap-to-print.','description'=>'<p>MFC-L8900CDW is Brother\'s premium colour laser all-in-one for medium-sized offices. The 50-sheet auto document feeder handles contracts, tax returns, and reports hands-free. NFC tap-to-print lets compatible phones print by touching the printer\'s NFC tag — no app or pairing setup required.</p><ul><li><strong>Functions:</strong> Print, Copy, Scan, Fax</li><li><strong>Speed:</strong> 33 ppm colour + mono</li><li><strong>ADF:</strong> 50-sheet auto document feeder</li><li><strong>Duplex:</strong> Automatic (all functions)</li><li><strong>NFC:</strong> Tap-to-print</li><li><strong>Connectivity:</strong> Wi-Fi, USB, Ethernet, NFC</li></ul>'],
            ['sku'=>'TH-LP-005','name'=>'HP LaserJet Enterprise M507dn High-Volume','brand'=>'HP','category'=>'laser-printers','price'=>599.00,'special_price'=>null,'weight'=>12.70,'stock'=>9,'new'=>0,'featured'=>0,'short_description'=>'HP LaserJet Enterprise M507dn — 45ppm, 250K monthly duty cycle and HP Security features for enterprise printing.','description'=>'<p>LaserJet Enterprise M507dn is designed for high-volume enterprise environments — up to 250,000 pages per month duty cycle with enterprise security features including McAfee Embedded Control and HP Sure Start to prevent firmware tampering. The standard 550-sheet tray reduces refill interruptions in busy environments.</p><ul><li><strong>Speed:</strong> 45 ppm</li><li><strong>Monthly Duty Cycle:</strong> 250,000 pages</li><li><strong>Paper Capacity:</strong> 550-sheet main tray</li><li><strong>Security:</strong> McAfee Embedded Control, HP Sure Start</li><li><strong>Connectivity:</strong> USB, Gigabit Ethernet</li></ul>'],
            ['sku'=>'TH-LP-006','name'=>'Brother HL-L3270CDW Compact Colour Laser','brand'=>'Brother','category'=>'laser-printers','price'=>299.00,'special_price'=>249.00,'weight'=>15.90,'stock'=>34,'new'=>0,'featured'=>0,'short_description'=>'Brother HL-L3270CDW — compact wireless colour laser with 25ppm speed and wireless direct printing.','description'=>'<p>HL-L3270CDW is Brother\'s most compact wireless colour laser, suitable for small offices with limited counter space. Wireless Direct printing lets you connect smartphones and tablets to the printer\'s own Wi-Fi network without a separate router — useful for presentations in meeting rooms without IT access.</p><ul><li><strong>Speed:</strong> 25 ppm (colour and mono)</li><li><strong>Duplex:</strong> Automatic</li><li><strong>Wireless Direct:</strong> Yes (printer as hotspot)</li><li><strong>Connectivity:</strong> Wi-Fi, USB, Ethernet</li><li><strong>Mobile:</strong> AirPrint, Google Cloud Print</li></ul>'],
        ];
    }
}
