<?php

namespace Database\Seeders\ProductData;

class SmartHomeData
{
    public static function get(): array
    {
        return array_merge(
            self::smartSpeakers(),
            self::smartLighting(),
            self::securityCameras(),
        );
    }

    private static function smartSpeakers(): array
    {
        return [
            ['sku'=>'TH-SS-001','name'=>'Amazon Echo Show 10 (3rd Gen)','brand'=>'Philips','category'=>'smart-speakers','price'=>249.00,'special_price'=>199.00,'weight'=>2.57,'stock'=>44,'new'=>0,'featured'=>1,'short_description'=>'Amazon Echo Show 10 — 10.1" HD display that automatically turns to face you, with Alexa and Zigbee hub built in.','description'=>'<p>Echo Show 10 brings intelligent motion tracking to the smart display category — the 10.1" display automatically rotates to face you as you move around the kitchen or living room. The built-in Zigbee/Thread/Matter smart home hub controls compatible lights, locks, sensors and cameras without an additional bridge.</p><ul><li><strong>Display:</strong> 10.1" HD (1280×800)</li><li><strong>Motion:</strong> Motorised, follows you automatically</li><li><strong>Speaker:</strong> 3-inch woofer + 2× 1-inch tweeters</li><li><strong>Camera:</strong> 13MP for video calls</li><li><strong>Smart Home:</strong> Zigbee, Thread, Matter built-in hub</li><li><strong>Assistant:</strong> Alexa</li></ul>'],
            ['sku'=>'TH-SS-002','name'=>'Apple HomePod (2nd Gen)','brand'=>'Apple','category'=>'smart-speakers','price'=>299.00,'special_price'=>null,'weight'=>2.30,'stock'=>31,'new'=>1,'featured'=>1,'short_description'=>'Apple HomePod 2nd gen — 360° spatial audio, S9 chip, temperature/humidity sensor and Thread border router.','description'=>'<p>HomePod 2nd gen is the best smart speaker for Apple households, offering Spatial Audio computed in real time by the S9 chip. It also serves as a Thread border router for HomeKit accessories and includes a built-in temperature/humidity sensor that can trigger automations. Pair two for a stereo home cinema setup.</p><ul><li><strong>Chip:</strong> Apple S9</li><li><strong>Driver:</strong> High-excursion woofer + 5× tweeters</li><li><strong>Spatial Audio:</strong> Yes, room sensing</li><li><strong>Smart Home:</strong> Thread border router, Matter, HomeKit</li><li><strong>Sensor:</strong> Temperature + humidity built-in</li><li><strong>Assistant:</strong> Siri</li></ul>'],
            ['sku'=>'TH-SS-003','name'=>'Google Nest Hub Max (2nd Gen)','brand'=>'Philips','category'=>'smart-speakers','price'=>229.00,'special_price'=>179.00,'weight'=>0.96,'stock'=>38,'new'=>0,'featured'=>0,'short_description'=>'Google Nest Hub Max — 10" display, face recognition, 6.5MP camera and Google Home hub controller.','description'=>'<p>Nest Hub Max is the central controller for Google Home ecosystems. The 10" display with Face Match recognises family members individually, showing personalised content and answering questions based on who is standing in front of it. The 6.5MP camera doubles as a home security camera when you\'re away.</p><ul><li><strong>Display:</strong> 10" full-colour LCD</li><li><strong>Speaker:</strong> 18W stereo (3" woofer + 2× tweeters)</li><li><strong>Camera:</strong> 6.5MP with face recognition</li><li><strong>Smart Home:</strong> Google Home hub, Thread, Matter</li><li><strong>Features:</strong> Face Match, Quick Gestures</li><li><strong>Assistant:</strong> Google Assistant</li></ul>'],
            ['sku'=>'TH-SS-004','name'=>'Amazon Echo Dot (5th Gen) with Clock','brand'=>'Philips','category'=>'smart-speakers','price'=>59.00,'special_price'=>null,'weight'=>0.30,'stock'=>92,'new'=>1,'featured'=>0,'short_description'=>'Amazon Echo Dot 5th gen with clock display — compact Alexa speaker with LED clock and motion sensor.','description'=>'<p>Echo Dot 5th gen adds a front-facing LED display that shows time and temperature to the compact spherical design. The new motion sensor detects when you enter a room and can trigger automations or start playing music automatically. Sound quality is improved 40% over the 4th gen with a larger speaker driver.</p><ul><li><strong>Speaker:</strong> 1.73" full-range driver</li><li><strong>Display:</strong> LED clock with time, temperature, alarms</li><li><strong>Sensor:</strong> Motion detection</li><li><strong>Smart Home:</strong> Alexa Guard, Eero built-in</li><li><strong>Assistant:</strong> Alexa</li></ul>'],
            ['sku'=>'TH-SS-005','name'=>'Apple HomePod Mini','brand'=>'Apple','category'=>'smart-speakers','price'=>99.00,'special_price'=>null,'weight'=>0.34,'stock'=>67,'new'=>0,'featured'=>0,'short_description'=>'Apple HomePod Mini — S5 chip, 360° audio and Thread border router in a small, affordable package.','description'=>'<p>HomePod Mini brings Apple\'s acoustic engineering to a compact spherical design. Computational audio with the S5 chip analyses room acoustics in real time. As a Thread border router, it enables local control of Matter and HomeKit accessories. Handoff with iPhone lets you seamlessly transfer phone calls and music to HomePod Mini.</p><ul><li><strong>Chip:</strong> Apple S5</li><li><strong>Driver:</strong> Full-range driver + passive radiators</li><li><strong>Smart Home:</strong> Thread border router, Matter, HomeKit</li><li><strong>Handoff:</strong> iPhone handoff for calls and audio</li><li><strong>Assistant:</strong> Siri</li><li><strong>Colour:</strong> Midnight, White, Yellow, Orange, Blue</li></ul>'],
        ];
    }

    private static function smartLighting(): array
    {
        return [
            ['sku'=>'TH-SL-001','name'=>'Philips Hue White & Colour Ambiance Starter Kit (3 Bulbs + Hub)','brand'=>'Philips','category'=>'smart-lighting','price'=>199.00,'special_price'=>169.00,'weight'=>0.90,'stock'=>47,'new'=>0,'featured'=>1,'short_description'=>'Philips Hue starter kit with 3 colour bulbs and Hue Bridge — the gold standard smart lighting ecosystem.','description'=>'<p>Philips Hue is the most mature smart lighting ecosystem, compatible with Alexa, Google Home, Apple HomeKit, and Matter. This starter kit includes 3 E27 White & Colour Ambiance bulbs (16M colours) and a Hue Bridge for local processing. Expand with 400+ Hue accessories from light strips to outdoor fixtures.</p><ul><li><strong>Includes:</strong> 3× A19 E27 Colour Ambiance bulbs + Hue Bridge</li><li><strong>Colours:</strong> 16 million (full RGB + warm/cool white)</li><li><strong>Protocol:</strong> Zigbee, Matter</li><li><strong>Compatibility:</strong> Alexa, Google Home, HomeKit, SmartThings</li><li><strong>Max Brightness:</strong> 800 lm per bulb</li></ul>'],
            ['sku'=>'TH-SL-002','name'=>'Govee RGBICWW LED Strip Lights 10m (Matter)','brand'=>'Philips','category'=>'smart-lighting','price'=>49.00,'special_price'=>39.00,'weight'=>0.42,'stock'=>83,'new'=>1,'featured'=>0,'short_description'=>'Govee 10m RGBICWW LED strip with Matter support — segment-addressable for room and bias lighting.','description'=>'<p>Govee\'s RGBICWW strip lights support individual LED segment control — you can show a gradient, a chasing rainbow, or different colours in each segment. Matter protocol ensures compatibility with Apple Home, Google Home, Alexa, and SmartThings without any Govee account required. Ideal for TV bias lighting, under-desk accent, or cabinet lighting.</p><ul><li><strong>Length:</strong> 10 metres (cuttable every 3 LEDs)</li><li><strong>LEDs:</strong> RGBICWW (RGB + warm + cool white)</li><li><strong>Addressable:</strong> Yes (segment control)</li><li><strong>Protocol:</strong> Wi-Fi 2.4 GHz, Matter</li><li><strong>Brightness:</strong> Up to 1300 lm</li></ul>'],
            ['sku'=>'TH-SL-003','name'=>'Philips Hue Gradient Signe Floor Lamp','brand'=>'Philips','category'=>'smart-lighting','price'=>249.00,'special_price'=>null,'weight'=>2.50,'stock'=>22,'new'=>1,'featured'=>0,'short_description'=>'Philips Hue Gradient Signe Floor Lamp — gradient RGB floor lamp with Hue Entertainment TV sync.','description'=>'<p>Signe Gradient Floor Lamp creates a flowing gradient of colours from bottom to top, controllable per zone via the Hue app. With Hue Sync, it mirrors the dominant colours on your TV screen in real time — widening your field of view and making movies and games more immersive. No Hue Bridge needed for basic control via Bluetooth.</p><ul><li><strong>Height:</strong> 135cm</li><li><strong>Zones:</strong> 3 independently controlled gradient zones</li><li><strong>Protocol:</strong> Zigbee + Bluetooth (bridge optional)</li><li><strong>Entertainment:</strong> Hue Sync for PC/Mac screen mirroring</li><li><strong>Compatibility:</strong> Alexa, Google Home, HomeKit</li></ul>'],
            ['sku'=>'TH-SL-004','name'=>'Ring Smart Lighting Step Lights (4-Pack, Battery)','brand'=>'Ring','category'=>'smart-lighting','price'=>79.00,'special_price'=>null,'weight'=>1.20,'stock'=>51,'new'=>0,'featured'=>0,'short_description'=>'Ring Solar Step Lights 4-pack — wireless, weather-resistant outdoor stair lights with Ring Bridge control.','description'=>'<p>Ring Step Lights install without any wiring — battery-powered and weather-resistant, they mount to steps, posts, or walls and integrate with the Ring ecosystem. Motion-triggered lighting can be coordinated with Ring cameras and doorbells for a complete outdoor security lighting setup.</p><ul><li><strong>Power:</strong> Battery (weather-resistant, IP65)</li><li><strong>Trigger:</strong> Motion-activated</li><li><strong>Protocol:</strong> Z-Wave via Ring Bridge (included)</li><li><strong>Integration:</strong> Ring app, Alexa</li><li><strong>Includes:</strong> 4× step lights + Ring Bridge</li></ul>'],
            ['sku'=>'TH-SL-005','name'=>'Nanoleaf Lines Starter Kit (9 Lines)','brand'=>'Philips','category'=>'smart-lighting','price'=>199.00,'special_price'=>179.00,'weight'=>0.90,'stock'=>29,'new'=>0,'featured'=>0,'short_description'=>'Nanoleaf Lines 9-pack — modular RGB light bars for geometric wall art with music sync and Matter support.','description'=>'<p>Nanoleaf Lines are modular light bars that connect at 60° and 150° angles to form geometric patterns on your wall. Each segment is independently addressable for ripple, gradient, and reactive effects. Music visualisation mode pulses and shifts colours in real time to the beat of any audio source in the room.</p><ul><li><strong>Lines:</strong> 9× 59cm RGB segments</li><li><strong>Connection:</strong> 60° and 150° connectors</li><li><strong>Effects:</strong> Music Visualizer, Screen Mirror, Rhythms</li><li><strong>Protocol:</strong> Wi-Fi 2.4 GHz, Matter, Thread</li><li><strong>Compatibility:</strong> Alexa, Google Home, HomeKit</li></ul>'],
        ];
    }

    private static function securityCameras(): array
    {
        return [
            ['sku'=>'TH-SC-001','name'=>'Arlo Pro 5S 2K Outdoor Camera (2-Pack)','brand'=>'Arlo','category'=>'security-cameras','price'=>299.00,'special_price'=>249.00,'weight'=>0.53,'stock'=>36,'new'=>1,'featured'=>1,'short_description'=>'Arlo Pro 5S 2K outdoor wireless camera 2-pack — integrated spotlight, colour night vision and 3-month battery.','description'=>'<p>Arlo Pro 5S 2K delivers wire-free outdoor security with colour 2K video and an integrated spotlight. Dual-band Wi-Fi connects directly to your router without a hub. Arlo\'s CVR (Continuous Video Recording) subscription captures footage even between motion events — useful for post-incident review.</p><ul><li><strong>Resolution:</strong> 2K HDR (2560×1440)</li><li><strong>Night Vision:</strong> Colour with integrated spotlight</li><li><strong>Wireless:</strong> Wi-Fi 6 dual-band (direct, no hub)</li><li><strong>Battery:</strong> Up to 3 months</li><li><strong>Detection:</strong> AI-powered person, vehicle, package, animal</li><li><strong>Storage:</strong> Local microSD + optional Arlo Secure cloud</li></ul>'],
            ['sku'=>'TH-SC-002','name'=>'Ring Floodlight Cam Wired Pro','brand'=>'Ring','category'=>'security-cameras','price'=>249.00,'special_price'=>null,'weight'=>1.08,'stock'=>28,'new'=>1,'featured'=>0,'short_description'=>'Ring Floodlight Cam Wired Pro — 3D motion detection, 1080p HDR video, dual 3000-lumen floodlights.','description'=>'<p>Floodlight Cam Wired Pro adds 3D Motion Detection — using radar to determine a person\'s exact position, distance, and direction rather than simple passive infrared. The dual 3000-lumen LED floodlights can be aimed independently, illuminating specific areas of your property rather than flooding the entire scene.</p><ul><li><strong>Resolution:</strong> 1080p HDR</li><li><strong>Floodlights:</strong> 2× 1500 lm (3000 lm total), independently aimed</li><li><strong>Detection:</strong> 3D Motion Radar (position, distance, direction)</li><li><strong>Power:</strong> Wired 110–240V</li><li><strong>Audio:</strong> Two-way audio + siren</li><li><strong>Integration:</strong> Alexa, Google Home</li></ul>'],
            ['sku'=>'TH-SC-003','name'=>'Arlo Essential Indoor 2K Camera','brand'=>'Arlo','category'=>'security-cameras','price'=>79.00,'special_price'=>null,'weight'=>0.09,'stock'=>53,'new'=>0,'featured'=>0,'short_description'=>'Arlo Essential Indoor 2K camera — automated privacy shield, pet and baby monitoring without subscription.','description'=>'<p>Essential Indoor 2K is one of the few home security cameras with a built-in automated privacy shield — a physical lens cover that slides closed when you are home and open when you leave, providing genuine privacy assurance rather than just software-based privacy modes. Free 30-day cloud storage included.</p><ul><li><strong>Resolution:</strong> 2K (2560×1440)</li><li><strong>Privacy Shield:</strong> Automated physical lens cover</li><li><strong>Night Vision:</strong> Colour (infrared + ambient light boost)</li><li><strong>Audio:</strong> Two-way audio</li><li><strong>Storage:</strong> 30 days free cloud + optional local</li><li><strong>Connection:</strong> 2.4 GHz Wi-Fi</li></ul>'],
            ['sku'=>'TH-SC-004','name'=>'Ring Video Doorbell 4','brand'=>'Ring','category'=>'security-cameras','price'=>149.00,'special_price'=>null,'weight'=>0.23,'stock'=>61,'new'=>0,'featured'=>0,'short_description'=>'Ring Video Doorbell 4 — 1080p HD, colour pre-roll, improved night vision and quick-release battery.','description'=>'<p>Ring Video Doorbell 4 introduces colour Pre-Roll — it captures 4 seconds of full-colour video before motion is triggered, giving you context about what was happening before the alert fired. The quick-release battery can be charged externally without removing the doorbell from the mounting bracket.</p><ul><li><strong>Resolution:</strong> 1080p HD</li><li><strong>Pre-Roll:</strong> 4 seconds colour video before motion alert</li><li><strong>Night Vision:</strong> Colour enhanced</li><li><strong>Power:</strong> Battery (quick-release) or hardwired</li><li><strong>Audio:</strong> Two-way audio + noise cancellation</li><li><strong>Integration:</strong> Alexa, Google Home</li></ul>'],
            ['sku'=>'TH-SC-005','name'=>'Arlo Ultra 2 4K Outdoor Security Camera','brand'=>'Arlo','category'=>'security-cameras','price'=>349.00,'special_price'=>null,'weight'=>0.60,'stock'=>17,'new'=>0,'featured'=>0,'short_description'=>'Arlo Ultra 2 4K outdoor camera — integrated spotlight, 180° view and dual-band Wi-Fi with SmartHub.','description'=>'<p>Arlo Ultra 2 is the highest-resolution wire-free security camera in the consumer market at 4K resolution. The 180° wide-angle lens captures the full width of driveways, porches, and entries without blind spots. Local storage via the Arlo SmartHub eliminates cloud dependency for privacy-conscious users.</p><ul><li><strong>Resolution:</strong> 4K HDR (3840×2160)</li><li><strong>Field of View:</strong> 180° diagonal</li><li><strong>Night Vision:</strong> Colour with integrated spotlight</li><li><strong>Wi-Fi:</strong> Dual-band 2.4/5 GHz via SmartHub</li><li><strong>Storage:</strong> Local SmartHub + optional Arlo Secure cloud</li><li><strong>Battery:</strong> Up to 6 months</li></ul>'],
        ];
    }
}
