<?php

namespace Database\Seeders\ProductData;

class StorageData
{
    public static function get(): array
    {
        return array_merge(
            self::nvmeSsds(),
            self::sataSsds(),
            self::portableSsds(),
            self::hardDrives(),
        );
    }

    private static function nvmeSsds(): array
    {
        return [
            ['sku'=>'TH-NV-001','name'=>'Samsung 990 Pro 2TB NVMe M.2 SSD','brand'=>'Samsung','category'=>'nvme-ssds','price'=>179.00,'special_price'=>149.00,'weight'=>0.01,'stock'=>84,'new'=>1,'featured'=>1,'short_description'=>'Samsung 990 Pro 2TB with 7450 MB/s sequential read — the fastest Gen 4 consumer SSD.','description'=>'<p>Samsung 990 Pro Gen 4 NVMe SSD delivers 7450 MB/s sequential reads and 6900 MB/s writes — near the theoretical ceiling of PCIe 4.0 x4. The sixth-generation V-NAND and enhanced controller keep temperatures low under sustained workloads, making it ideal for gaming and content creation.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> PCIe 4.0 x4, NVMe 2.0</li><li><strong>Sequential Read:</strong> 7,450 MB/s</li><li><strong>Sequential Write:</strong> 6,900 MB/s</li><li><strong>Random Read:</strong> 1,400K IOPS</li><li><strong>NAND:</strong> Samsung V-NAND TLC (6th gen)</li><li><strong>TBW:</strong> 1,200 TBW</li><li><strong>Form Factor:</strong> M.2 2280</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-NV-002','name'=>'WD Black SN850X 1TB NVMe SSD','brand'=>'WD','category'=>'nvme-ssds','price'=>99.00,'special_price'=>null,'weight'=>0.01,'stock'=>67,'new'=>0,'featured'=>0,'short_description'=>'WD Black 1TB SN850X with 7300 MB/s reads and optional heatsink — the gamer\'s PCIe 4.0 SSD.','description'=>'<p>WD Black SN850X is purpose-built for PC gaming. The SSD is compatible with the PS5, and WD\'s SN850X firmware includes game-mode acceleration that analyses the file system to pre-position data closer to the read heads — delivering up to 20% faster game loading times versus the original SN850.</p><ul><li><strong>Capacity:</strong> 1TB</li><li><strong>Interface:</strong> PCIe 4.0 x4, NVMe 2.0</li><li><strong>Sequential Read:</strong> 7,300 MB/s</li><li><strong>Sequential Write:</strong> 6,300 MB/s</li><li><strong>NAND:</strong> WD TLC 3D NAND</li><li><strong>TBW:</strong> 600 TBW</li><li><strong>Form Factor:</strong> M.2 2280</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-NV-003','name'=>'Crucial T700 2TB PCIe 5.0 NVMe SSD','brand'=>'Crucial','category'=>'nvme-ssds','price'=>249.00,'special_price'=>null,'weight'=>0.01,'stock'=>31,'new'=>1,'featured'=>1,'short_description'=>'Crucial T700 — first consumer PCIe 5.0 SSD, delivering 12,400 MB/s sequential read speeds.','description'=>'<p>Crucial T700 is among the first consumer-grade PCIe 5.0 NVMe SSDs. On a PCIe 5.0-capable motherboard (Intel 13th/14th Gen or AMD Ryzen 7000), it achieves sequential reads of 12,400 MB/s — nearly 2× faster than the best Gen 4 drives. A heatsink is required due to higher operating temperatures.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> PCIe 5.0 x4, NVMe 2.0</li><li><strong>Sequential Read:</strong> 12,400 MB/s</li><li><strong>Sequential Write:</strong> 11,800 MB/s</li><li><strong>NAND:</strong> Micron 232L TLC 3D NAND</li><li><strong>TBW:</strong> 1,200 TBW</li><li><strong>Form Factor:</strong> M.2 2280 (heatsink version available)</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-NV-004','name'=>'Kingston Fury Renegade 1TB NVMe SSD','brand'=>'Kingston','category'=>'nvme-ssds','price'=>89.00,'special_price'=>79.00,'weight'=>0.01,'stock'=>59,'new'=>0,'featured'=>0,'short_description'=>'Kingston Fury 1TB Gen 4 SSD with 7300 MB/s read speeds and optional 2mm heatsink.','description'=>'<p>Fury Renegade delivers Gen 4 flagship speeds at a competitive price. Kingston\'s high-quality 3D NAND and custom controller ensure consistent performance under sustained workloads. The optional 2mm low-profile heatsink fits within standard M.2 slots with thermal shields.</p><ul><li><strong>Capacity:</strong> 1TB</li><li><strong>Interface:</strong> PCIe 4.0 x4, NVMe 2.0</li><li><strong>Sequential Read:</strong> 7,300 MB/s</li><li><strong>Sequential Write:</strong> 6,000 MB/s</li><li><strong>TBW:</strong> 600 TBW</li><li><strong>Form Factor:</strong> M.2 2280</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-NV-005','name'=>'Seagate FireCuda 530 4TB NVMe SSD','brand'=>'Seagate','category'=>'nvme-ssds','price'=>359.00,'special_price'=>null,'weight'=>0.01,'stock'=>18,'new'=>0,'featured'=>0,'short_description'=>'Seagate FireCuda 530 4TB — highest-capacity Gen 4 SSD with Rescue Data Recovery Service.','description'=>'<p>FireCuda 530 4TB is ideal for video editors and creative professionals who need massive fast storage in a single M.2 slot. Seagate includes 3 years of Rescue Data Recovery Services — a valuable safety net for irreplaceable project files.</p><ul><li><strong>Capacity:</strong> 4TB</li><li><strong>Interface:</strong> PCIe 4.0 x4, NVMe 1.4</li><li><strong>Sequential Read:</strong> 7,300 MB/s</li><li><strong>Sequential Write:</strong> 6,900 MB/s</li><li><strong>TBW:</strong> 5,100 TBW</li><li><strong>Form Factor:</strong> M.2 2280</li><li><strong>Warranty:</strong> 5 years + Rescue Recovery</li></ul>'],
        ];
    }

    private static function sataSsds(): array
    {
        return [
            ['sku'=>'TH-SA-001','name'=>'Samsung 870 EVO 2TB SATA SSD','brand'=>'Samsung','category'=>'sata-ssds','price'=>149.00,'special_price'=>129.00,'weight'=>0.07,'stock'=>72,'new'=>0,'featured'=>1,'short_description'=>'Samsung 870 EVO 2TB SATA — the gold-standard laptop and desktop SSD upgrade for everyday users.','description'=>'<p>Samsung 870 EVO is the definitive SATA SSD upgrade. With 560 MB/s sequential read and Samsung\'s V-NAND reliability, it transforms any old laptop or desktop with a spinning hard drive into a responsive, fast machine. Includes Samsung Magician software for health monitoring.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>Sequential Read:</strong> 560 MB/s</li><li><strong>Sequential Write:</strong> 530 MB/s</li><li><strong>NAND:</strong> Samsung MKX V-NAND MLC + TLC</li><li><strong>TBW:</strong> 1,200 TBW</li><li><strong>Form Factor:</strong> 2.5" (7mm)</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-SA-002','name'=>'Crucial MX500 1TB SATA SSD','brand'=>'Crucial','category'=>'sata-ssds','price'=>69.00,'special_price'=>null,'weight'=>0.04,'stock'=>91,'new'=>0,'featured'=>0,'short_description'=>'Crucial MX500 1TB with AES 256-bit encryption and Micron 3D NAND for reliable everyday storage.','description'=>'<p>MX500 strikes the ideal balance between price, capacity and reliability for mainstream users. Hardware AES 256-bit encryption protects sensitive data, while Integrated Power Loss Immunity preserves saved data if power is unexpectedly cut.</p><ul><li><strong>Capacity:</strong> 1TB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>Sequential Read:</strong> 560 MB/s</li><li><strong>Sequential Write:</strong> 510 MB/s</li><li><strong>NAND:</strong> Micron 3D TLC NAND</li><li><strong>TBW:</strong> 360 TBW</li><li><strong>Form Factor:</strong> 2.5" (7mm)</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-SA-003','name'=>'SanDisk Ultra 3D 2TB SATA SSD','brand'=>'SanDisk','category'=>'sata-ssds','price'=>119.00,'special_price'=>99.00,'weight'=>0.04,'stock'=>56,'new'=>0,'featured'=>0,'short_description'=>'SanDisk Ultra 3D 2TB SATA SSD — nCache 2.0 technology for sustained write performance.','description'=>'<p>SanDisk Ultra 3D uses nCache 2.0 technology — a tiered caching architecture that maintains consistent write speeds even during large sequential transfers. Western Digital\'s 3D NAND provides enhanced durability over planar NAND alternatives.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>Sequential Read:</strong> 560 MB/s</li><li><strong>Sequential Write:</strong> 530 MB/s</li><li><strong>NAND:</strong> WD 3D NAND TLC</li><li><strong>TBW:</strong> 500 TBW</li><li><strong>Form Factor:</strong> 2.5" (7mm)</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-SA-004','name'=>'Kingston A400 960GB SATA SSD','brand'=>'Kingston','category'=>'sata-ssds','price'=>49.00,'special_price'=>null,'weight'=>0.04,'stock'=>108,'new'=>0,'featured'=>0,'short_description'=>'Budget-friendly Kingston A400 960GB — fastest way to speed up an ageing laptop or PC.','description'=>'<p>A400 is Kingston\'s entry-level SATA SSD, delivering 10× the performance of a spinning hard drive at an entry-level price. The performance boost for typical computing tasks like boot times, application launches and file transfers is immediately noticeable.</p><ul><li><strong>Capacity:</strong> 960GB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>Sequential Read:</strong> 500 MB/s</li><li><strong>Sequential Write:</strong> 450 MB/s</li><li><strong>Form Factor:</strong> 2.5" (7mm)</li><li><strong>Warranty:</strong> 3 years</li></ul>'],
        ];
    }

    private static function portableSsds(): array
    {
        return [
            ['sku'=>'TH-PS-001','name'=>'Samsung T7 Shield 2TB Portable SSD','brand'=>'Samsung','category'=>'portable-ssds','price'=>169.00,'special_price'=>139.00,'weight'=>0.10,'stock'=>47,'new'=>0,'featured'=>1,'short_description'=>'Samsung T7 Shield 2TB — IP65 rated, rugged texture finish, 1,050 MB/s USB 3.2 Gen 2 speed.','description'=>'<p>T7 Shield combines Samsung\'s speed with rugged protection. IP65 dust and water resistance, a textured outer shell, and shock-absorbing design make it suitable for field work, travel and outdoor photography. Includes USB-C to USB-C and USB-C to USB-A cables.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> USB 3.2 Gen 2 (10Gbps)</li><li><strong>Sequential Read:</strong> 1,050 MB/s</li><li><strong>Sequential Write:</strong> 1,000 MB/s</li><li><strong>Protection:</strong> IP65 dust and water resistant</li><li><strong>Encryption:</strong> AES 256-bit</li><li><strong>Dimensions:</strong> 88 × 59 × 13.5 mm, 98g</li><li><strong>Warranty:</strong> 3 years</li></ul>'],
            ['sku'=>'TH-PS-002','name'=>'WD My Passport SSD 4TB Portable','brand'=>'WD','category'=>'portable-ssds','price'=>249.00,'special_price'=>null,'weight'=>0.09,'stock'=>29,'new'=>1,'featured'=>0,'short_description'=>'WD My Passport SSD 4TB — 1050 MB/s speed in pocket size with password protection.','description'=>'<p>My Passport SSD 4TB packs a massive capacity into a pocket-friendly form. Password protection with hardware encryption keeps your data safe, and the included WD Discovery software provides automatic cloud backup integration with Dropbox and Google Drive.</p><ul><li><strong>Capacity:</strong> 4TB</li><li><strong>Interface:</strong> USB 3.2 Gen 2 (10Gbps)</li><li><strong>Sequential Read:</strong> 1,050 MB/s</li><li><strong>Sequential Write:</strong> 1,000 MB/s</li><li><strong>Encryption:</strong> AES 256-bit hardware encryption</li><li><strong>Weight:</strong> 100g</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-PS-003','name'=>'SanDisk Extreme Pro 2TB Portable SSD V2','brand'=>'SanDisk','category'=>'portable-ssds','price'=>179.00,'special_price'=>149.00,'weight'=>0.08,'stock'=>38,'new'=>0,'featured'=>0,'short_description'=>'SanDisk Extreme Pro 2TB V2 — 2000 MB/s USB 3.2 Gen 2×2 speed with IP55 protection.','description'=>'<p>Extreme Pro V2 is one of the fastest portable SSDs available, leveraging USB 3.2 Gen 2×2 (20Gbps) for up to 2000 MB/s reads. IP55 dust and splash resistance makes it suitable for demanding outdoor environments. ForceField technology adds drop resistance up to 2 metres.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> USB 3.2 Gen 2×2 (20Gbps)</li><li><strong>Sequential Read:</strong> 2,000 MB/s</li><li><strong>Sequential Write:</strong> 2,000 MB/s</li><li><strong>Protection:</strong> IP55, 2m drop resistant</li><li><strong>Encryption:</strong> 256-bit AES</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-PS-004','name'=>'Crucial X9 Pro 1TB Portable SSD','brand'=>'Crucial','category'=>'portable-ssds','price'=>79.00,'special_price'=>null,'weight'=>0.04,'stock'=>61,'new'=>0,'featured'=>0,'short_description'=>'Crucial X9 Pro 1TB — compact, durable portable SSD with 1050 MB/s speed and IP55 protection.','description'=>'<p>X9 Pro is Crucial\'s compact rugged portable SSD. At just 38g it weighs almost nothing in a bag or pocket, yet delivers 1050 MB/s transfer speeds and IP55 water and dust resistance. No software required — simply plug in and use on any USB-C or USB-A device.</p><ul><li><strong>Capacity:</strong> 1TB</li><li><strong>Interface:</strong> USB 3.2 Gen 2 (10Gbps)</li><li><strong>Sequential Read:</strong> 1,050 MB/s</li><li><strong>Sequential Write:</strong> 1,000 MB/s</li><li><strong>Protection:</strong> IP55</li><li><strong>Weight:</strong> 38g</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-PS-005','name'=>'Kingston XS2000 2TB Portable SSD','brand'=>'Kingston','category'=>'portable-ssds','price'=>129.00,'special_price'=>null,'weight'=>0.05,'stock'=>44,'new'=>0,'featured'=>0,'short_description'=>'Kingston XS2000 2TB — IP55 portable SSD with 2000 MB/s USB 3.2 Gen 2×2 in a small, pocket-sized form.','description'=>'<p>XS2000 is Kingston\'s fastest portable SSD, utilising the Gen 2×2 USB interface to achieve 2000 MB/s transfer speeds. The tiny form factor (69.54 × 32.58 × 13.5 mm) makes it one of the most portable high-speed drives available.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> USB 3.2 Gen 2×2 (20Gbps)</li><li><strong>Sequential Read:</strong> 2,000 MB/s</li><li><strong>Sequential Write:</strong> 2,000 MB/s</li><li><strong>Protection:</strong> IP55</li><li><strong>Dimensions:</strong> 69.54 × 32.58 × 13.5 mm, 28.1g</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
        ];
    }

    private static function hardDrives(): array
    {
        return [
            ['sku'=>'TH-HD-001','name'=>'Seagate Barracuda 4TB 3.5" HDD','brand'=>'Seagate','category'=>'hard-drives','price'=>69.00,'special_price'=>null,'weight'=>0.43,'stock'=>93,'new'=>0,'featured'=>0,'short_description'=>'Seagate Barracuda 4TB 3.5" SATA desktop hard drive — reliable everyday storage at a low cost per GB.','description'=>'<p>Barracuda 4TB delivers 4TB of reliable storage at a cost per gigabyte that SSDs cannot match. With a 256MB cache and 7200 RPM spindle speed, it provides solid sequential transfer rates for data archiving, media libraries, and desktop secondary storage.</p><ul><li><strong>Capacity:</strong> 4TB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>RPM:</strong> 7200</li><li><strong>Cache:</strong> 256MB</li><li><strong>Sequential Transfer:</strong> ~190 MB/s</li><li><strong>Form Factor:</strong> 3.5"</li><li><strong>Warranty:</strong> 2 years</li></ul>'],
            ['sku'=>'TH-HD-002','name'=>'WD Red Pro 8TB NAS Hard Drive','brand'=>'WD','category'=>'hard-drives','price'=>199.00,'special_price'=>null,'weight'=>0.75,'stock'=>34,'new'=>0,'featured'=>0,'short_description'=>'WD Red Pro 8TB NAS-optimised HDD with CMR recording, vibration compensation and 300TB/year workload rating.','description'=>'<p>WD Red Pro is engineered specifically for always-on NAS environments. CMR recording technology ensures reliable performance under sustained workloads, while 3D Active Balance Plus vibration compensation keeps performance high in multi-drive NAS enclosures of up to 24 bays.</p><ul><li><strong>Capacity:</strong> 8TB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>RPM:</strong> 7200</li><li><strong>Cache:</strong> 256MB</li><li><strong>Workload Rate:</strong> 300TB/year</li><li><strong>Form Factor:</strong> 3.5"</li><li><strong>Warranty:</strong> 5 years</li></ul>'],
            ['sku'=>'TH-HD-003','name'=>'Seagate IronWolf Pro 16TB NAS HDD','brand'=>'Seagate','category'=>'hard-drives','price'=>349.00,'special_price'=>null,'weight'=>0.68,'stock'=>17,'new'=>0,'featured'=>0,'short_description'=>'Seagate IronWolf Pro 16TB — enterprise-class NAS drive with 300TB/year workload and 3-year Rescue Recovery.','description'=>'<p>IronWolf Pro 16TB is Seagate\'s highest-capacity NAS drive, built for rackmount NAS enclosures with up to 24 bays. The AgileArray firmware optimises RAID performance, and 3 years of Rescue Data Recovery Services provide peace of mind for business-critical data.</p><ul><li><strong>Capacity:</strong> 16TB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>RPM:</strong> 7200</li><li><strong>Cache:</strong> 256MB</li><li><strong>Workload Rate:</strong> 300TB/year</li><li><strong>MTBF:</strong> 1.2 million hours</li><li><strong>Warranty:</strong> 5 years + Rescue Recovery</li></ul>'],
            ['sku'=>'TH-HD-004','name'=>'WD Blue 2TB 2.5" Laptop HDD','brand'=>'WD','category'=>'hard-drives','price'=>49.00,'special_price'=>null,'weight'=>0.10,'stock'=>61,'new'=>0,'featured'=>0,'short_description'=>'WD Blue 2TB 2.5" laptop hard drive — affordable secondary storage upgrade for notebooks.','description'=>'<p>WD Blue 2TB 2.5" provides a cost-effective way to add secondary storage to laptops with a spare drive bay, or to store media and archives without paying SSD prices. At 5400 RPM with 128MB cache, it balances capacity, power consumption and noise for portable use.</p><ul><li><strong>Capacity:</strong> 2TB</li><li><strong>Interface:</strong> SATA III 6Gb/s</li><li><strong>RPM:</strong> 5400</li><li><strong>Cache:</strong> 128MB</li><li><strong>Form Factor:</strong> 2.5" (7mm)</li><li><strong>Warranty:</strong> 2 years</li></ul>'],
            ['sku'=>'TH-HD-005','name'=>'Seagate Expansion Desktop 8TB External HDD','brand'=>'Seagate','category'=>'hard-drives','price'=>129.00,'special_price'=>109.00,'weight'=>0.82,'stock'=>43,'new'=>0,'featured'=>0,'short_description'=>'Seagate Expansion 8TB desktop external hard drive — plug-and-play backup for PC and Mac.','description'=>'<p>Seagate Expansion 8TB provides straightforward plug-and-play external storage. No software required — just connect the USB cable and it mounts as a drive on Windows or Mac. Ideal for Time Machine backups, media libraries, or game storage expansion.</p><ul><li><strong>Capacity:</strong> 8TB</li><li><strong>Interface:</strong> USB 3.0</li><li><strong>Form Factor:</strong> Desktop (external)</li><li><strong>Power:</strong> AC adapter included</li><li><strong>Compatibility:</strong> Windows / macOS / Xbox / PlayStation</li><li><strong>Warranty:</strong> 2 years</li></ul>'],
            ['sku'=>'TH-HD-006','name'=>'WD Elements Desktop 12TB External HDD','brand'=>'WD','category'=>'hard-drives','price'=>189.00,'special_price'=>null,'weight'=>0.95,'stock'=>28,'new'=>0,'featured'=>0,'short_description'=>'WD Elements Desktop 12TB — high-capacity USB 3.0 external storage for creative archives and backups.','description'=>'<p>Elements Desktop 12TB offers the highest per-dollar storage for users archiving large media collections. The solid, compact desktop enclosure keeps the drive cool and quiet. Compatible with macOS Time Machine and Windows Backup for seamless scheduled backups.</p><ul><li><strong>Capacity:</strong> 12TB</li><li><strong>Interface:</strong> USB 3.0</li><li><strong>Form Factor:</strong> Desktop (external)</li><li><strong>Power:</strong> AC adapter included</li><li><strong>Compatibility:</strong> Windows / macOS</li><li><strong>Warranty:</strong> 3 years</li></ul>'],
        ];
    }
}
