<?php

namespace Database\Seeders\ProductData;

class WearableData
{
    public static function get(): array
    {
        return array_merge(
            self::smartwatches(),
            self::fitnessTrackers(),
        );
    }

    private static function smartwatches(): array
    {
        return [
            ['sku'=>'TH-SW-101','name'=>'Apple Watch Series 10 (42mm, GPS + Cellular)','brand'=>'Apple','category'=>'smartwatches','price'=>499.00,'special_price'=>null,'weight'=>0.04,'stock'=>54,'new'=>1,'featured'=>1,'short_description'=>'Apple Watch Series 10 — thinnest Apple Watch ever, wider LTPO display and new sleep apnea detection.','description'=>'<p>Apple Watch Series 10 is the thinnest Apple Watch Apple has made, with the largest display yet on the standard model thanks to reduced bezels. New in Series 10: FDA-cleared sleep apnea detection monitors your breathing while sleeping and alerts you if irregular patterns are detected. The S10 SiP enables faster on-device processing for Siri and Health features.</p><ul><li><strong>Chip:</strong> S10 SiP</li><li><strong>Display:</strong> 42mm LTPO Always-On Retina</li><li><strong>Health:</strong> Sleep apnea detection (FDA-cleared), ECG, Blood Oxygen, Heart Rate</li><li><strong>Battery:</strong> 18 hours (36 hours low power)</li><li><strong>Water Resistance:</strong> 50 metres (IP6X dust)</li><li><strong>Connectivity:</strong> GPS + Cellular (LTE/UMTS)</li></ul>'],
            ['sku'=>'TH-SW-102','name'=>'Apple Watch Ultra 2 (49mm, GPS + Cellular)','brand'=>'Apple','category'=>'smartwatches','price'=>799.00,'special_price'=>null,'weight'=>0.06,'stock'=>21,'new'=>1,'featured'=>1,'short_description'=>'Apple Watch Ultra 2 — titanium case, 2000-nit display, 60-hour battery and EN 13319 dive computer.','description'=>'<p>Apple Watch Ultra 2 is designed for extreme athletes, mountaineers, and divers. The 49mm titanium case, sapphire crystal display (rated to 2000 nits), and 100-metre water resistance handle conditions that would destroy a standard Apple Watch. The Action button provides customisable one-tap workout controls even with gloves on.</p><ul><li><strong>Chip:</strong> S9 SiP + ultra-wideband U2</li><li><strong>Display:</strong> 49mm LTPO Retina, 2000 nits</li><li><strong>Case:</strong> Grade 5 titanium</li><li><strong>Battery:</strong> 60 hours (36 hours with optimised GPS)</li><li><strong>Water Resistance:</strong> 100 metres (EN 13319 dive computer)</li><li><strong>Satellite:</strong> Emergency SOS via satellite</li></ul>'],
            ['sku'=>'TH-SW-103','name'=>'Samsung Galaxy Watch 7 (44mm, LTE)','brand'=>'Samsung','category'=>'smartwatches','price'=>299.00,'special_price'=>269.00,'weight'=>0.03,'stock'=>44,'new'=>1,'featured'=>0,'short_description'=>'Samsung Galaxy Watch 7 44mm — BioActive sensor, sleep coaching and 3nm Exynos W1000 processor.','description'=>'<p>Galaxy Watch 7 is the fastest Samsung smartwatch ever, powered by the 3nm Exynos W1000 — 50% faster than the previous chip. Galaxy AI enables personalised sleep coaching that analyses 18 sleep metrics and provides actionable insights for improving sleep quality. BioActive sensor measures ECG, blood glucose trends, and body composition.</p><ul><li><strong>Processor:</strong> Exynos W1000 (3nm)</li><li><strong>Display:</strong> 1.47" Super AMOLED Always-On</li><li><strong>Health:</strong> ECG, Blood Pressure, Body Composition, Sleep Coaching</li><li><strong>Battery:</strong> 40 hours</li><li><strong>Water Resistance:</strong> 5ATM + IP68</li><li><strong>OS:</strong> Wear OS + One UI Watch 6</li></ul>'],
            ['sku'=>'TH-SW-104','name'=>'Garmin Fenix 7X Solar Sapphire (51mm)','brand'=>'Garmin','category'=>'smartwatches','price'=>899.00,'special_price'=>799.00,'weight'=>0.09,'stock'=>16,'new'=>0,'featured'=>0,'short_description'=>'Garmin Fenix 7X Solar Sapphire — solar charging, 28-day battery, topographic maps and multi-sport GPS.','description'=>'<p>Fenix 7X Solar Sapphire is the ultimate multisport GPS watch for adventurers. Solar charging extends battery life beyond 28 days in expedition mode, while full-colour topographic maps with turn-by-turn navigation work without a phone connection. Built-in flashlight illuminates trails for night running. Sapphire crystal lens resists scratches in rugged environments.</p><ul><li><strong>Battery:</strong> 28 days (smartwatch), 89 hours (GPS), 28 days (expedition solar)</li><li><strong>Solar:</strong> Power Glass solar charging</li><li><strong>Display:</strong> 1.4" memory-in-pixel, 240×240</li><li><strong>Navigation:</strong> Topo maps, turn-by-turn, ClimbPro</li><li><strong>Sports:</strong> 40+ sport modes, triathlon, swim, ski, golf</li><li><strong>Water Resistance:</strong> 10ATM (100m)</li></ul>'],
            ['sku'=>'TH-SW-105','name'=>'Garmin Venu 3S (41mm)','brand'=>'Garmin','category'=>'smartwatches','price'=>449.00,'special_price'=>null,'weight'=>0.03,'stock'=>31,'new'=>1,'featured'=>0,'short_description'=>'Garmin Venu 3S — AMOLED always-on display, nap detection, wheelchair mode and 10-day battery.','description'=>'<p>Venu 3S is Garmin\'s AMOLED lifestyle smartwatch with 10-day battery life — exceptional for an always-on display. New features include nap detection with recovery insights and a dedicated wheelchair mode with push detection and wheeling metrics. Body Battery energy monitoring tells you when to push hard and when to rest.</p><ul><li><strong>Display:</strong> 1.2" AMOLED always-on</li><li><strong>Battery:</strong> 10 days (smartwatch), 14 days (battery saver)</li><li><strong>Health:</strong> Body Battery, Nap Detection, Sleep Score, HRV, ECG</li><li><strong>Sports:</strong> 25+ sport modes</li><li><strong>New:</strong> Wheelchair mode, nap detection</li></ul>'],
            ['sku'=>'TH-SW-106','name'=>'Samsung Galaxy Watch Ultra 47mm','brand'=>'Samsung','category'=>'smartwatches','price'=>649.00,'special_price'=>null,'weight'=>0.06,'stock'=>18,'new'=>1,'featured'=>0,'short_description'=>'Samsung Galaxy Watch Ultra — titanium case, 3-day battery, multi-sport and advanced health monitoring.','description'=>'<p>Galaxy Watch Ultra is Samsung\'s first premium rugged smartwatch, featuring a titanium case with a unique side rail that provides additional impact protection without adding bulk. The improved BioActive sensor extends blood pressure monitoring to detect trends over time rather than single readings.</p><ul><li><strong>Case:</strong> Grade 4 titanium</li><li><strong>Display:</strong> 1.47" Super AMOLED, 3000 nits</li><li><strong>Battery:</strong> 3 days (smartwatch) / 48 hours (sport mode)</li><li><strong>Water Resistance:</strong> 10ATM + IP68 + MIL-STD-810H</li><li><strong>Health:</strong> ECG, Blood Pressure, Body Composition, Sleep Coaching</li></ul>'],
            ['sku'=>'TH-SW-107','name'=>'Apple Watch SE (2nd Gen, 40mm, GPS)','brand'=>'Apple','category'=>'smartwatches','price'=>249.00,'special_price'=>null,'weight'=>0.03,'stock'=>67,'new'=>0,'featured'=>0,'short_description'=>'Apple Watch SE 2nd gen — the most affordable Apple Watch with Crash Detection and Family Setup.','description'=>'<p>Apple Watch SE 2nd gen is the entry point to the Apple Watch ecosystem with Crash Detection, Emergency SOS, and Family Setup (a child can use it independently without their own iPhone). The S8 SiP delivers the same chip performance as Apple Watch Series 8 in a streamlined package.</p><ul><li><strong>Chip:</strong> S8 SiP</li><li><strong>Display:</strong> Always-On Retina LTPO</li><li><strong>Safety:</strong> Crash Detection, Emergency SOS, Fall Detection</li><li><strong>Family Setup:</strong> Yes (independent cellular without paired iPhone)</li><li><strong>Battery:</strong> 18 hours</li><li><strong>Water Resistance:</strong> 50 metres</li></ul>'],
            ['sku'=>'TH-SW-108','name'=>'Garmin Instinct 2X Solar Tactical','brand'=>'Garmin','category'=>'smartwatches','price'=>499.00,'special_price'=>null,'weight'=>0.08,'stock'=>23,'new'=>0,'featured'=>0,'short_description'=>'Garmin Instinct 2X Solar Tactical — unlimited solar battery, NVG mode, kill switch and stealth mode.','description'=>'<p>Instinct 2X Solar Tactical adds military-specific features including NVG (night-vision goggle) mode with compatible display backlight settings, a kill switch that disables wireless features on command, and stealth mode that disables all wireless signals. Unlimited battery in direct sunlight makes it the GPS watch of choice for extended field operations.</p><ul><li><strong>Solar:</strong> Unlimited battery in sunlight (solar only mode)</li><li><strong>Display:</strong> MIP (transflective, visible in bright sunlight)</li><li><strong>Tactical:</strong> NVG mode, kill switch, stealth mode</li><li><strong>Water Resistance:</strong> 10ATM (100m)</li><li><strong>MIL-STD:</strong> 810H</li><li><strong>Navigation:</strong> GPS/GLONASS/Galileo</li></ul>'],
            ['sku'=>'TH-SW-109','name'=>'Samsung Galaxy Watch 6 Classic 47mm','brand'=>'Samsung','category'=>'smartwatches','price'=>399.00,'special_price'=>349.00,'weight'=>0.06,'stock'=>38,'new'=>0,'featured'=>0,'short_description'=>'Samsung Galaxy Watch 6 Classic 47mm — rotating bezel, Sapphire Crystal and 40-hour battery.','description'=>'<p>Galaxy Watch 6 Classic brings back the iconic rotating bezel that loyal Samsung watch fans have missed — physical rotation navigates menus and dials without touching the display. Sapphire crystal glass provides scratch resistance that the standard Watch 6 lacks. The larger 47mm case accommodates a bigger battery for 40-hour runtime.</p><ul><li><strong>Bezel:</strong> Physical rotating bezel</li><li><strong>Crystal:</strong> Sapphire</li><li><strong>Display:</strong> 1.5" Super AMOLED</li><li><strong>Battery:</strong> 40 hours</li><li><strong>Health:</strong> ECG, Blood Pressure, Body Composition, Sleep</li><li><strong>OS:</strong> Wear OS + One UI Watch 5</li></ul>'],
        ];
    }

    private static function fitnessTrackers(): array
    {
        return [
            ['sku'=>'TH-FT-001','name'=>'Fitbit Charge 6','brand'=>'Fitbit','category'=>'fitness-trackers','price'=>159.00,'special_price'=>null,'weight'=>0.03,'stock'=>73,'new'=>1,'featured'=>1,'short_description'=>'Fitbit Charge 6 — built-in GPS, ECG app, Google Maps integration and 7-day battery life.','description'=>'<p>Charge 6 is the most advanced Fitbit tracker, adding built-in GPS (no phone required for accurate run routes) and an ECG app alongside the comprehensive health suite Fitbit is known for. Google integration brings Google Maps directions and Google Wallet NFC payments to your wrist.</p><ul><li><strong>GPS:</strong> Built-in (no phone required)</li><li><strong>Health:</strong> ECG, heart rate (24/7), SpO2, skin temperature, stress</li><li><strong>Payment:</strong> Google Wallet NFC</li><li><strong>Battery:</strong> 7 days</li><li><strong>Water Resistance:</strong> 50 metres</li><li><strong>Display:</strong> 1.04" AMOLED</li></ul>'],
            ['sku'=>'TH-FT-002','name'=>'Garmin Vivosmart 5','brand'=>'Garmin','category'=>'fitness-trackers','price'=>149.00,'special_price'=>129.00,'weight'=>0.03,'stock'=>48,'new'=>0,'featured'=>0,'short_description'=>'Garmin Vivosmart 5 — slim clip-style tracker with Body Battery, SpO2 and up to 7-day battery.','description'=>'<p>Vivosmart 5 is Garmin\'s slim lifestyle tracker, featuring the company\'s Body Battery energy monitoring that synthesises heart rate variability, stress, and sleep data to estimate how energised you are throughout the day. Respiration tracking and Pulse Ox (SpO2) monitoring run continuously in the background.</p><ul><li><strong>Display:</strong> 0.26" monochrome OLED (touchscreen)</li><li><strong>Health:</strong> Body Battery, SpO2, HRV, Stress, Respiration</li><li><strong>Battery:</strong> 7 days</li><li><strong>Water Resistance:</strong> 5ATM</li><li><strong>Fitness:</strong> Step counting, floors climbed, intensity minutes</li></ul>'],
            ['sku'=>'TH-FT-003','name'=>'Fitbit Inspire 3','brand'=>'Fitbit','category'=>'fitness-trackers','price'=>99.00,'special_price'=>null,'weight'=>0.02,'stock'=>86,'new'=>0,'featured'=>0,'short_description'=>'Fitbit Inspire 3 — 10-day battery, colour display, stress management score and Fitbit Premium trial.','description'=>'<p>Inspire 3 is Fitbit\'s entry-level fitness tracker, upgraded with a colour AMOLED display and a Stress Management Score derived from heart rate variability. 10-day battery life means you need to charge it just twice a month. Every purchase includes a 6-month Fitbit Premium trial with guided workouts and mindfulness sessions.</p><ul><li><strong>Display:</strong> Colour AMOLED touchscreen</li><li><strong>Health:</strong> Heart rate, SpO2, stress, sleep, HRV</li><li><strong>Battery:</strong> 10 days</li><li><strong>Water Resistance:</strong> 50 metres</li><li><strong>Premium:</strong> 6-month Fitbit Premium included</li></ul>'],
            ['sku'=>'TH-FT-004','name'=>'Garmin Lily 2 Sport','brand'=>'Garmin','category'=>'fitness-trackers','price'=>199.00,'special_price'=>null,'weight'=>0.02,'stock'=>34,'new'=>1,'featured'=>0,'short_description'=>'Garmin Lily 2 Sport — ultra-slim patterned lens design with menstrual cycle tracking and 5-day GPS battery.','description'=>'<p>Lily 2 Sport is Garmin\'s fashion-forward fitness tracker with a unique patterned lens that conceals the display until activated, resembling jewellery more than technology. Despite its slim profile, it includes GPS tracking, menstrual cycle health tracking, sleep score, and Body Battery monitoring.</p><ul><li><strong>Display:</strong> 0.84" hidden-lens OLED</li><li><strong>Health:</strong> Body Battery, menstrual cycle, stress, SpO2, sleep</li><li><strong>GPS:</strong> Built-in</li><li><strong>Battery:</strong> 5 days with GPS, 7 days smartwatch</li><li><strong>Weight:</strong> 24g</li></ul>'],
            ['sku'=>'TH-FT-005','name'=>'Fitbit Luxe Special Edition','brand'=>'Fitbit','category'=>'fitness-trackers','price'=>129.00,'special_price'=>null,'weight'=>0.02,'stock'=>52,'new'=>0,'featured'=>0,'short_description'=>'Fitbit Luxe Special Edition — slim metallic design with a Gorjana accessory band and stress management.','description'=>'<p>Fitbit Luxe Special Edition comes with a premium Gorjana accessory link bracelet in addition to the standard silicone band, enabling you to wear it as jewellery during formal occasions. Advanced sleep tracking with Sleep Score, continuous heart rate, and Stress Management Score in an ultra-slim form factor.</p><ul><li><strong>Display:</strong> 0.76" colour AMOLED</li><li><strong>Health:</strong> Heart rate, SpO2, stress, sleep, HRV</li><li><strong>Includes:</strong> Silicone band + Gorjana link bracelet</li><li><strong>Battery:</strong> 5 days</li><li><strong>Water Resistance:</strong> 50 metres</li></ul>'],
            ['sku'=>'TH-FT-006','name'=>'Samsung Galaxy Fit3','brand'=>'Samsung','category'=>'fitness-trackers','price'=>59.00,'special_price'=>null,'weight'=>0.02,'stock'=>97,'new'=>1,'featured'=>0,'short_description'=>'Samsung Galaxy Fit3 — 1.6" AMOLED display, 13-day battery and 100+ workout modes at an accessible price.','description'=>'<p>Galaxy Fit3 is the best-value fitness tracker in the Samsung ecosystem. The 1.6" AMOLED display is noticeably larger than competing trackers in this price range, and 100 workout modes track everything from yoga to cycling with automatic activity recognition. 13-day battery life makes it ideal for travel.</p><ul><li><strong>Display:</strong> 1.6" AMOLED colour touchscreen</li><li><strong>Health:</strong> Heart rate, SpO2, stress, sleep</li><li><strong>Workout Modes:</strong> 100+ (auto-detection)</li><li><strong>Battery:</strong> 13 days</li><li><strong>Water Resistance:</strong> 5ATM + IP68</li></ul>'],
            ['sku'=>'TH-FT-007','name'=>'Garmin Forerunner 265 Music Running Watch','brand'=>'Garmin','category'=>'fitness-trackers','price'=>449.00,'special_price'=>null,'weight'=>0.05,'stock'=>27,'new'=>1,'featured'=>0,'short_description'=>'Garmin Forerunner 265 — AMOLED display, running dynamics, music storage and training readiness score.','description'=>'<p>Forerunner 265 targets serious runners who want an AMOLED display without sacrificing GPS accuracy. Advanced running dynamics measure ground contact time, vertical oscillation, and stride length to identify form improvements. Training Readiness score tells you each morning whether to push hard or recover based on HRV, sleep, and recovery data.</p><ul><li><strong>Display:</strong> 1.3" AMOLED always-on</li><li><strong>Running Metrics:</strong> Running Dynamics, Race Predictor, Recovery Advisor</li><li><strong>Training:</strong> Training Readiness, HRV Status</li><li><strong>Music:</strong> 650 songs storage + Spotify sync</li><li><strong>Battery:</strong> 13 days (smartwatch), 20 hours (GPS)</li><li><strong>Water Resistance:</strong> 5ATM</li></ul>'],
        ];
    }
}
